### ISSUE TITLE
Cipher tool fails to encrypt the fields

### ISSUE THREAD

**Issue by jsonds** [wso2/product-iots#1003]
On a fresh pack tried to run the cipher tool from the below mentioned 3 locations and all 3 attempts failed. 

**1. Core - wso2iot-3.1.0-SNAPSHOT/bin**
```
jason@jason-ThinkPad-T540p:~/Products/IOT301/M8/wso2iot-3.1.0-SNAPSHOT/bin$ ./ciphertool.sh -Dconfigure
Exception in thread "main" org.wso2.ciphertool.exception.CipherToolException: File, cipher-standalone-config.properties does not exist.
	at org.wso2.ciphertool.utils.Utils.setSystemProperties(Utils.java:247)
	at org.wso2.ciphertool.CipherTool.initialize(CipherTool.java:93)
	at org.wso2.ciphertool.CipherTool.main(CipherTool.java:52)
```

**2. Analytics - wso2iot-3.1.0-SNAPSHOT/wso2/analytics/bin**
`Error: Could not find or load main class org.wso2.ciphertool.CipherTool`

**3. Broker - wso2iot-3.1.0-SNAPSHOT/wso2/broker/bin**

`Error: Could not find or load main class org.wso2.ciphertool.CipherTool`

**Comment by jsonds** [comment]
**Labels -** 3.1.0-M8, blocker, bug

**Comment by sinthuja** [comment]
Fix is committed. The cipher tool script can be executed from PRODUCT_HOME location as './bin/cipher-tool.sh -Dconfigure'.
