### ISSUE TITLE
Error thrown when shutting down server -  Can not unsubscribe from the destination

### ISSUE THREAD

**Issue by jsonds** [wso2/product-iots#1015]
**Steps**

1. Start the server with start-all.sh script
2. Shut-down the server with stop-all.sh script or CTRL+C

In both occasions when shutting down the below exception is thrown.
```
[2017-06-15 11:17:24,460] [IoT-Analytics] ERROR {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  Can not unsubscribe from the destination carbon.super/android_sense/+/data with the event adapter android_sense_receiver-carbon.super
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 more
[2017-06-15 11:17:24,461] [IoT-Analytics]  WARN {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  MQTT connection not reachable Connection lost (32109) - java.io.EOFException

```

**Comment by jsonds** [comment]
**Labels -** 3.1.0-M8, Bug, High

**Comment by milanperera** [comment]
This occurs when the broker is stopped before stopping the analytics and iot core servers.
The correct shutting down order is analytics, core and then broker.
Even if the stop-all script does the same thing, sometimes analytics server takes time to shutdown, while broker gets stopped before the analytics server gets down, hence results the same error.
