### ISSUE TITLE
If mailto is not configured, do not attempt to send mails

### ISSUE THREAD

**Issue by sumedharubasinghe** [wso2/product-iots#1035]
If mailto is not configured, do not attempt to send mails. Provide that as an information (e.g.: 'Mail Server is not configured. Email invitation will not be sent')

>>>>>>>
[2017-06-22 18:56:06,052] [IoT-Core] ERROR - {org.wso2.carbon.email.sender.core.service.EmailSenderServiceImpl} Error occurred while delivering the message, subject: 'You have successfully been registered in WSO2 IoT', to: 'xyz@abc.com'
org.apache.axis2.AxisFault: The system cannot infer the transport information from the mailto:sxyz@abc.com URL.
	at org.apache.axis2.description.ClientUtils.inferOutTransport(ClientUtils.java:81)
	at org.apache.axis2.client.OperationClient.prepareMessageContext(OperationClient.java:288)

**Comment by menakaj** [comment]
#1360
