### ISSUE TITLE
[Sample] Unable to run the sample mobile-qsg.jar in Windows

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1061]
**Pre-Conditions:-**
- OS Should be Windows (Tested with Server 2012 R2)
- Configure the server to access via IP as explained in [1]
- IoT Server should be up and running

**Steps:-**
1. Go to {$HOME}\samples\mobile-qsg directory
2. Execute java -jar mobile-qsg.jar command
3. Observe the output

**Expected Results:-**
- The sample should be successfully uploaded.

**Actual Results:-**
- Following output is given

C:\Users\Administrator\Downloads\wso2iot-3.1.0-alpha\samples\mobile-qsg>java -jar mobile-qsg.jar
Creating users
Creating iotMobileUser role
Adding sample policies
Upload the android application
**Unable to upload the sample android application. Terminating the IoTS QSG now.**

Note:-
Tested the same on a Mac on a vanilla pack it worked as expected.

[1] https://docs.wso2.com/display/IoTS310/Configuring+WSO2+IoT+Server+with+the+IP

**Comment by pubudup** [comment]
The following exception could be also seen in logs when executing the above jar.

`[2017-06-27 06:30:35,733] [IoT-Core] ERROR - {org.wso2.carbon.appmgt.rest.api.util.exception.GlobalThrowableMapper} An Unknown exception has been captured by global exception mapper.
java.lang.IllegalArgumentException: File '090572005e2addca.apk' is not within the required directory.
        at org.wso2.carbon.appmgt.impl.utils.AppManagerUtil.resolvePath(AppManagerUtil.java:4036)
        at org.wso2.carbon.appmgt.rest.api.util.utils.RestApiUtil.transferFile(RestApiUtil.java:522)
        at org.wso2.carbon.appmgt.rest.api.publisher.utils.RestApiPublisherUtils.uploadFileIntoStorage(RestApiPublisherUtils.java:73)
        at org.wso2.carbon.appmgt.rest.api.publisher.impl.AppsApiServiceImpl.appsMobileBinariesPost(AppsApiServiceImpl.java:156)
        at org.wso2.carbon.appmgt.rest.api.publisher.AppsApi.appsMobileBinariesPost(AppsApi.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:212)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
        at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
        at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
        at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:45)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
[2017-06-27 06:30:58,123] [IoT-Core] ERROR - {org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl} Invalid OAuth Token : Invalid access token
[2017-06-27 06:30:58,139] [IoT-Core]  WARN - {org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler} API authentication failure due to Invalid Credentials
[2017-06-27 06:30:58,342] [IoT-Core]  INFO - {org.wso2.carbon.apimgt.gateway.handlers.security.APIKeyValidator} Invalid OAuth Token : Access Token 842b939d-7e1c-32ac-ac79-a89822b85211 expired.
[2017-06-27 06:30:58,358] [IoT-Core]  WARN - {org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler} API authentication failure due to Invalid Credentials
`

**Comment by inoshperera** [comment]
FIxed with https://github.com/wso2/carbon-appmgt/pull/655

**Comment by pubudup** [comment]
The following exception is triggered when tried out the above steps. 

OS: Windows 2012 R2

`C:\Users\Administrator\Downloads\Beta\wso2iot-3.1.0-beta\wso2iot-3.1.0-beta\samples\mobile-qsg>java -jar mobile-qsg.jar
Exception in thread "main" java.lang.NullPointerException
        at org.wso2.mdm.qsg.utils.QSGUtils.getOAuthToken(QSGUtils.java:104)
        at org.wso2.mdm.qsg.QSGExecutor.main(QSGExecutor.java:59)`

**Comment by pubudup** [comment]
@chamaraanu , @inoshperera : Please review my comment above and reopen this ticket. Thanks!

**Comment by pubudup** [comment]
@geethkokila , @madhawap : Please reopen this ticket as per the comment above. Thanks!

**Comment by inoshperera** [comment]
This seems like a new issue and not reproducible in Windows 10. Seems like this has to be tested on Windows 2012 R2

**Comment by pubudup** [comment]
Tried this in mac os by executing the relevant .sh file as explained in the doc. Still got the same error.

`Admins-MacBook-Pro:mobile-qsg pubudup$ sh mobile-qsg.sh
Starting wso2iots-3.0.0 QSG setup ...
Exception in thread "main" java.lang.NullPointerException
	at org.wso2.mdm.qsg.utils.QSGUtils.getOAuthToken(QSGUtils.java:104)
	at org.wso2.mdm.qsg.QSGExecutor.main(QSGExecutor.java:59)
wso2iots-3.0.0 QSG setup completed.`

**Comment by inoshperera** [comment]
closing with https://github.com/wso2/product-iots/pull/1123

**Comment by pubudup** [comment]
Verified in 3.1.0-RC
