### ISSUE TITLE
iOS mobile-qsg script throws an exception

### ISSUE THREAD

**Issue by sherenem** [wso2/product-iots#1107]
The following exception occurs when running the mobile-qsg script after configuring IOTS for iOS with the ios-feature-deployer and ios-configurator.

Exception in thread "main" java.lang.NullPointerException
       	at org.wso2.mdm.qsg.utils.QSGUtils.getOAuthToken(QSGUtils.java:104)
       	at org.wso2.mdm.qsg.QSGExecutor.main(QSGExecutor.java:59)

**Comment by madhawap** [comment]
This issue will be addressed in https://github.com/wso2/product-iots/issues/1061. Hence closed.
