### ISSUE TITLE
[IoTS/Analytics] An exception on startup in analytics pack even though the cert is imported to the client trust store

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1124]
Pre-Conditions:-
- IoTS should be configured to access via IP as per [1]
- A cert should be created in IoTS with commands given in [2] and imported it to the client trust store of the IoTS analytics with [3]
- Replace localhost with the server IP in below parameters in analytics pack's wso2server.sh or wso2server.bat file (in this case .bat file)
-Dmqtt.broker.host
-Diot.keymanager.host
-Diot.gateway.host

Steps:-
1. Start the broker
2. Start the core
3. Start the analytics 

Expected Results:-
- No error s should be triggered on startup

Actual Results:-
- A cert related error is triggered on start up of the analytics pack eventhough the cert is imported from core

[1] https://docs.wso2.com/display/Carbon420/Configuring+Keystores+in+WSO2+Products
[2]
keytool -genkey -alias 192.168.48.201 -keyalg RSA -keysize 1024 -keypass wso2carbon -keystore wso2carbon.jks -storepass wso2carbon

[provide the CN as hostname when prompted after issuing the above command. In this example 192.168.48.201]

keytool -list -v -keystore wso2carbon.jks -storepass wso2carbon

keytool -export -alias 192.168.48.201 -keystore wso2carbon.jks -storepass wso2carbon -file MYcert.pem

keytool -import -alias 192.168.48.201 -file MYcert.pem -keystore client-truststore.jks -storepass wso2carbon

[3] 

Copy the MYcert.pem in to [IOTS/wso2/analytics/repository/resources/security] and then import the cert into client trust store with the command below.

keytool -import -alias 192.168.48.201 -file MYcert.pem -keystore client-truststore.jks -storepass wso2carbon

[4] Exception from analytics

`2017-07-06 06:49:43,045] [IoT-Analytics] ERROR {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  Failed to create an oauth token with jwt grant type.
org.wso2.carbon.identity.jwt.client.extension.exception.JWTClientException: Error when reading the response from buffer.
        at org.wso2.carbon.identity.jwt.client.extension.JWTClient.getTokenInfo(JWTClient.java:171)
        at org.wso2.carbon.identity.jwt.client.extension.JWTClient.getAccessToken(JWTClient.java:79)
        at org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener.getToken(MQTTAdapterListener.java:338)
        at org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener.startListener(MQTTAdapterListener.java:183)
        at org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener.run(MQTTAdapterListener.java:302)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLException: hostname in certificate didn't match: <localhost> != <192.168.48.201>
        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:231)
        at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)
        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:152)
        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:133)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:291)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:262)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at org.wso2.carbon.identity.jwt.client.extension.JWTClient.getTokenInfo(JWTClient.java:147)
        ... 5 more
[2017-07-06 06:49:56,858] [IoT-Analytics]  INFO {org.wso2.carbon.event.processor.manager.core.internal.CarbonEventManagementService} -  Starting polling event receivers`

**Comment by pubudup** [comment]
@chamaraanu @geethkokila @madhawap : Labels: high, 3.1.0-beta

**Comment by pubudup** [comment]
Checked after applying the changes in [1] except for step 3,4 (optional). Still, this seems to be happening.

[1] https://docs.wso2.com/display/DAS310/Exposing+WSO2+DAS+with+Host+Names

**Comment by lasanthaDLPDS** [comment]
This issue won't reproduce when following instructions in bellow documentations, therefore this issue is closed. 

- https://docs.wso2.com/display/IoTS310/Configuring+WSO2+IoT+Server+with+the+IP
- https://docs.wso2.com/display/ADMIN44x/Creating+New+Keystores
- https://docs.wso2.com/display/IoTS310/Configuring+Keystores+in+WSO2+IoT+Server
