### ISSUE TITLE
[Windows / Sample] An exception triggered in IoT core when executing mobile-qsg sample

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1146]
Pre-Conditions:-
- Configure the IoT server with IP as described at [1]
- Start all 3 core, analytics and broker components
- OS (Tested on Windows 10, Windows 2012 R2)

1. Goto [$HOME/samples/mobile-qsg] directory
2. Execute java -jar mobile-qsg.jar command
3. Observe the logs in IoT core

Expected Results:-
- There should be no error messages

Actual Results:-
- The following error message is triggered when the sample is run in Windows (Tesed in Mac OS but the error is not observed)

`
[2017-07-11 17:57:54,480] [IoT-Core]  INFO - {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} Initializing of policy store is started at :  Tue Jul 11 17:57:54 IST 2017
[2017-07-11 17:57:54,496] [IoT-Core]  INFO - {org.wso2.carbon.identity.entitlement.policy.store.DefaultPolicyDataStore} Using Global policy combining algorithm that is defined in configuration file.
[2017-07-11 17:57:54,496] [IoT-Core]  INFO - {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} Start retrieving policies from org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule@fb02b03 at : Tue Jul 11 17:57:54 IST 2017
[2017-07-11 17:57:54,512] [IoT-Core]  INFO - {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} Finish retrieving policies from org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule@fb02b03 at : Tue Jul 11 17:57:54 IST 2017
[2017-07-11 17:57:54,512] [IoT-Core]  INFO - {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} Initializing of policy store is finished at :  Tue Jul 11 17:57:54 IST 2017
[2017-07-11 17:57:54,621] [IoT-Core]  INFO - {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} Initializing of policy store is started at :  Tue Jul 11 17:57:54 IST 2017
[2017-07-11 17:57:54,652] [IoT-Core]  INFO - {org.wso2.carbon.identity.entitlement.policy.store.DefaultPolicyDataStore} Using Global policy combining algorithm that is defined in configuration file.
[2017-07-11 17:57:54,652] [IoT-Core]  INFO - {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} Start retrieving policies from org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule@fb02b03 at : Tue Jul 11 17:57:54 IST 2017
[2017-07-11 17:57:54,668] [IoT-Core]  INFO - {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} Finish retrieving policies from org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule@fb02b03 at : Tue Jul 11 17:57:54 IST 2017
[2017-07-11 17:57:54,668] [IoT-Core]  INFO - {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} Initializing of policy store is finished at :  Tue Jul 11 17:57:54 IST 2017
[2017-07-11 17:58:00,777] [IoT-Core] ERROR - {org.apache.axis2.description.ClientUtils} The system cannot infer the transport information from the mailto:alex@example.com URL.
[2017-07-11 17:58:00,949] [IoT-Core] ERROR - {org.wso2.carbon.email.sender.core.service.EmailSenderServiceImpl} Error occurred while delivering the message, subject: 'You have successfully been registered in WSO2 IoT', to: 'alex@example.com'
org.apache.axis2.AxisFault: The system cannot infer the transport information from the mailto:alex@example.com URL.
        at org.apache.axis2.description.ClientUtils.inferOutTransport(ClientUtils.java:81)
        at org.apache.axis2.client.OperationClient.prepareMessageContext(OperationClient.java:288)
        at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:249)
        at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
        at org.apache.axis2.client.ServiceClient.fireAndForget(ServiceClient.java:511)
        at org.apache.axis2.client.ServiceClient.fireAndForget(ServiceClient.java:488)
        at org.wso2.carbon.email.sender.core.service.EmailSenderServiceImpl$EmailSender.run(EmailSenderServiceImpl.java:117)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
[2017-07-11 17:58:00,824] [IoT-Core] ERROR - {org.apache.axis2.description.ClientUtils} The system cannot infer the transport information from the mailto:chris@mobx.com URL.
[2017-07-11 17:58:01,184] [IoT-Core] ERROR - {org.wso2.carbon.email.sender.core.service.EmailSenderServiceImpl} Error occurred while delivering the message, subject: 'You have successfully been registered in WSO2 IoT', to: 'chris@mobx.com'
org.apache.axis2.AxisFault: The system cannot infer the transport information from the mailto:chris@mobx.com URL.
        at org.apache.axis2.description.ClientUtils.inferOutTransport(ClientUtils.java:81)
        at org.apache.axis2.client.OperationClient.prepareMessageContext(OperationClient.java:288)
        at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:249)
        at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
        at org.apache.axis2.client.ServiceClient.fireAndForget(ServiceClient.java:511)
        at org.apache.axis2.client.ServiceClient.fireAndForget(ServiceClient.java:488)
        at org.wso2.carbon.email.sender.core.service.EmailSenderServiceImpl$EmailSender.run(EmailSenderServiceImpl.java:117)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

`

[1] https://docs.wso2.com/display/IoTS310/Configuring+WSO2+IoT+Server+with+the+IP

**Comment by pubudup** [comment]
@chamaraanu , @geethkokila , @madhawap : Labels: 3.1.0-beta2, Medium
