### ISSUE TITLE
[Core / Exception] An exception could be seen after start up in IoT core

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1148]
The following exception could be seen in IoT core after the start up.

OS:  Windows 10
Pack: Beta 2

Pre-Conditions:-
- A device should be already enrolled
- Server should be stopped

Steps:-
1. Start the broker
2. Once the broker is started, start the analytics component
3. Once the analytics is started, start the core component
4. Sync the device
5. Observe the server logs

Expected Result:-
- There should be no exceptions triggered when synching the device

Actual Results:-
- The following exception could be seen in IoT core.

`
[2017-07-12 11:06:42,796] [IoT-Core] ERROR - {org.apache.synapse.transport.passthru.SourceHandler} I/O error: An established connection was aborted by the software in your host machine
java.io.IOException: An established connection was aborted by the software in your host machine
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.receiveEncryptedData(SSLIOSession.java:371)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:406)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:119)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
        at java.lang.Thread.run(Thread.java:748)

`

**Comment by pubudup** [comment]
@chamaraanu , @geethkokila , @madhawap : Lebels: Medium, 3.1.0-beta2

**Comment by pubudup** [comment]
Closing the ticket since this is not reproducible anymore. Will be reopened if experienced in future.

**Comment by pubudup** [comment]
Looks like this is due to the antivirus enabling the firewall.
