### ISSUE TITLE
HTTP 500 in the Device Mgt. page when the session expires. 

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-iots#1184]
Logged into the Device mgt. page. 
Let the session to be expired for the particular time. 
Try accessing the Device Mgt. page again. Instead of redirecting to the login page, this gives a http 500 page. 

![http500](https://user-images.githubusercontent.com/6646840/28263315-eb890740-6b03-11e7-8a82-d55b82e579a8.png)

```
[2017-07-17 09:34:20,865] [IoT-Core] ERROR - {org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl} Invalid OAuth Token : Access token expired
[2017-07-17 09:34:20,869] [IoT-Core]  WARN - {org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler} API authentication failure due to Invalid Credentials
[2017-07-17 09:50:35,156] [IoT-Core] ERROR - {org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl} Invalid OAuth Token : Access token expired
[2017-07-17 09:50:35,159] [IoT-Core]  WARN - {org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler} API authentication failure due to Invalid Credentials
[2017-07-17 09:50:35,190] [IoT-Core] ERROR - {/app/modules/oauth/token-protected-service-invokers.js} API application has been removed.
[2017-07-17 09:50:35,193] [IoT-Core] ERROR - {/app/modules/business-controllers/user.js} User object was not found in the session
[2017-07-17 09:50:35,193] [IoT-Core] ERROR - {/app/modules/business-controllers/user.js} User object was not found in the session
[2017-07-17 09:50:35,205] [IoT-Core] ERROR - {error-pages-handler} java.lang.IllegalStateException: getAttribute: Session already invalidated
org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalStateException: getAttribute: Session already invalidated (/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js#2236(Function)#2)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.devicemgt.lib.c1._c_anonymous_14(/devicemgt/lib/utils.js:611)
	at org.jaggeryjs.rhino.devicemgt.lib.c1.call(/devicemgt/lib/utils.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
	at org.jaggeryjs.rhino.devicemgt.lib.c4._c_route_3(/devicemgt/lib/error-pages-router.js:110)
	at org.jaggeryjs.rhino.devicemgt.lib.c4.call(/devicemgt/lib/error-pages-router.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.devicemgt.lib.c4._c_anonymous_2(/devicemgt/lib/error-pages-router.js:51)
	at org.jaggeryjs.rhino.devicemgt.lib.c4.call(/devicemgt/lib/error-pages-router.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c0._c_anonymous_24(/devicemgt/app/modules/business-controllers/user.js:501)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c0.call(/devicemgt/app/modules/business-controllers/user.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c0._c_anonymous_26(/devicemgt/app/modules/business-controllers/user.js:535)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c0.call(/devicemgt/app/modules/business-controllers/user.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c2._c_anonymous_2(/devicemgt/app/modules/business-controllers/group.js:36)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c2.call(/devicemgt/app/modules/business-controllers/group.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
	at org.jaggeryjs.rhino.devicemgt.app.pages.cdmf.page.dashboard.c1._c_onRequest_1(/devicemgt/app/pages/cdmf.page.dashboard/dashboard.js:44)
	at org.jaggeryjs.rhino.devicemgt.app.pages.cdmf.page.dashboard.c1.call(/devicemgt/app/pages/cdmf.page.dashboard/dashboard.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0._c_executeScript_8(/devicemgt/lib/modules/handlebars/handlebars.js:239)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0.call(/devicemgt/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0._c_pageHelper_10(/devicemgt/lib/modules/handlebars/handlebars.js:295)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0.call(/devicemgt/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1473)
	at script.anonymous(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js#2236(Function):2)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c2._c_anonymous_44(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js:558)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c2.call(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c2._c_anonymous_142(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js:2029)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c2.call(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0._c_anonymous_16(/devicemgt/lib/modules/handlebars/handlebars.js:706)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0.call(/devicemgt/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.c6._c_anonymous_4(/devicemgt/lib/dynamic-files-renderer.js:97)
	at org.jaggeryjs.rhino.devicemgt.lib.c6.call(/devicemgt/lib/dynamic-files-renderer.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.c6._c_anonymous_3(/devicemgt/lib/dynamic-files-renderer.js:80)
	at org.jaggeryjs.rhino.devicemgt.lib.c6.call(/devicemgt/lib/dynamic-files-renderer.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.c5._c_anonymous_5(/devicemgt/lib/pages-router.js:181)
	at org.jaggeryjs.rhino.devicemgt.lib.c5.call(/devicemgt/lib/pages-router.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.devicemgt.lib.c3._c_script_0(/devicemgt/lib/pages.jag:23)
	at org.jaggeryjs.rhino.devicemgt.lib.c3.call(/devicemgt/lib/pages.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.devicemgt.lib.c3.call(/devicemgt/lib/pages.jag)
	at org.jaggeryjs.rhino.devicemgt.lib.c3.exec(/devicemgt/lib/pages.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:45)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: getAttribute: Session already invalidated
	at org.apache.catalina.session.StandardSession.getAttribute(StandardSession.java:1176)
	at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:115)
	at org.jaggeryjs.hostobjects.web.SessionHostObject.jsFunction_get(SessionHostObject.java:140)
	at sun.reflect.GeneratedMethodAccessor184.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 117 more

```

**Comment by dilee** [comment]
Solved in https://github.com/wso2/carbon-device-mgt/pull/854
