### ISSUE TITLE
[IP Config] Mutual SSL scenario is giving an exception in IOT Core

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1187]
As discussed we have tested the mutual SSL scenario. Please find the steps below.

1. Configure the IP based changes from [1]
2. Remove the wso2carbon alias from wso2carbon.jks IOT core
3. Create a new Public key using wso2carbon alias and import to client trust store of IOT core
4. Repeat step 2 and 3 for analytics and broker components as well
5. Add the public keys of each components to other client trust stores and wso2carbon.jks (eg:- core public key should be added to analytics and broker keystore and truststore)
6. Update the certificate section of iot_default.xml in /wso2iot-3.1.0/conf/identity/identity-providers with base64 encoded value of core public key.
6. Start broker component
7. Start core component
8. Observe server logs

Expected Results:-
- No error messages should be triggered

Actual Results:-
- A null pointer exception is triggered from core component

`
[2017-07-17 14:31:29,374] [IoT-Core]  INFO - {org.wso2.carbon.identity.oauth.config.OAuthServerConfiguration} The default Identity OAuth token issuer will be used. No custom token generator is set.
[2017-07-17 14:31:29,749] [IoT-Core] ERROR - {org.wso2.carbon.identity.oauth2.grant.jwt.JWTBearerGrantHandler} Signature or Message Authentication invalid.
Exception in thread "Thread-34" java.lang.NullPointerException
        at org.wso2.carbon.apimgt.integration.client.OAuthRequestInterceptor.apply(OAuthRequestInterceptor.java:104)
        at feign.SynchronousMethodHandler.targetRequest(SynchronousMethodHandler.java:158)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:88)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
        at com.sun.proxy.$Proxy40.apisGet(Unknown Source)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherServiceImpl.publishAPI(APIPublisherServiceImpl.java:53)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler.publishAPIs(APIPublisherStartupHandler.java:97)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler.access$500(APIPublisherStartupHandler.java:30)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler$1.run(APIPublisherStartupHandler.java:69)
        at java.lang.Thread.run(Thread.java:748)
`

[1] https://docs.wso2.com/display/IoTS310/Configuring+WSO2+IoT+Server+with+the+IP

**Comment by pubudup** [comment]
@chamaraanu , @geethkokila , @madhawap : Labels: High, 3.1.0-RC

**Comment by pubudup** [comment]
The following error is seen on analytics component.

`
[2017-07-17 17:15:10,999] [IoT-Analytics]  INFO {org.wso2.carbon.event.processor.manager.core.internal.CarbonEventManagementService} -  Starting polling event receivers
[2017-07-17 17:16:25,770] [IoT-Analytics] ERROR {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  Failed to create an oauth token with jwt grant type.
org.wso2.carbon.identity.jwt.client.extension.exception.JWTClientException: Error when reading the response from buffer.
        at org.wso2.carbon.identity.jwt.client.extension.JWTClient.getTokenInfo(JWTClient.java:171)
        at org.wso2.carbon.identity.jwt.client.extension.JWTClient.getAccessToken(JWTClient.java:79)
        at org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener.getToken(MQTTAdapterListener.java:338)
        at org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener.startListener(MQTTAdapterListener.java:183)
        at org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener.run(MQTTAdapterListener.java:302)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.http.impl.conn.CPoolProxy.invoke(CPoolProxy.java:138)
        at com.sun.proxy.$Proxy45.receiveResponseHeader(Unknown Source)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:253)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at org.wso2.carbon.identity.jwt.client.extension.JWTClient.getTokenInfo(JWTClient.java:147)
        ... 5 more
[2017-07-17 17:16:42,734] [IoT-Analytics]  WARN {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  Broker is unreachable, Waiting.....


`

**Comment by madhawap** [comment]
depends on https://github.com/wso2/product-iots/issues/1193

**Comment by milanperera** [comment]
This is fixed in [1].

[1] https://github.com/wso2/product-iots/pull/1252
