### ISSUE TITLE
[Mobile QSG] An exception when running the sample

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1226]
1. Start the broker
2. Start the core
3. run mobile qsg sample by executing mobile-qsg.sh
4. Observe the core logs

Expected Results:-
- Sample shouldn't give any errors

Actual Results:-
- Sample gives the following error in core

`
[2017-07-25 17:22:20,174] [IoT-Core] ERROR - {org.apache.axis2.description.ClientUtils} The system cannot infer the transport information from the mailto:chris@mobx.com URL.
[2017-07-25 17:22:20,176] [IoT-Core] ERROR - {org.wso2.carbon.email.sender.core.service.EmailSenderServiceImpl} Error occurred while delivering the message, subject: 'You have successfully been registered in WSO2 IoT', to: 'chris@mobx.com'
org.apache.axis2.AxisFault: The system cannot infer the transport information from the mailto:chris@mobx.com URL.
	at org.apache.axis2.description.ClientUtils.inferOutTransport(ClientUtils.java:81)
	at org.apache.axis2.client.OperationClient.prepareMessageContext(OperationClient.java:288)
	at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:249)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.axis2.client.ServiceClient.fireAndForget(ServiceClient.java:511)
	at org.apache.axis2.client.ServiceClient.fireAndForget(ServiceClient.java:488)
	at org.wso2.carbon.email.sender.core.service.EmailSenderServiceImpl$EmailSender.run(EmailSenderServiceImpl.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-07-25 17:22:20,307] [IoT-Core] ERROR - {org.apache.axis2.description.ClientUtils} The system cannot infer the transport information from the mailto:alex@example.com URL.
[2017-07-25 17:22:20,308] [IoT-Core] ERROR - {org.wso2.carbon.email.sender.core.service.EmailSenderServiceImpl} Error occurred while delivering the message, subject: 'You have successfully been registered in WSO2 IoT', to: 'alex@example.com'
org.apache.axis2.AxisFault: The system cannot infer the transport information from the mailto:alex@example.com URL.
	at org.apache.axis2.description.ClientUtils.inferOutTransport(ClientUtils.java:81)
	at org.apache.axis2.client.OperationClient.prepareMessageContext(OperationClient.java:288)
	at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:249)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.axis2.client.ServiceClient.fireAndForget(ServiceClient.java:511)
	at org.apache.axis2.client.ServiceClient.fireAndForget(ServiceClient.java:488)
	at org.wso2.carbon.email.sender.core.service.EmailSenderServiceImpl$EmailSender.run(EmailSenderServiceImpl.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by pubudup** [comment]
@chamaraanu , @geethkokila , @madawas : Labels - 3.1.0-RC2, High

**Comment by pubudup** [comment]
@shavidissa : Please update the doc by adding a note by mentioning the email related config as discussed offline. Thanks.

**Comment by pubudup** [comment]
Note:- This error doesn't occur when all broker / core / analytics components are up. Only experienced when broker and core are started.

**Comment by pubudup** [comment]
Closing the ticket since this issue can be overcome by using the config specified here [1]

[1] https://docs.wso2.com/display/IoTS310/Configuring+the+Email+Settings

**Comment by pubudup** [comment]
Doc JIRA created [1]. 
[1] https://wso2.org/jira/browse/DOCUMENTATION-4617
