### ISSUE TITLE
[Oracle12C] Errors on startup when started with -Dsetup

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1250]
1. Configure the databases with Oracle 12c as described in [1]
2. Start up the server with -Dsetup

Expected Results:-
- Server should be successfully started

Actual Results:-
- Db error is triggered on startup

[1] https://docs.wso2.com/display/IoTS310/Changing+to+Oracle
```
Admins-MacBook-Pro:bin pubudup$ sh iot-server.sh -Dsetup
JAVA_HOME environment variable is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
CARBON_HOME environment variable is set to /Users/pubudup/Documents/WSO2/IoT/RC3/oracle/wso2iot-3.1.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
[2017-07-28 16:55:00,040] [IoT-Core]  INFO - {org.wso2.carbon.appmgt.impl.internal.AppDiscoveryComponent} WebApp Discovery component activated
[2017-07-28 16:55:00,412] [IoT-Core]  INFO - {org.wso2.carbon.appmgt.mobile.internal.AppManagerMobileComponent} WSO2MDM_INTERNAL MDM is bound to App Manager.
[2017-07-28 16:55:00,413] [IoT-Core]  INFO - {org.wso2.carbon.appmgt.mobile.internal.AppManagerMobileComponent} App Manger Mobile Component activated.
[2017-07-28 16:55:00,518] [IoT-Core]  INFO - {org.wso2.carbon.core.internal.CarbonCoreActivator} Starting WSO2 Carbon...
[2017-07-28 16:55:00,518] [IoT-Core]  INFO - {org.wso2.carbon.core.internal.CarbonCoreActivator} Operating System : Mac OS X 10.12.2, x86_64
[2017-07-28 16:55:00,518] [IoT-Core]  INFO - {org.wso2.carbon.core.internal.CarbonCoreActivator} Java Home        : /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
[2017-07-28 16:55:00,518] [IoT-Core]  INFO - {org.wso2.carbon.core.internal.CarbonCoreActivator} Java Version     : 1.8.0_121
[2017-07-28 16:55:00,519] [IoT-Core]  INFO - {org.wso2.carbon.core.internal.CarbonCoreActivator} Java VM          : Java HotSpot(TM) 64-Bit Server VM 25.121-b13,Oracle Corporation
[2017-07-28 16:55:00,519] [IoT-Core]  INFO - {org.wso2.carbon.core.internal.CarbonCoreActivator} Carbon Home      : /Users/pubudup/Documents/WSO2/IoT/RC3/oracle/wso2iot-3.1.0
[2017-07-28 16:55:00,519] [IoT-Core]  INFO - {org.wso2.carbon.core.internal.CarbonCoreActivator} Java Temp Dir    : /Users/pubudup/Documents/WSO2/IoT/RC3/oracle/wso2iot-3.1.0/wso2/tmp
[2017-07-28 16:55:00,519] [IoT-Core]  INFO - {org.wso2.carbon.core.internal.CarbonCoreActivator} User             : pubudup, en-US, Asia/Colombo
Activating org.wso2.jaggery.scxml with RealmService enabled
[2017-07-28 16:55:08,311] [IoT-Core]  INFO - {org.wso2.carbon.databridge.core.internal.DataBridgeDS} Successfully deployed Agent Server
[2017-07-28 16:55:09,661] [IoT-Core]  INFO - {org.wso2.carbon.registry.core.jdbc.EmbeddedRegistryService} Configured Registry in 1223ms
[2017-07-28 16:55:13,863] [IoT-Core]  INFO - {org.wso2.carbon.registry.core.internal.RegistryCoreServiceComponent} Registry Mode    : READ-WRITE
[2017-07-28 16:55:14,317] [IoT-Core]  INFO - {org.wso2.carbon.device.mgt.core.internal.DeviceManagementServiceComponent} Initializing device management repository database schema
[2017-07-28 16:55:15,761] [IoT-Core] ERROR - {org.wso2.carbon.device.mgt.core.internal.DeviceManagementServiceComponent} Error occurred while initializing device management core bundle
org.wso2.carbon.device.mgt.common.DeviceManagementException: Error occurred while initializing Device Management database schema
	at org.wso2.carbon.device.mgt.core.internal.DeviceManagementServiceComponent.setupDeviceManagementSchema(DeviceManagementServiceComponent.java:322)
	at org.wso2.carbon.device.mgt.core.internal.DeviceManagementServiceComponent.activate(DeviceManagementServiceComponent.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
	at org.wso2.carbon.ndatasource.core.internal.DataSourceServiceComponent.registerServices(DataSourceServiceComponent.java:126)
	at org.wso2.carbon.ndatasource.core.internal.DataSourceServiceComponent.initSuperTenantUserDataSources(DataSourceServiceComponent.java:221)
	at org.wso2.carbon.ndatasource.core.internal.DataSourceServiceComponent.checkInitTenantUserDataSources(DataSourceServiceComponent.java:206)
	at org.wso2.carbon.ndatasource.core.internal.DataSourceServiceComponent.setRegistryService(DataSourceServiceComponent.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:376)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:430)
	at org.eclipse.equinox.internal.ds.InstanceProcess.dynamicBind(InstanceProcess.java:416)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:334)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.wso2.carbon.registry.core.internal.RegistryCoreServiceComponent.activate(RegistryCoreServiceComponent.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.wso2.carbon.user.core.internal.Activator.startDeploy(Activator.java:69)
	at org.wso2.carbon.user.core.internal.BundleCheckActivator.start(BundleCheckActivator.java:61)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.Exception: Error occurred while executing :   CREATE INDEX IDX_ENID_OPID ON DM_DEVICE_OPERATION_RESPONSE(OPERATION_ID, ENROLMENT_ID); CREATE INDEX IDX_DM_EN_OP_MAP_RES ON DM_DEVICE_OPERATION_RESPONSE(EN_OP_MAP_ID);   CREATE  TABLE DM_PROFILE ( ID NUMBER(10) NOT NULL , PROFILE_NAME VARCHAR2(45) NOT NULL , TENANT_ID NUMBER(10) NOT NULL , DEVICE_TYPE VARCHAR2(300) NOT NULL , CREATED_TIME TIMESTAMP(0) NOT NULL , UPDATED_TIME TIMESTAMP(0) NOT NULL , CONSTRAINT PK_DM_PROFILE PRIMARY KEY (ID) )
	at org.wso2.carbon.utils.dbcreator.DatabaseCreator.executeSQL(DatabaseCreator.java:177)
	at org.wso2.carbon.utils.dbcreator.DatabaseCreator.executeSQLScript(DatabaseCreator.java:333)
	at org.wso2.carbon.utils.dbcreator.DatabaseCreator.createRegistryDatabase(DatabaseCreator.java:61)
	at org.wso2.carbon.device.mgt.core.internal.DeviceManagementServiceComponent.setupDeviceManagementSchema(DeviceManagementServiceComponent.java:317)
	... 82 more
Caused by: java.sql.SQLSyntaxErrorException: ORA-02158: invalid CREATE INDEX option

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:202)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:45)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:933)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1718)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1678)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:332)
	at org.wso2.carbon.utils.dbcreator.DatabaseCreator.executeSQL(DatabaseCreator.java:147)
	... 85 more
[2017-07-28 16:55:16,787] [IoT-Core]  INFO - {org.wso2.carbon.metrics.impl.internal.LocalDatabaseCreator} Using the SQL script file '/Users/pubudup/Documents/WSO2/IoT/RC3/oracle/wso2iot-3.1.0/dbscripts/metrics/oracle.sql' to create Metrics Database tables
[2017-07-28 16:55:17,363] [IoT-Core]  INFO - {org.wso2.carbon.metrics.impl.util.JDBCReporterBuilder} Creating JDBC reporter for Metrics with source 'localhost', data source 'jdbc/WSO2MetricsDB' and 60 seconds polling period
[2017-07-28 16:55:17,364] [IoT-Core]  INFO - {org.wso2.carbon.metrics.impl.util.JmxReporterBuilder} Creating JMX reporter for Metrics with domain 'org.wso2.carbon.metrics'
[2017-07-28 16:55:17,367] [IoT-Core]  INFO - {org.wso2.carbon.metrics.impl.reporter.AbstractReporter} Started JMX reporter for Metrics
[2017-07-28 16:55:17,372] [IoT-Core]  INFO - {org.wso2.carbon.metrics.impl.reporter.AbstractReporter} Started JDBC reporter for Metrics
[2017-07-28 16:55:19,035] [IoT-Core]  INFO - {org.wso2.carbon.registry.indexing.solr.SolrClient} Default Embedded Solr Server Initialized
[2017-07-28 16:55:19,687] [IoT-Core]  INFO - {org.apache.catalina.startup.TaglibUriRule} TLD skipped. URI: http://tiles.apache.org/tags-tiles is already defined
[2017-07-28 16:55:23,792] [IoT-Core]  INFO - {org.wso2.carbon.social.sql.SocialDBInitilizer} Social database already exists. Not creating a new database.
[2017-07-28 16:55:24,066] [IoT-Core]  INFO - {org.wso2.carbon.user.core.internal.UserStoreMgtDSComponent} Carbon UserStoreMgtDSComponent activated successfully.
[2017-07-28 16:55:25,752] [IoT-Core]  INFO - {org.wso2.carbon.identity.user.store.configuration.deployer.UserStoreConfigurationDeployer} User Store Configuration Deployer initiated.
[2017-07-28 16:55:25,752] [IoT-Core]  INFO - {org.wso2.carbon.identity.user.store.configuration.deployer.UserStoreConfigurationDeployer} User Store Configuration Deployer initiated.
^C[2017-07-28 16:55:27,412] [IoT-Core]  INFO - {org.wso2.carbon.core.init.CarbonServerManager} Shutdown hook triggered....
[2017-07-28 16:55:27,412] [IoT-Core]  INFO - {org.wso2.carbon.core.init.CarbonServerManager} Gracefully shutting down WSO2 IoT Server...
[2017-07-28 16:55:27,414] [IoT-Core]  INFO - {org.wso2.carbon.core.ServerManagement} Starting to switch to maintenance mode...
[2017-07-28 16:55:27,414] [IoT-Core]  INFO - {org.wso2.carbon.core.ServerManagement} Stopped all transport listeners
[2017-07-28 16:55:27,414] [IoT-Core]  INFO - {org.wso2.carbon.core.ServerManagement} Waiting for request service completion...
[2017-07-28 16:55:27,417] [IoT-Core]  INFO - {org.wso2.carbon.core.ServerManagement} All requests have been served.
[2017-07-28 16:55:27,417] [IoT-Core]  INFO - {org.wso2.carbon.core.ServerManagement} Waiting for deployment completion...
[2017-07-28 16:55:27,419] [IoT-Core]  INFO - {org.wso2.carbon.core.ServerManagement} All deployment tasks have been completed.
[2017-07-28 16:55:27,419] [IoT-Core]  INFO - {org.wso2.carbon.core.ServerManagement} Waiting for server task completion...
[2017-07-28 16:55:27,419] [IoT-Core]  INFO - {org.wso2.carbon.registry.core.internal.RegistryCoreServiceComponent} Writing logs
[2017-07-28 16:55:27,454] [IoT-Core]  INFO - {org.wso2.carbon.core.ServerManagement} All server tasks have been completed.
[2017-07-28 16:55:27,454] [IoT-Core]  INFO - {org.wso2.carbon.core.init.CarbonServerManager} Shutting down WSO2 IoT Server...
[2017-07-28 16:55:27,548] [IoT-Core]  INFO - {org.wso2.carbon.core.init.CarbonServerManager} Shutting down OSGi framework...
[2017-07-28 16:55:27,548] [IoT-Core]  INFO - {org.wso2.carbon.core.init.CarbonServerManager} Shutdown complete
[2017-07-28 16:55:27,549] [IoT-Core]  INFO - {org.wso2.carbon.core.init.CarbonServerManager} Halting JVM
```

**Comment by pubudup** [comment]
@chamaraanu , @geethkokila , @madhawap : Labels: High , 3.1.0-RC3

**Comment by pubudup** [comment]
This could be related to #487

**Comment by pubudup** [comment]
Executed {HOME}/dbscripts/cdm/oracle.sql script on a oracle 12c db and I didn't see any errors. This could be specifically related to startup with -Dsetup

**Comment by pubudup** [comment]
Verified the fix in Pre-RC4 pack. Fixed
