### ISSUE TITLE
[Geo Fencing] Geo Fencing alerts are not working with Android 

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1266]
1. Enable geo fencing as explained in [1]
2. Login to device management and add a geo fence and an alert
3. Mock the device location to be outside the geo fence
4. Observe the geo fencing alert once the location is updated

Expected Results:-
- Geo fencing alert should be sent to the device management UI

Actual Results:-
- Geo fencing alert is not appearing in device management UI
 - Errors displayed in Core
```
[2017-08-03 11:07:58,162] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftEventConverter} Undefined attribute type : 1501738677637
[2017-08-03 11:07:58,163] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftEventConverter} Undefined attribute type : 79.85980224609375
[2017-08-03 11:07:58,164] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftEventConverter} Undefined attribute type : 6.910711288452148
[2017-08-03 11:08:14,729] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftEventConverter} Undefined attribute type : 1501738694670
[2017-08-03 11:08:14,731] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftEventConverter} Undefined attribute type : 79.85980224609375
[2017-08-03 11:08:14,731] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftEventConverter} Undefined attribute type : 6.910711288452148
[2017-08-03 11:08:58,902] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftEventConverter} Undefined attribute type : 1501738738867
[2017-08-03 11:08:58,903] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftEventConverter} Undefined attribute type : 79.85980224609375
[2017-08-03 11:08:58,903] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftEventConverter} Undefined attribute type : 6.910711288452148
[2017-08-03 11:09:02,261] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftEventConverter} Undefined attribute type : 1501738742140
[2017-08-03 11:09:02,262] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftEventConverter} Undefined attribute type : 79.85980224609375
[2017-08-03 11:09:02,262] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftEventConverter} Undefined attribute type : 6.910711288452148
[2017-08-03 11:10:57,129] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftEventConverter} Undefined attribute type : 1501738857048
[2017-08-03 11:10:57,130] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftEventConverter} Undefined attribute type : 79.85980224609375
[2017-08-03 11:10:57,130] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftEventConverter} Undefined attribute type : 6.910711288452148
```

- Errors displayed in analytics

```
[2017-08-03 11:07:58,187] [IoT-Analytics] ERROR {org.wso2.carbon.databridge.core.internal.queue.QueueWorker} -  Dropping wrongly formatted event sent for -1234
org.wso2.carbon.databridge.core.exception.EventConversionException: Error when converting org.wso2.iot.LocationStream:1.0.0 of event bundle with events 1
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.createEventList(ThriftEventConverter.java:181)
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.toEventList(ThriftEventConverter.java:90)
	at org.wso2.carbon.databridge.core.internal.queue.QueueWorker.run(QueueWorker.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.toObjectArray(ThriftEventConverter.java:59)
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.createEventList(ThriftEventConverter.java:169)
	... 7 more
[2017-08-03 11:08:14,732] [IoT-Analytics] ERROR {org.wso2.carbon.databridge.core.internal.queue.QueueWorker} -  Dropping wrongly formatted event sent for -1234
org.wso2.carbon.databridge.core.exception.EventConversionException: Error when converting org.wso2.iot.LocationStream:1.0.0 of event bundle with events 1
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.createEventList(ThriftEventConverter.java:181)
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.toEventList(ThriftEventConverter.java:90)
	at org.wso2.carbon.databridge.core.internal.queue.QueueWorker.run(QueueWorker.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.toObjectArray(ThriftEventConverter.java:59)
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.createEventList(ThriftEventConverter.java:169)
	... 7 more
[2017-08-03 11:08:58,904] [IoT-Analytics] ERROR {org.wso2.carbon.databridge.core.internal.queue.QueueWorker} -  Dropping wrongly formatted event sent for -1234
org.wso2.carbon.databridge.core.exception.EventConversionException: Error when converting org.wso2.iot.LocationStream:1.0.0 of event bundle with events 1
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.createEventList(ThriftEventConverter.java:181)
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.toEventList(ThriftEventConverter.java:90)
	at org.wso2.carbon.databridge.core.internal.queue.QueueWorker.run(QueueWorker.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.toObjectArray(ThriftEventConverter.java:59)
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.createEventList(ThriftEventConverter.java:169)
	... 7 more
[2017-08-03 11:09:02,263] [IoT-Analytics] ERROR {org.wso2.carbon.databridge.core.internal.queue.QueueWorker} -  Dropping wrongly formatted event sent for -1234
org.wso2.carbon.databridge.core.exception.EventConversionException: Error when converting org.wso2.iot.LocationStream:1.0.0 of event bundle with events 1
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.createEventList(ThriftEventConverter.java:181)
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.toEventList(ThriftEventConverter.java:90)
	at org.wso2.carbon.databridge.core.internal.queue.QueueWorker.run(QueueWorker.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.toObjectArray(ThriftEventConverter.java:59)
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.createEventList(ThriftEventConverter.java:169)
	... 7 more
[2017-08-03 11:09:03,034] [IoT-Analytics]  INFO {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} -  'admin@carbon.super [-1234]' logged in at [2017-08-03 11:09:03,034+0530]
[2017-08-03 11:10:57,132] [IoT-Analytics] ERROR {org.wso2.carbon.databridge.core.internal.queue.QueueWorker} -  Dropping wrongly formatted event sent for -1234
org.wso2.carbon.databridge.core.exception.EventConversionException: Error when converting org.wso2.iot.LocationStream:1.0.0 of event bundle with events 1
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.createEventList(ThriftEventConverter.java:181)
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.toEventList(ThriftEventConverter.java:90)
	at org.wso2.carbon.databridge.core.internal.queue.QueueWorker.run(QueueWorker.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.toObjectArray(ThriftEventConverter.java:59)
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.createEventList(ThriftEventConverter.java:169)
	... 7 more

```
[1] https://docs.wso2.com/display/IoTS310/Monitoring+Devices+Using+Location+Based+Services

**Comment by pubudup** [comment]
@rasika : Labels: Blocker, 3.1.0-RC3 (pre RC4 pack)
Please review the ticket and feel free to drop the priority if this is a config issue or a document gap.

**Comment by pubudup** [comment]
Please make sure to address both Enter and Exit alerts

**Comment by rasika** [comment]
This is an intermittent issue that we have encountered. But in Pubudu's PC it is constantly reproduced. Geo Fencing won't work if the events are dropped without persisting. In this case; location event is not captured into DAS.

**Comment by pubudup** [comment]
@rasika : I was able to reproduce the issue on another pack with same steps. It doesn't seems to consistent in Pre-RC4 pack. 

Cheers.

**Comment by madhawap** [comment]
This is fixed with https://github.com/wso2/carbon-device-mgt-plugins/pull/785. Hence closed.

**Comment by pubudup** [comment]
Also checked with the internally shared pack on the 09Aug2017 with an android 5.1 mobile device. Did not work for both IP configured and localhost packs when tested on the internal network.

**Comment by pubudup** [comment]
Verified the fix in RC4 pack. Fixed.
