### ISSUE TITLE
Error after admin login on Device Management Console 3.1.0

### ISSUE THREAD

**Issue by nemanjanedic** [wso2/product-iots#1324]
I've installed WSO2 IOTS 3.1.0 on a Linux machine. I've run the script to change IP address (`scripts/change-ip.sh`) and after starting the server, I've logged into the Device Management console and I got this HTTP 500 error message after entering correct credentials:
```
org.wso2.carbon.apimgt.integration.client.exception.APIMClientOAuthException: failed to retrieve oauth token using jwt
```
The log file contains this error:
```
[2017-08-21 09:11:17,520] [IoT-Core] ERROR - {auth-module} An exception thrown when executing the script '/app/modules/login.js'.
[2017-08-21 09:11:17,527] [IoT-Core] ERROR - {auth-module} org.wso2.carbon.apimgt.integration.client.exception.APIMClientOAuthException: failed to retrieve oauth token using jwt
org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.apimgt.integration.client.exception.APIMClientOAuthException: failed to retrieve oauth token using jwt (/devicemgt/app/modules/login.js#31)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
	at org.jaggeryjs.rhino.devicemgt.app.modules.c3._c_anonymous_2(/devicemgt/app/modules/login.js:31)
	at org.jaggeryjs.rhino.devicemgt.app.modules.c3.call(/devicemgt/app/modules/login.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.auth.c0._c_executeScript_10(/devicemgt/lib/modules/auth/auth.js:234)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.auth.c0.call(/devicemgt/lib/modules/auth/auth.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.auth.c0._c_handleEvent_11(/devicemgt/lib/modules/auth/auth.js:259)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.auth.c0.call(/devicemgt/lib/modules/auth/auth.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.auth.c0._c_anonymous_20(/devicemgt/lib/modules/auth/auth.js:547)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.auth.c0.call(/devicemgt/lib/modules/auth/auth.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.auth.c2._c_anonymous_1(/devicemgt/lib/modules/auth/acs.jag:34)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.auth.c2.call(/devicemgt/lib/modules/auth/acs.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.auth.c2._c_script_0(/devicemgt/lib/modules/auth/acs.jag:22)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.auth.c2.call(/devicemgt/lib/modules/auth/acs.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.auth.c2.call(/devicemgt/lib/modules/auth/acs.jag)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.auth.c2.exec(/devicemgt/lib/modules/auth/acs.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:45)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.apimgt.integration.client.exception.APIMClientOAuthException: failed to retrieve oauth token using jwt
	at org.wso2.carbon.apimgt.integration.client.OAuthRequestInterceptor.apply(OAuthRequestInterceptor.java:118)
	at feign.SynchronousMethodHandler.targetRequest(SynchronousMethodHandler.java:158)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:88)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy38.tiersTierLevelTierNameGet(Unknown Source)
	at org.wso2.carbon.apimgt.application.extension.APIManagementProviderServiceImpl.isTierLoaded(APIManagementProviderServiceImpl.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 75 more
Caused by: org.wso2.carbon.identity.jwt.client.extension.exception.JWTClientException: Error when parsing the response <am:fault xmlns:am="http://wso2.org/apimanager"><am:code>101500</am:code><am:type>Status report</am:type><am:message>Runtime Error</am:message><am:description>Error in Sender</am:description></am:fault>
	at org.wso2.carbon.identity.jwt.client.extension.JWTClient.getTokenInfo(JWTClient.java:169)
	at org.wso2.carbon.identity.jwt.client.extension.JWTClient.getAccessToken(JWTClient.java:79)
	at org.wso2.carbon.apimgt.integration.client.OAuthRequestInterceptor.apply(OAuthRequestInterceptor.java:99)
	... 86 more
Caused by: Unexpected character (<) at position 0.
	at org.json.simple.parser.Yylex.yylex(Unknown Source)
	at org.json.simple.parser.JSONParser.nextToken(Unknown Source)
	at org.json.simple.parser.JSONParser.parse(Unknown Source)
	at org.json.simple.parser.JSONParser.parse(Unknown Source)
	at org.json.simple.parser.JSONParser.parse(Unknown Source)
	at org.wso2.carbon.identity.jwt.client.extension.JWTClient.getTokenInfo(JWTClient.java:153)
	... 88 more
```
Is there anything that can be done to fix this issue?

**Comment by harshanL** [comment]
Hi Nemanjanedic,

Thank you very much for your interest in WSO2 IoT Server and reporting this issue. I've tried to reproduce this. But unable to do so and I was able to login to devicemgt console without any issue. Have you done any additional configuration changes (such as changing admin credentials) other than changing the ip?

Regards,
Harshan

**Comment by nemanjanedic** [comment]
Hi,

I haven't done any other changes. I haven't even started the server before changing the IP. Is there a chance that some of the parameters in that script require special values, or something?

Regards,
Nemanja

**Comment by harshanL** [comment]
Hi,

Nope. But make sure to enter the ip without the port and give the same ip to as the **common-name** when generating the certificate at the end. I'm closing this issue as it's not reproducible. Thank you again for your interest in WSO2 IoT server.

Regards,
Harshan

**Comment by nemanjanedic** [comment]
Could you please post here an example or the test case that you tested and that was working.

Thanks,
Nemanja

**Comment by harshanL** [comment]
Please refer to the screenshot below where I was able to login to the server after changing the ip address using the **change-ip.sh** script.

<img width="1911" alt="screen shot 2017-08-28 at 3 50 32 pm" src="https://user-images.githubusercontent.com/6368301/29769654-e9adfcac-8c08-11e7-9fa4-10877ac8ce4a.png">

Regards,
Harshan

**Comment by nemanjanedic** [comment]
Thanks. Could you also put here the exact values used when running **change-ip.sh** script?

**Comment by harshanL** [comment]
Given below is the output after running the script.

Harshans-MacBook-Pro:scripts harshan$ ./change-ip.sh 

----------------------------------------
WSO2 IoT Server IP configuration tool
----------------------------------------

>>> Step 1: Change current IP address of the IoT server

Please enter the IoT Core IP that you need to replace (if you are trying out IoT server for the first time this will be localhost)
localhost

Please enter your current IP
10.100.5.16
--------------------------------------
All your  + localhost +  IP's are replaced with  +10.100.5.16
--------------------------------------
Changing <IoT_HOME>/conf/carbon.xml
Completed!!
Changing <IoT_HOME>/conf/app-manager.xml
Completed!!
Changing <IoT_HOME>/conf/identity/sso-idp-config.xml
Completed!!
Changing <IoT_HOME>/conf/iot-api-config.xml
Completed!!
Changing <IoT_HOME>/repository/deployment/server/jaggeryapps/devicemgt/app/conf/app-conf.json
Completed!!
Changing <IoT_HOME>/repository/deployment/server/jaggeryapps/api-store/site/conf/site.json
Completed!!
Changing <IoT_HOME>/repository/deployment/server/jaggeryapps/portal/configs/designer.json
Completed!!
Changing  <IoT_HOME>/conf/api-manager.xml
found
Completed!!
Changing <IoT_HOME>/conf/etc/webapp-publisher-config.xml
Completed!!
Changing  <IoT_HOME>/bin/iot-server.sh
Completed!!

Changing hostURL of <IoT_HOME>/wso2/broker/conf/broker.xml
found
Completed!!

Changing tokenEndpoint of <IoT_HOME>/wso2/broker/conf/broker.xml
found
Completed!!

Changing deviceMgtServerUrl of <IoT_HOME>/wso2/broker/conf/broker.xml
found
Completed!!
Changing  <IoT_HOME>/wso2/analytics/bin/wso2server.sh
Completed!!
Changing  <IoT_HOME>/wso2/analytics/repository/deployment/server/jaggeryapps/portal/configs/designer.json
Completed!!


>>> Step 2: Change current IP address of the IoT Broker
-------------------------------------------------------
Changing  <IoT_HOME>/wso2/analytics/bin/wso2server.sh
Completed!!
Changing  <IoT_HOME>/bin/iot-server.sh
Completed!!
Changing <IoT_HOME>/wso2/broker/conf/carbon.xml
Completed!!


>>> Step 3: Change current IP address of the IoT Analytics
-------------------------------------------------------
Changing  <IoT_HOME>/bin/iot-server.sh
Completed!!
Changing  <IoT_HOME>/wso2/analytics/repository/deployment/server/jaggeryapps/portal/configs/designer.json
Completed!!
Changing <IoT_HOME>/wso2/analytics/conf/carbon.xml
Completed!!

-----------------------------------------------
Generating SSL certificates for the IoT Server
-----------------------------------------------

=======Enter Values for IoT Core SSL Certificate=======
Please provide Country. Press Enter to skip.
LK
Please provide State. Press Enter to skip.
Western
Please provide Location. Press Enter to skip.
Colombo
Please provide Organization. Press Enter to skip.
WSO2
Please provide Organizational Unit. Press Enter to skip.
Eng
Please provide Email Address. Press Enter to skip.
harshan@wso2.com
Please provide Common Name 
10.100.5.16

Provided IoT Core SSL Subject :  /C=LK/ST=Western/L=Colombo/O=WSO2/OU=Eng/emailAddress=harshan@wso2.com/CN=10.100.5.16
If you have a different IoT Core Keystore password please enter it here. Press Enter to use the default password.

Generating SSL Certificate for IoT Core
Generating RSA private key, 4096 bit long modulus
.......++
..........................................................................................................................................................................................................................................................................++
e is 65537 (0x10001)
Signature ok
subject=/CN=10.100.5.16
Getting Private key
Export to PKCS12
Export PKCS12 to JKS
Warning: Overwriting existing alias wso2carbon in destination keystore
Entry for alias wso2carbon successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
Warning: Overwriting existing alias wso2carbon in destination keystore
Entry for alias wso2carbon successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
Warning: Overwriting existing alias wso2carbon in destination keystore
Entry for alias wso2carbon successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
Warning: Overwriting existing alias wso2carbon in destination keystore
Entry for alias wso2carbon successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
Warning: Overwriting existing alias wso2carbon in destination keystore
Entry for alias wso2carbon successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
Warning: Overwriting existing alias wso2carbon in destination keystore
Entry for alias wso2carbon successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled

Setting up the public certificate for the default idp
./change-ip.sh: line 309: hash: tac: not found

Printing certificate
-----------------------
MIIEozCCAosCBAKkWBQwDQYJKoZIhvcNAQEFBQAwFjEUMBIGA1UEAxMLMTAuMTAwLjUuMTYwHhcNMTcwODI4MDk1MjQ3WhcNMTkwODI4MDk1MjQ3WjAWMRQwEgYDVQQDEwsxMC4xMDAuNS4xNjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAN+TgwO6VbO8nT3Jjqxpo61YDqATWsb0y+RTDAaMnbNNfOoDawC5AcgdqEYTJHGIXDr6+5LItCczSbEuQqRtlxChhfQ0hQTr0u69Hf2wObNNi3+Z1X275zh/SOGM2r7RED5PC0ooflD38WR9WsZByLeg407coKGT4bF7SJ9DKVP20QawH9YnpYOAQ2NtDg9JIKR9Ab4w2+sNdg2BsUaTAgMBAAEwDQYJKoZIhvcNAQEFBQADggIBANcn/cdeuVXXIuWb3/ZT4u+MVQGvSJHB/WRO6xQFOYylNYH81Flt4YnYEQ5fCZigubap05Qco2y2i5Fn46nhu8cUe40WI1VGU7RZTntBaPpbwECuS5b3fz9IqmSkrwmCCRxYpfSy/qRf9t6e3vuGwC//VHO2l23o7f7RfkYxOKiR0/kBxmuYky3Zex5Pa+fMpyZ+kFzAYelOn0beDw0deG2c2/GApU+BqzxMDn7hfBoshOqNvxmWuzFmQadouNpdF3iRaTesK0Rsj4aMUojXtd9xCYDxABKJ9erYmp9MD1h87C2QebSkz9nmxxyAZmeHYKVGVb3y0SAwG6idgnkZdH5HrreNj6dvd55XqIOWBg0hWtBcEeh60uBNWvei/a39r/ectxSHf0W4UQWOMozgw9+/+6jR3D/4uJ8Ch1Q/3jwDZXgnd+xdeYXEeucJ80jNL/Xux9qdBSqt3+lyUKnidf6qNRSxR8Jr1hoZPgMUxiNggPhHaLf3Q/JPT7Hn1i4AG2FNT6i7A/aWYVF/BxpJxsXW2Tj9NTHgSLZ66khJOz1Hcoq7bQt73GfLVSyA9Ke9h4ASLhDeBDFHk4/N74Nz7Qlacai0zc3aRXPqK+iVOUCkGeyKeVPi2JNKTSGViECACaG4JSbgjSSA3eFeG7XBuTWykE0wT7+FcUfxHubL1B08


Configuration Completed!!!

**Comment by nemanjanedic** [comment]
This done on MacOS? I had issues with Ubuntu Linux. Did you have chance to test on a Linux distribution?

**Comment by nemanjanedic** [comment]
I've retested this on the Ubuntu and it's still not working. Here is the info on the Linux distribution:
```
$  cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by GDLMadushanka** [comment]
Hi 
I was able to login successfully after changing IP in the following Linux machine

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
NAME="Ubuntu"
VERSION="17.04 (Zesty Zapus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.04"
VERSION_ID="17.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=zesty
UBUNTU_CODENAME=zesty

Find the output of the script below.

----------------------------------------
WSO2 IoT Server IP configuration tool
----------------------------------------

>>> Step 1: Change current IP address of the IoT server

Please enter the IoT Core IP that you need to replace (if you are trying out IoT server for the first time this will be localhost)
localhost
change-ip.sh: 18: change-ip.sh: [[: not found

Please enter your current IP
192.168.8.108
change-ip.sh: 27: change-ip.sh: [[: not found
--------------------------------------
All your  + localhost +  IP's are replaced with  +192.168.8.108
--------------------------------------
Changing <IoT_HOME>/conf/carbon.xml
sed: can't read : No such file or directory
sed: can't read : No such file or directory
Completed!!
Changing <IoT_HOME>/conf/app-manager.xml
sed: can't read : No such file or directory
Completed!!
Changing <IoT_HOME>/conf/identity/sso-idp-config.xml
sed: can't read : No such file or directory
Completed!!
Changing <IoT_HOME>/conf/iot-api-config.xml
sed: can't read : No such file or directory
Completed!!
Changing <IoT_HOME>/repository/deployment/server/jaggeryapps/devicemgt/app/conf/app-conf.json
Completed!!
Changing <IoT_HOME>/repository/deployment/server/jaggeryapps/api-store/site/conf/site.json
Completed!!
Changing <IoT_HOME>/repository/deployment/server/jaggeryapps/portal/configs/designer.json
Completed!!
Changing  <IoT_HOME>/conf/api-manager.xml
found
sed: can't read : No such file or directory
Completed!!
Changing <IoT_HOME>/conf/etc/webapp-publisher-config.xml
sed: can't read : No such file or directory
Completed!!
Changing  <IoT_HOME>/bin/iot-server.sh
Completed!!

Changing hostURL of <IoT_HOME>/wso2/broker/conf/broker.xml
found
Completed!!

Changing tokenEndpoint of <IoT_HOME>/wso2/broker/conf/broker.xml
found
Completed!!

Changing deviceMgtServerUrl of <IoT_HOME>/wso2/broker/conf/broker.xml
found
Completed!!
Changing  <IoT_HOME>/wso2/analytics/bin/wso2server.sh
Completed!!
Changing  <IoT_HOME>/wso2/analytics/repository/deployment/server/jaggeryapps/portal/configs/designer.json
Completed!!


>>> Step 2: Change current IP address of the IoT Broker
-------------------------------------------------------
Changing  <IoT_HOME>/wso2/analytics/bin/wso2server.sh
Completed!!
Changing  <IoT_HOME>/bin/iot-server.sh
Completed!!
Changing <IoT_HOME>/wso2/broker/conf/carbon.xml
sed: can't read : No such file or directory
sed: can't read : No such file or directory
Completed!!


>>> Step 3: Change current IP address of the IoT Analytics
-------------------------------------------------------
Changing  <IoT_HOME>/bin/iot-server.sh
Completed!!
Changing  <IoT_HOME>/wso2/analytics/repository/deployment/server/jaggeryapps/portal/configs/designer.json
Completed!!
Changing <IoT_HOME>/wso2/analytics/conf/carbon.xml
sed: can't read : No such file or directory
sed: can't read : No such file or directory
Completed!!

-----------------------------------------------
Generating SSL certificates for the IoT Server
-----------------------------------------------


=======Enter Values for IoT Core SSL Certificate=======
Please provide Country. Press Enter to skip.
SL
Please provide State. Press Enter to skip.
Western
Please provide Location. Press Enter to skip.
Colombo
Please provide Organization. Press Enter to skip.
WSO2
Please provide Organizational Unit. Press Enter to skip.
Eng
Please provide Email Address. Press Enter to skip.
lahirumadu@wso2.com
Please provide Common Name 
192.168.8.108
change-ip.sh: 231: change-ip.sh: [[: not found

Provided IoT Core SSL Subject :  /C=SL/ST=Western/L=Colombo/O=WSO2/OU=Eng/emailAddress=lahirumadu@wso2.com/CN=192.168.8.108
If you have a different IoT Core Keystore password please enter it here. Press Enter to use the default password.
change-ip.sh: 281: read: Illegal option -s

Generating SSL Certificate for IoT Core
Generating RSA private key, 4096 bit long modulus
...............................................................................................................................................................................++
.....................................++
e is 65537 (0x10001)
Signature ok
subject=/C=SL/ST=Western/L=Colombo/O=WSO2/OU=Eng/emailAddress=lahirumadu@wso2.com/CN=192.168.8.108
Getting Private key
Export to PKCS12
Export PKCS12 to JKS
Warning: Overwriting existing alias wso2carbon in destination keystore
Entry for alias wso2carbon successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
Warning: Overwriting existing alias wso2carbon in destination keystore
Entry for alias wso2carbon successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
Warning: Overwriting existing alias wso2carbon in destination keystore
Entry for alias wso2carbon successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
Warning: Overwriting existing alias wso2carbon in destination keystore
Entry for alias wso2carbon successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
Warning: Overwriting existing alias wso2carbon in destination keystore
Entry for alias wso2carbon successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
Warning: Overwriting existing alias wso2carbon in destination keystore
Entry for alias wso2carbon successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled

Setting up the public certificate for the default idp

Printing certificate
-----------------------
MIIFjTCCA3UCBAKkWBQwDQYJKoZIhvcNAQELBQAwgYoxCzAJBgNVBAYTAlNMMRAwDgYDVQQIDAdXZXN0ZXJuMRAwDgYDVQQHDAdDb2xvbWJvMQ0wCwYDVQQKDARXU08yMQwwCgYDVQQLDANFbmcxIjAgBgkqhkiG9w0BCQEWE2xhaGlydW1hZHVAd3NvMi5jb20xFjAUBgNVBAMMDTE5Mi4xNjguOC4xMDgwHhcNMTcwODMwMDQyNzQwWhcNMTkwODMwMDQyNzQwWjCBijELMAkGA1UEBhMCU0wxEDAOBgNVBAgMB1dlc3Rlcm4xEDAOBgNVBAcMB0NvbG9tYm8xDTALBgNVBAoMBFdTTzIxDDAKBgNVBAsMA0VuZzEiMCAGCSqGSIb3DQEJARYTbGFoaXJ1bWFkdUB3c28yLmNvbTEWMBQGA1UEAwwNMTkyLjE2OC44LjEwODCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKsiDQhIMyEO8BGbAW8a8XkgclKUWvmeE+pVElVMhqzaKDG4I2y0gYarcu7ApA1U/aD2Ecgk7Oww4JuJeCHlQcwmLCpVtffDj49uHz6c6/7UCjounS/a7OcfaZvavh0xWvlREGNDPEEN32BczNnPavvUPTCQNKluRvnb751hCHVu/hJ3DQJ3B60N2rz+UcAD35HnFXXLF9RDIZlDhELrt12J7kygW4MOGWdbIhUHRxrHQJtBXwr9h80zqEb0i4RjWTQtlhK9NoGcuqs+kUuJdL5SdykESmoI8NMR9dyfUgl8T4tRkQzXEaVQ5y96fPVoTLAGvNoD8IkTKlp5rJUVZMM0V+SPOa9Q4bvXHoCwzaSJKcF0sX3v8WFOlVE4OoG6iEf/6ZaIE3Rlyfc2r1nP3WCWYerMVEoawUZo1I6BByIQ8Q4MHeOt0oufYMbg5qQpvbujf5ov8Sg88tkeTAagvfjW4hYjufm/qQWayU2rlkSyz+pkRrpj6ilWa90nq6AhRmHvQZKr+p2A0bC1yB/CTNbNOkdQFhCmYVtgS3M/G0obYXAcXiEAIRPVYw4GUf0GrXlXopuLQeSjW1Qd6pzHerbNnxfQvgXu66gsH2kI099Ma8RRAZWqHwSc0B71yX3eteNmK+WtqUAWvonQPo9CFYUXMyhbgYaV+DqLxWs2riLxAgMBAAEwDQYJKoZIhvcNAQELBQADggIBAByHqrZWMs1higJfzp6qWILlGldlCqfbQhyGvgBxhD2ULU9ou0eX7TTlge00+rETCYmbkk2RO6dIWC9nnqg8/pS6UNchDCcjJWmOrlANcsLrLNUH3TvqNHYkXKm7CvOZoG2M/KESYfIATGr0N1MHfaXGXXGAo9vtbHH9ObCe8/ouMShGDVNLS3g1T+wTSyC8gowpANZA+Is0In5gf2OUmkrdqVYidaaMmSMn7dvLxtuNA76nRtwbvIIzPKRiXouV2HykcXe5r1dkBAlw6xx5KWMwgC8im8Ll4z4Mpn8vTL8zID2bKPDp2j1CdwXQHDPVntLVDeHHlnR+O6pD0yHQ9wsfcbCneaSDjfsXOj/ndNb3hKa2NJINMwZ4zhiW2jIz7M0WVIudnF53JiPHwwKGGgV4Wjl9J+Wvs6jf3jjrHBz9MKF7uB+hLZq4dzU95Q2SIXa4LusJCms4UYly41Ig8bZ4WnsnzVnQ82CTG5e46ngHxzTKtp+wvFnN5dPYC+5xpliKbX80YWZGKLS1uxHWbp5a4q0YmdWyHAZ8DQH5Sesdik72kD1Te8+Rp5odO23LML+0PniA7C8yU2ZZPfGzwSbD+JJDrmCO0F7oqcusVsKp8pm2GmRCw7zMbkEWmSEf9mUPew5vcwxjaWo8MUMJBoPJW4OKfh5rv0e7cKjuxtYo
sed: can't read : No such file or directory


Configuration Completed!!!

![screenshot from 2017-08-30 10-11-48](https://user-images.githubusercontent.com/8251118/29855735-b85e9d64-8d6b-11e7-950c-ed54681e925b.png)
