### ISSUE TITLE
After executing the change-ip.sh cannot login to api-store

### ISSUE THREAD

**Issue by Megala21** [wso2/product-iots#1355]
Following exception is thrown,
```
[2017-08-30 10:45:27,546] [IoT-Core] ERROR - {org.jaggeryjs.jaggery.core.manager.WebAppManager} org.mozilla.javascript.WrappedException: Wrapped javax.script.ScriptException: Invalid arguments when setting sso configuration values. (/api-store/site/themes/wso2/templates/sso/filter/template.jag#61)
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped javax.script.ScriptException: Invalid arguments when setting sso configuration values. (/api-store/site/themes/wso2/templates/sso/filter/template.jag#61)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:45)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.mozilla.javascript.WrappedException: Wrapped javax.script.ScriptException: Invalid arguments when setting sso configuration values. (/api-store/site/themes/wso2/templates/sso/filter/template.jag#61)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.api_store.site.themes.wso_2.templates.sso.filter.c0._c_anonymous_1(/api-store/site/themes/wso2/templates/sso/filter/template.jag:61)
	at org.jaggeryjs.rhino.api_store.site.themes.wso_2.templates.sso.filter.c0.call(/api-store/site/themes/wso2/templates/sso/filter/template.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.api_store.jagg.c0._c_anonymous_26(/api-store/jagg/jagg.jag:243)
	at org.jaggeryjs.rhino.api_store.jagg.c0.call(/api-store/jagg/jagg.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.api_store.jagg.c0._c_anonymous_51(/api-store/jagg/jagg.jag:684)
	at org.jaggeryjs.rhino.api_store.jagg.c0.call(/api-store/jagg/jagg.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.api_store.site.pages.c0._c_anonymous_1(/api-store/site/pages/list-apis.jag:14)
	at org.jaggeryjs.rhino.api_store.site.pages.c0.call(/api-store/site/pages/list-apis.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
	at org.jaggeryjs.rhino.api_store.site.pages.c0._c_script_0(/api-store/site/pages/list-apis.jag:10)
	at org.jaggeryjs.rhino.api_store.site.pages.c0.call(/api-store/site/pages/list-apis.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.api_store.site.pages.c0.call(/api-store/site/pages/list-apis.jag)
	at org.jaggeryjs.rhino.api_store.site.pages.c0.exec(/api-store/site/pages/list-apis.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	... 45 more
Caused by: javax.script.ScriptException: Invalid arguments when setting sso configuration values.
	at org.wso2.carbon.hostobjects.sso.SAMLSSORelyingPartyObject.jsFunction_setProperty(SAMLSSORelyingPartyObject.java:694)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 66 more
```

**Comment by kavithasub** [comment]
Hi,
Please add more details in the issues(e.g. steps to recreate, description) when creating bugs moving forward :)
Because the exactly same error[1] I received while SSO login to /store app using latest apim pack, but I don't have any clue here how the above error observed to analyze my issue further.
`
[2018-03-08 20:52:34,688] ERROR - WebAppManager org.mozilla.javascript.WrappedException: Wrapped javax.script.ScriptException: Invalid arguments when setting sso configuration values. (/store/jagg/jaggery_acs.jag#58)
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped javax.script.ScriptException: Invalid arguments when setting sso configuration values. (/store/jagg/jaggery_acs.jag#58)...`

**Comment by Megala21** [comment]
In iot server, we have a script, to configure it with an ip addreess. Please refer [1]. After executing that script, I got the above issue.

Re-producing steps would be 

- Execute the change-ip.sh as in [1]
- Start the server and login to apim-store.

I think you were getting this issue due to [2]. This can happen, if there are any parameters missing parameters in sso configuration in site.json of store.

[1] https://docs.wso2.com/display/IoTS310/Configuring+the+IP+or+Hostname
[2] https://github.com/wso2/product-apim/issues/2807

**Comment by kavithasub** [comment]
Thank you so much! @Megala21 for shared details. :)
