### ISSUE TITLE
WSO2 IOT UPDATE1 : Store does not work with multi-tenants

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#1383]
Hi,

There is a bug with the store, in WSO2 IOT UPDATE1
The context :
I created a new Tenants in carbon wso2. Once created, I can record my devices without any problems.

With publisher, I log in with my admin account of the new Tenant. I put up my new application and there too, I have no problem.

In the Store, I log in with my admin account of my new Tenant. I find my new application without any problem: 

<a href="https://www.hostingpics.net/viewer.php?id=898361BugStore01.png"><img src="https://img11.hostingpics.net/thumbs/mini_898361BugStore01.png" alt="Heberger image" /></a>

But when I click on it here is what I have:

<a href="https://www.hostingpics.net/viewer.php?id=627296BugStore02.png"><img src="https://img11.hostingpics.net/thumbs/mini_627296BugStore02.png" alt="Heberger image" /></a>

We can also see in the console iot-server.sh that there is a problem:

```
 ERROR - {org.jaggeryjs.jaggery.core.manager.WebAppManager} org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.appmgt.mobile.utils.MobileApplicationException: Received empty device list for getAllDeviceInfo (/store/extensions/assets/mobileapp/pages/asset.jag#95) (/store/controllers/routers/assets.jag#77)
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.appmgt.mobile.utils.MobileApplicationException: Received empty device list for getAllDeviceInfo (/store/extensions/assets/mobileapp/pages/asset.jag#95) (/store/controllers/routers/assets.jag#77)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.URLBasedCachePreventionFilter.doFilter(URLBasedCachePreventionFilter.java:57)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:45)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.appmgt.mobile.utils.MobileApplicationException: Received empty device list for getAllDeviceInfo (/store/extensions/assets/mobileapp/pages/asset.jag#95) (/store/controllers/routers/assets.jag#77)
```
Thanks

**Comment by sameerawickramasekara** [comment]
Hi @Tofdu31 ,

I have followed the steps below to reproduce the issue with the IoTS 3.1.0-Update1 release.

1.Created a new tenant. 
2.Enrolled an Android device with new Tenant.
3.Published an app to through the publisher from new Tenant.
4.Installed the app to the device through the Store

App was successfully installed on the device.

Since it was not reproducible this issue is closed. Please reopen if it persists 
@ruwany Please close the issue.

Regards,
Sameera

**Comment by ghost** [comment]
hi,
Do you perform your tests with a server that has an IP address or localhost?
The bug is on a server with an IP address

**Comment by ghost** [comment]
Here is a new point on my bug,

After creating a new Tenants; I noticed in the console that if I connect to "devicemgt", "store" I have no error in the console.

On the other hand, when I connect to publisher, here is what I have as error:

> [2017-09-07 12:14:09,651] [IoT-Core] ERROR - {org.wso2.carbon.identity.authenticator.saml2.sso.SAML2SSOAuthenticator} Authentication Request is rejected. Signature validation failed.
> [2017-09-07 12:14:09,652] [IoT-Core]  WARN - {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} Failed Administrator login attempt 'admin@test.fr[1]' at [2017-09-07 12:14:09,652-0400]

Still, I'm well connected to Publisher

I think it's important to find the concern for that side to start with.

**Comment by ghost** [comment]
1.Created a new tenant.
2. **Change IP**

3. i'm loging to devicemgt with new tenant : All it's ok (console and web interface)
4. i'm loging to store with new tenant : All it's ok (console and web interface)
5. i'm loging to publisher with new tenant : ok for web interface but it's no ok in console : 

```
[2017-09-07 16:49:21,842] [IoT-Core] ERROR - {org.wso2.carbon.identity.authenticator.saml2.sso.SAML2SSOAuthenticator} Authentication Request is rejected. Signature validation failed.
[2017-09-07 16:49:21,842] [IoT-Core]  WARN - {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} Failed Administrator login attempt 'admin@test.fr[1]' at [2017-09-07 16:49:21,842-0400]
```
By adding an application in publisher, I just can see an error of authentication:

```
[2017-09-07 17:34:50,848] [IoT-Core] ERROR - {org.wso2.carbon.identity.authenticator.saml2.sso.SAML2SSOAuthenticator} Authentication Request is rejected. Signature validation failed.
[2017-09-07 17:34:50,848] [IoT-Core]  WARN - {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} Failed Administrator login attempt 'admin@test.fr[1]' at [2017-09-07 17:34:50,848-0400]
```

**Comment by sameerawickramasekara** [comment]
Hi ,

I will follow these steps and get back to you soon. did you run the change-ip script after creating a new tenant?

Regards

**Comment by ghost** [comment]
Hi @sameerawickramasekara 

I have developed a personal script but rely on your script changeip.sh as it lacks some information in it.

Nothing very important that could bug only Publisher authentication.

I'm looking on the net, apparently, there have been several similar problems with WSO2 EMM

Best regards

**Comment by sameerawickramasekara** [comment]
Hi @Tofdu31 

I was able to reproduce the error log you have mentioned. I have created an issue for that
you can track it here #1404 .
but a 500 response was not reproducible after following all the steps . Hence this issue will be closed.

Regards,
Sameera

**Comment by janakact** [comment]
Got the same error. Fixed by restarting the server.
