### ISSUE TITLE
Mutual SSL not working... Certificate DN Name Exception after following the documentation

### ISSUE THREAD

**Issue by kolemartins** [wso2/product-iots#1674]
After almost a whole day trying out Mustual SSL with self sign cert. This is all I get:

org.wso2.carbon.certificate.mgt.core.exception.KeystoreException: Invalid name exception while trying to create a LDAP name using the distinguished name
        at org.wso2.carbon.certificate.mgt.core.impl.CertificateGenerator.verifyCertificateDN(CertificateGenerator.java:335)
        at org.wso2.carbon.certificate.mgt.core.service.CertificateManagementServiceImpl.verifySubjectDN(CertificateManagementServiceImpl.java:110)
        at org.wso2.carbon.webapp.authenticator.framework.authenticator.CertificateAuthenticator.authenticate(CertificateAuthenticator.java:79)
        at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:56)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1770)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1729)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.naming.InvalidNameException: Invalid name: xxx.xxxx.xxxx
        at javax.naming.ldap.Rfc2253Parser.doParse(Rfc2253Parser.java:111)
        at javax.naming.ldap.Rfc2253Parser.parseDn(Rfc2253Parser.java:70)
        at javax.naming.ldap.LdapName.parse(LdapName.java:785)
        at javax.naming.ldap.LdapName.<init>(LdapName.java:123)
        at org.wso2.carbon.certificate.mgt.core.impl.CertificateGenerator.verifyCertificateDN(CertificateGenerator.java:333)
        ... 18 more

**Comment by 6xhhs** [comment]
were you able  to solve this error?

**Comment by charlie89grasshopper** [comment]
Do you ever manage to sort out this error
