### ISSUE TITLE
Wso2 İot Server - Error after changing super-admin password

### ISSUE THREAD

**Issue by omerstack** [wso2/product-iots#1813]
**Description:**
I get an error after changing the super-admin password.

**Affected Product Version:**
Wso2 iot Server 3.3.0  - Agent v3.1.32
   or
Wso2 İot Server 3.20 RC4 - Agent v3.1.31

**OS, DB, other environment details and versions:**
Ubuntu 14.04.1 LTS / Java(TM) SE Runtime Environment (build 1.8.0_161-b12)

The steps are below 
1.  Ip Congiguration 
      <IOTS_HOME>/scripts
      ./change-ip.sh

2. Geofence
     <IOTS_HOME>/wso2/analytics/scripts
     mvn clean install -f siddhi-geo-extention-deployer.xml 
     ....

3. Https Configuration
  https://docs.wso2.com/display/IoTS330/Configuring+Android+for+HTTPS+Communication 

4. Wso2 Agent
    https://docs.wso2.com/display/IoTS310/Integrating+the+Android+System+Service+Application 

5. https://docs.wso2.com/display/IoTS320/Changing+the+Super+Administrator+Username+and+Password
./change-superadmin-credentials.sh use.

6. Project run and constantly error.

**Error:**
```
[2018-04-12 17:59:02,257] [IoT-Core]  WARN - {org.wso2.carbon.databridge.agent.endpoint.DataEndpointGroup} No receiver is reachable at reconnection, will try to reconnect every 30 sec
[2018-04-12 17:59:02,287] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker} Thrift Authentication Exception
org.wso2.carbon.databridge.agent.exception.DataEndpointAuthenticationException: Thrift Authentication Exception
	at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftDataEndpoint.login(ThriftDataEndpoint.java:47)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:93)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: ThriftAuthenticationException(message:wrong userName or password)
	at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$connect_result$connect_resultStandardScheme.read(ThriftSecureEventTransmissionService.java:2020)
	at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$connect_result$connect_resultStandardScheme.read(ThriftSecureEventTransmissionService.java:1998)
	at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$connect_result.read(ThriftSecureEventTransmissionService.java:1940)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$Client.recv_connect(ThriftSecureEventTransmissionService.java:110)
	at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$Client.connect(ThriftSecureEventTransmissionService.java:96)
	at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftDataEndpoint.login(ThriftDataEndpoint.java:45)
	... 7 more
[2018-04-12 17:59:02,288] [IoT-Core] ERROR - {org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker} Error while trying to connect to the endpoint. Cannot borrow client for ssl://localhost:7713
org.wso2.carbon.databridge.agent.exception.DataEndpointAuthenticationException: Cannot borrow client for ssl://localhost:7713
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:99)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.databridge.agent.exception.DataEndpointAuthenticationException: Thrift Authentication Exception
	at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftDataEndpoint.login(ThriftDataEndpoint.java:47)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:93)
	... 6 more
Caused by: ThriftAuthenticationException(message:wrong userName or password)
	at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$connect_result$connect_resultStandardScheme.read(ThriftSecureEventTransmissionService.java:2020)
	at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$connect_result$connect_resultStandardScheme.read(ThriftSecureEventTransmissionService.java:1998)
	at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$connect_result.read(ThriftSecureEventTransmissionService.java:1940)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$Client.recv_connect(ThriftSecureEventTransmissionService.java:110)
	at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$Client.connect(ThriftSecureEventTransmissionService.java:96)
	at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftDataEndpoint.login(ThriftDataEndpoint.java:45)
```

**Comment by rasika** [comment]
@omerstack There's a known issue when changing the super admin username it might break some functionalities. Could you please try changing only the password of the super admin and keep the username intact?
