### ISSUE TITLE
[ Windows ]Unable to create New user and Login in IoT 3.3.0

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-iots#1830]
**Description:**
When creating a new user and try to log in with it, **AUTHENTICATION ERROR** Is thrown.

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
IoT 3.3.0

**OS, DB, other environment details and versions:** 
Windows OS   

**Steps to reproduce:**

1. Start the IoT 3.3.0 pack in Windows.
2. Create a user in device mgt portal.
3. Try to log in with it. The following error is thrown in the backend.

 [IoT-Core] ERROR - {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} Exception in Authentication Framework                                            java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils                                                                                                                                                                                  at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.getDriverName(JdbcTemplate.java:336)                                                                                                                                                     at org.wso2.carbon.consent.mgt.core.util.JdbcUtils.isDBTypeOf(JdbcUtils.java:100)                                                                                                                                                            at org.wso2.carbon.consent.mgt.core.util.JdbcUtils.isH2MySqlOrPostgresDB(JdbcUtils.java:54)                                                                                                                                                  at org.wso2.carbon.consent.mgt.core.dao.impl.ReceiptDAOImpl.searchReceipt(ReceiptDAOImpl.java:316)                                                                                                                                           at org.wso2.carbon.consent.mgt.core.dao.impl.ReceiptDAOImpl.searchReceipts(ReceiptDAOImpl.java:290)                                                                                                                                          at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.searchReceipts(ConsentManagerImpl.java:589)                                                                                                                                           at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.searchReceipts(ConsentManagerImpl.java:562)                                                                                                                                           at org.wso2.carbon.consent.mgt.core.InterceptingConsentManager$21.execute(InterceptingConsentManager.java:546)                                                                                                                               at org.wso2.carbon.consent.mgt.core.InterceptingConsentManager$21.execute(InterceptingConsentManager.java:542)                                                                                                                               at org.wso2.carbon.consent.mgt.core.model.ConsentInterceptorTemplate.executeWith(ConsentInterceptorTemplate.java:56)                                                                                                                         at org.wso2.carbon.consent.mgt.core.InterceptingConsentManager.searchReceipts(InterceptingConsentManager.java:542)                                                                                                                           at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.consent.SSOConsentServiceImpl.getReceiptListOfUserForSP(SSOConsentServiceImpl.java:767)                                                                at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.consent.SSOConsentServiceImpl.getConsentReceiptOfUser(SSOConsentServiceImpl.java:382)                                                                  at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.consent.SSOConsentServiceImpl.getConsentRequiredClaims(SSOConsentServiceImpl.java:218)                                                                 at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.consent.SSOConsentServiceImpl.getConsentRequiredClaimsWithExistingConsents(SSOConsentServiceImpl.java:132)                                             at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.consent.ConsentMgtPostAuthnHandler.handlePreConsent(ConsentMgtPostAuthnHandler.java:147)                                                               at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.consent.ConsentMgtPostAuthnHandler.handle(ConsentMgtPostAuthnHandler.java:106)                                                                         at org.wso2.carbon.identity.application.authentication.framework.services.PostAuthenticationMgtService.executePostAuthnHandler(PostAuthenticationMgtService.java:109)                                                                        at org.wso2.carbon.identity.application.authentication.framework.services.PostAuthenticationMgtService.handlePostAuthentication(PostAuthenticationMgtService.java:78)                                                                        at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handlePostAuthentication(DefaultAuthenticationRequestHandler.java:165)                                             at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:134)                                                               at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:157)                                                                                   at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53)                                                                                             at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)                                                                                                                                                                              at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)                                                                                                                                                                              at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)                                                                                                                                      at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)                                                                                                                                        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)                                                                                                                                                at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)                                                                                                                                                      at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)                                                                                                                                                                              at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)                                                                                                                                                   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)                                                                                                                                         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                                                                                                                                                 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)                                                                                                                                                                    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                                                                                                                                         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                                                                                                                                                 at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)                                                                                                                                                                     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                                                                                                                                         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                                                                                                                                                 at org.wso2.carbon.ui.filters.CSRFPreventionFilter.doFilter(CSRFPreventionFilter.java:88)                                                                                                                                                    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                                                                                                                                         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                                                                                                                                                 at org.wso2.carbon.ui.filters.CRLFPreventionFilter.doFilter(CRLFPreventionFilter.java:61)                                                                                                                                                    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                                                                                                                                         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                                                                                                                                                 at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)                                                                                                                                                 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                                                                                                                                         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                                                                                                                                                 at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)                                                                                                                                          at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                                                                                                                                         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                                                                                                                                                 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)                                                                                                                                                       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)                                                                                                                                                       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)                                                                                                                                                             at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)                                                                                                                                                             at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)                                                                                                                                               at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)                                                                                                                                                   at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)                                                                                                                                                    at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:46)                                                                                                                        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)                                                                                                                                         at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)                                                                                                                                                           at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)                                                                                                                        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)                                                                                                                                                                 at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)                                                                                                                                     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)                                                                                                                                                         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)                                                                                                                                                               at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)                                                                                                                                               at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)                                                                                                                                           at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)                                                                                                                                                       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)                                                                                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)                                                                                                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)                                                                                                                                                                        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)                                                                                                                                                        at java.lang.Thread.run(Unknown Source)                                                                                                                                                                                              Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils cannot be found by org.wso2.carbon.database.utils_2.0.6                                                                                                             at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)                                                                                                                                                    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)                                                                                                                                                            at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)                                                                                                                                                            at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)                                                                                                                                           at java.lang.ClassLoader.loadClass(Unknown Source)                                                                                                                                                                                           ... 74 more`

This can be solved by importing 

org.apache.commons.lang.* package in org.wso2.carbon.database.utils_2.0.6 jar. 
https://github.com/wso2/carbon-utils/blob/master/components/org.wso2.carbon.database.utils/pom.xml#L140

**Comment by jkuek** [comment]
See https://github.com/wso2/product-iots/pull/1838 for resolution

**Comment by Naveen97-hacker** [comment]
how to import that pom.xml file
