### ISSUE TITLE
Cannot use remote session after changing admin password

### ISSUE THREAD

**Issue by AdAzMa** [wso2/product-iots#1836]
**Description:**
After changing the admin password using [https://docs.wso2.com/display/IoTS330/Changing+the+Super+Administrator+Username+and+Password](url) I cannot use remote session on an android device anymore. I put the errors I get in the bottom. Before changing the password it worked just fine. I changed the password both manually and using the change-superadmin-credentials.sh script.
I think I also have to change the admin password in files other than the ones mentioned in the documentation. If this is the case, in what files do I have to change the password?
Thanks in advance. 

**Suggested Labels:**
wso2, iot, remote session

**Affected Product Version:**
IoT 3.3.0

**OS, DB, other environment details and versions:**    
Ubuntu 18.04

**Steps to reproduce:**
On a clean install of IOT-server:
1. Change the admin password using [https://docs.wso2.com/display/IoTS330/Changing+the+Super+Administrator+Username+and+Password] (Both manually as using the change-superadmin-credentials.sh script)
2. Enroll an android device.
3. Start a remote session on this device.

Error when starting the session:
`TID: [-1234] [] [2018-06-06 11:53:00,039] ERROR {org.wso2.carbon.core.services.authentication.AbstractAuthenticator} -  Invalid domain  : rt {org.wso2.carbon.core.services.authentication.AbstractAuthenticator}
TID: [-1234] [] [2018-06-06 11:53:00,040]  WARN {org.wso2.carbon.server.admin.module.handler.AuthenticationHandler} -  Illegal access attempt at [2018-06-06 11:53:00,0040] from IP address 127.0.0.1 while trying to authenticate access to service OAuth2TokenValidationService {org.wso2.carbon.server.admin.module.handler.AuthenticationHandler}
TID: [-1234] [] [2018-06-06 11:53:00,040] ERROR {org.apache.axis2.engine.AxisEngine} -  Access Denied. Authentication failed - System error occurred. Please check server logs for more details. {org.apache.axis2.engine.AxisEngine}
org.apache.axis2.AxisFault: Access Denied. Authentication failed - System error occurred. Please check server logs for more details.
        at org.wso2.carbon.server.admin.module.handler.AuthenticationHandler.authenticate(AuthenticationHandler.java:125)
        at org.wso2.carbon.server.admin.module.handler.AuthenticationHandler.invoke(AuthenticationHandler.java:66)
        at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
        at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
        at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
        at org.apache.axis2.transport.http.HTTPTransportUtils.processHTTPPostRequest(HTTPTransportUtils.java:173)
        at org.apache.axis2.transport.http.AxisServlet.doPost(AxisServlet.java:147)
        at org.wso2.carbon.core.transports.CarbonServlet.doPost(CarbonServlet.java:232)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:72)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.wso2.carbon.ui.filters.CSRFPreventionFilter.doFilter(CSRFPreventionFilter.java:88)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.wso2.carbon.ui.filters.CRLFPreventionFilter.doFilter(CRLFPreventionFilter.java:61)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
        at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
        at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
        at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:46)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2018-06-06 11:53:00,047] ERROR {org.wso2.carbon.device.mgt.extensions.remote.session.authentication.oauth.OAuthTokenValidator} -  Error on connecting with the validation endpoint. {org.wso2.carbon.device.mgt.extensions.remote.session.authentication.oauth.OAuthTokenValidator}
org.apache.axis2.AxisFault: Access Denied. Authentication failed - System error occurred. Please check server logs for more details.
        at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
        at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:381)
        at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:456)
        at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:227)
        at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
        at org.wso2.carbon.identity.oauth2.stub.OAuth2TokenValidationServiceStub.validate(OAuth2TokenValidationServiceStub.java:738)
        at org.wso2.carbon.device.mgt.extensions.remote.session.authentication.oauth.OAuthTokenValidator.getAuthenticationInfo(OAuthTokenValidator.java:118)
        at org.wso2.carbon.device.mgt.extensions.remote.session.authentication.oauth.OAuthTokenValidator.validateToken(OAuthTokenValidator.java:72)
        at org.wso2.carbon.device.mgt.extensions.remote.session.authentication.OAuthAuthenticator.isAuthenticated(OAuthAuthenticator.java:34)
        at org.wso2.carbon.device.mgt.extensions.remote.session.RemoteSessionManagementServiceImpl.initializeSession(RemoteSessionManagementServiceImpl.java:77)
        at org.wso2.carbon.device.mgt.extensions.remote.session.RemoteSessionManagementServiceImpl.initializeSession(RemoteSessionManagementServiceImpl.java:141)
        at org.wso2.carbon.device.mgt.extensions.remote.session.endpoint.ClientSessionSubscriptionEndpoint.onOpen(ClientSessionSubscriptionEndpoint.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.websocket.pojo.PojoEndpointBase.doOnOpen(PojoEndpointBase.java:66)
        at org.apache.tomcat.websocket.pojo.PojoEndpointServer.onOpen(PojoEndpointServer.java:70)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:137)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:663)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by warunalakshitha** [comment]
We need to change KeyManager configuration in wso2iot-3.3.0/conf/cdm-config.xml file as below.

    <KeyManagerConfiguration>
        <ServerUrl>https://localhost:9443</ServerUrl>
        <AdminUsername>admin</AdminUsername>
        <AdminPassword>newPassword</AdminPassword>
    </KeyManagerConfiguration>

**Comment by AdAzMa** [comment]
I have already changed all the passwords in the files that are in the script. I'm still facing this problem. 
What I think is strange is that this error is also given: 
`{org.wso2.carbon.core.services.authentication.AbstractAuthenticator} - Invalid domain : rt `
Even though this is not my domain. Maybe there is a file where I can change this?

**Comment by AdAzMa** [comment]
I still haven't found a solution for this problem. I had already changed the file that you mentioned, but I'm not sure what you meant by your comment. Is this a bug or am I doing something wrong?

**Comment by shifudeen** [comment]
I face the same issue on 3.3.0.. The weird part is the log is showing my password is now considered as a user. Say my password is admin123, and when i choose remote session to a device, the system is taking my admin password and searching in local and ldap user repository and fail. Of course it will fail because there is no such user called admin123. It seems somewhere in config admin password value is used as user name.

**Comment by anton-svetlosak** [comment]
I think that the same issue is described here: https://github.com/wso2/carbon-device-mgt-plugins/issues/907
