### ISSUE TITLE
After some time, Connot open https://IP:9445/carbon/

### ISSUE THREAD

**Issue by knight19** [wso2/product-iots#1858]
I need to restart ./iot-server.sh
Affected Product Version:
 3.3.0
 OS, DB, other environment details and versions:
 ubuntu16.04  java version "1.8.0_181"

[2018-08-31 20:39:31,019] [IoT-Core] ERROR - {org.apache.catalina.core.ApplicationDispatcher} Servlet.service() for servlet bridgeservlet threw exception
java.lang.ClassNotFoundException: org.apache.jsp.admin.layout.template_jsp
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:132)
        at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:63)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:157)
        at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:172)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:376)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)

[2018-08-31 20:39:31,020] [IoT-Core] ERROR - {org.apache.tiles.servlet.context.ServletTilesRequestContext} Servlet Exception while including path
org.apache.jasper.JasperException: java.lang.ClassNotFoundException: org.apache.jsp.admin.layout.template_jsp
        at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:177)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:376)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
        at javax.servlet.http.HttpServlet.service(HttpServlet

[2018-08-31 20:39:31,023] [IoT-Core] ERROR - {org.apache.tiles.impl.BasicTilesContainer} Error rendering tile
java.io.IOException: Error including path '/admin/layout/template.jsp'. java.lang.ClassNotFoundException: org.apache.jsp.admin.layout.template_jsp
        at org.apache.tiles.servlet.context.ServletTilesRequestContext.forward(ServletTilesRequestContext.java:201)
        at org.apache.tiles.servlet.context.ServletTilesRequestContext.dispatch(ServletTilesRequestContext.java:185)
        at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:419)
        at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:370)
        at org.wso2.carbon.ui.action.ActionHelper.render(ActionHelper.java:52)
        at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:101)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)

![manage console error](https://user-images.githubusercontent.com/28888287/44886968-47bb6680-acfc-11e8-92c3-8117507f5c5a.png)

![manage console error1](https://user-images.githubusercontent.com/28888287/44886971-4db14780-acfc-11e8-96b8-855492ddb26b.png)
![manage console error2](https://user-images.githubusercontent.com/28888287/44886978-50ac3800-acfc-11e8-8188-5f0d6a49e617.png)

**Comment by knight19** [comment]
It happens a lot.
