### ISSUE TITLE
Error while enrolling Arduino device via Ethernet

### ISSUE THREAD

**Issue by shaheenk94** [wso2/product-iots#1886]
I'm currently exploring the WSO2 IoT Server and trying to enroll Arduino devices. The sketch downloaded from the server is for WiFi Shield and I'm using an Ethernet shield. So, I made necessary changes in the sketch and uploaded it. The following error popped up on my terminal and the following on the Serial:

(I used service port : 8280, please let me know if other port is to be used)

Error on Terminal

```
[2018-11-02 17:27:54,595] [IoT-Core] ERROR - {org.apache.synapse.transport.passthru.SourceHandler} HttpException occurred
org.apache.http.ProtocolException: Invalid request line:
        at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:208)
        at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection$LoggingNHttpMessageParser.parse(LoggingNHttpServerConnection.java:407)
        at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection$LoggingNHttpMessageParser.parse(LoggingNHttpServerConnection.java:381)
        at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:265)
        at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.consumeInput(LoggingNHttpServerConnection.java:114)
        at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:82)
        at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:113)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.ParseException: Invalid request line:
        at org.apache.http.message.BasicLineParser.parseRequestLine(BasicLineParser.java:287)
        at org.apache.http.impl.nio.codecs.DefaultHttpRequestParser.createMessage(DefaultHttpRequestParser.java:119)
        at org.apache.http.impl.nio.codecs.DefaultHttpRequestParser.createMessage(DefaultHttpRequestParser.java:51)
        at org.apache.http.impl.nio.codecs.AbstractMessageParser.parseHeadLine(AbstractMessageParser.java:156)
        at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:206)
        ... 14 more
[2018-11-02 17:27:55,888] [IoT-Core] ERROR - {org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl} Invalid OAuth Token : Access token expired
[2018-11-02 17:27:55,892] [IoT-Core]  WARN - {org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler} API authentication failure due to Invalid Credentials
[2018-11-02 17:27:55,895] [IoT-Core] ERROR - {org.apache.synapse.transport.passthru.SourceHandler} HttpException occurred
org.apache.http.ProtocolException: Invalid request line: protocol: HTTP
        at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:208)
        at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection$LoggingNHttpMessageParser.parse(LoggingNHttpServerConnection.java:407)
        at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection$LoggingNHttpMessageParser.parse(LoggingNHttpServerConnection.java:381)
        at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:265)
        at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.consumeInput(LoggingNHttpServerConnection.java:114)
        at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:82)
        at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:113)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.ParseException: Invalid request line: protocol: HTTP
        at org.apache.http.message.BasicLineParser.parseRequestLine(BasicLineParser.java:298)
        at org.apache.http.impl.nio.codecs.DefaultHttpRequestParser.createMessage(DefaultHttpRequestParser.java:119)
        at org.apache.http.impl.nio.codecs.DefaultHttpRequestParser.createMessage(DefaultHttpRequestParser.java:51)
        at org.apache.http.impl.nio.codecs.AbstractMessageParser.parseHeadLine(AbstractMessageParser.java:156)
        at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:206)
        ... 14 more
```

Error on Serial:

```
JSON Payload: {"event":{"metaData":{"owner":"admin@carbon.super","deviceId":"vbbwcr05ekx1"}, "payloadData":{

connected
Temperature is
35.81
POST /endpoints/arduino_receiver?deviceId=vbbwcr05ekx1 HTTP/1.1

Content-Type: application/json
Content-Length: 116

{"event":{"metaData":{"owner":"admin@carbon.super","deviceId":"vbbwcr05ekx1"}, "payloadData":{"temperature":35.81}}}
HTTP/1.1 404 Not Found
Content-Type: application/xml; charset=UTF-8
Date: Tue, 06 Nov 2018 05:41:50 GMT
Transfer-Encoding: chunked

110
<am:fault xmlns:am="http://wso2.org/apimanager"><am:code>404</am:code><am:type>Status report</am:type><am:message>Not Found</am:message><am:description>The requested resource (/endpoints/arduino_receiver?deviceId=vbbwcr05ekx1) is not available.</am:description></am:fault>
0

HTTP/1.1 400 Bad request
Connection: Close
Date: Tue, 06 Nov 2018 05:41:50 GMT
Content-Length: 0


-------------------------------
connected
Read Controls
Started..
GET /arduino/device/vbbwcr05ekx1/controls HTTP/1.1
Host: 192.168.1.57:8280
Content-Type: application/json

HTTP/1.1 401 Unauthorized
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET
WWW-Authenticate: OAuth2 realm="WSO2 API Manager", error="invalid token", error_description="The access token expired"
Access-Control-Allow-Headers: authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction
Content-Type: application/xml; charset=UTF-8
Date: Tue, 06 Nov 2018 05:41:51 GMT
Transfer-Encoding: chunked

143
<ams:fault xmlns:ams="http://wso2.org/apimanager/security"><ams:code>900901</ams:code><ams:message>Invalid Credentials</ams:message><ams:description>Access failure for API: /arduino/1.0.0, version: 1.0.0 status: (900901) - Invalid Credentials. Make sure you have given the correct access token</ams:description></ams:fault>
0

HTTP/1.1 400 Bad request
Connection: Close
Date: Tue, 06 Nov 2018 05:41:51 GMT
Content-Length: 0
```

**Comment by shaheenk94** [comment]
[IoT-Core]  WARN - {org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler} API authentication failure due to Invalid Credentials
