### ISSUE TITLE
Issues after changing the admin password manually through configuration files

### ISSUE THREAD

**Issue by Chandrakala95** [wso2/product-iots#1898]
Description:
While changing the admin password through the configuration files, unable to login to device management console due to unauthenticated user error.

Affected Product Version: WSO2 IoT Server 3.1.0

OS, DB, other environment details and versions: Centos 7

Steps to reproduce:
change the admin password by following the steps mentioned in the below link:

https://docs.wso2.com/display/IoTS310/Changing+the+Super+Administrator+Username+and+Password

Related Issues:
       org.wso2.carbon.apimgt.integration.client.OAuthRequestInterceptor.apply(OAuthRequestInterceptor.java:84)
        at feign.SynchronousMethodHandler.targetRequest(SynchronousMethodHandler.java:158)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:88)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
        at com.sun.proxy.$Proxy40.apisGet(Unknown Source)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherServiceImpl.publishAPI(APIPublisherServiceImpl.java:53)
        ... 4 more
[2018-12-05 17:11:04,563] [IoT-Core] ERROR - {org.wso2.carbon.apimgt.rest.api.util.interceptors.auth.BasicAuthenticationInterceptor} Authentication failed. Please check your username/password
[2018-12-05 17:11:04,564] [IoT-Core] ERROR - {org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler} failed to publish api.
org.wso2.carbon.apimgt.webapp.publisher.exception.APIManagerPublisherException: feign.FeignException: status 401 reading DCRClient#register(ClientProfile)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherServiceImpl.publishAPI(APIPublisherServiceImpl.java:75)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler.publishAPIs(APIPublisherStartupHandler.java:97)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler.access$500(APIPublisherStartupHandler.java:30)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler$1.run(APIPublisherStartupHandler.java:72)
        at java.lang.Thread.run(Thread.java:748)
Caused by: feign.FeignException: status 401 reading DCRClient#register(ClientProfile)
        at feign.FeignException.errorStatus(FeignException.java:62)
        at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:91)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
        at com.sun.proxy.$Proxy26.register(Unknown Source)
        at org.wso2.carbon.apimgt.integration.client.OAuthRequestInterceptor.apply(OAuthRequestInterceptor.java:84)
        at feign.SynchronousMethodHandler.targetRequest(SynchronousMethodHandler.java:158)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:88)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
        at com.sun.proxy.$Proxy40.apisGet(Unknown Source)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherServiceImpl.publishAPI(APIPublisherServiceImpl.java:53)
        ... 4 more
[2018-12-05 17:11:04,574] [IoT-Core] ERROR - {org.wso2.carbon.apimgt.rest.api.util.interceptors.auth.BasicAuthenticationInterceptor} Authentication failed. Please check your username/password
[2018-12-05 17:11:04,575] [IoT-Core] ERROR - {org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler} failed to publish api.
org.wso2.carbon.apimgt.webapp.publisher.exception.APIManagerPublisherException: feign.FeignException: status 401 reading DCRClient#register(ClientProfile)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherServiceImpl.publishAPI(APIPublisherServiceImpl.java:75)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler.publishAPIs(APIPublisherStartupHandler.java:97)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler.access$500(APIPublisherStartupHandler.java:30)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler$1.run(APIPublisherStartupHandler.java:72)
        at java.lang.Thread.run(Thread.java:748)
Caused by: feign.FeignException: status 401 reading DCRClient#register(ClientProfile)
        at feign.FeignException.errorStatus(FeignException.java:62)
        at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:91)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
        at com.sun.proxy.$Proxy26.register(Unknown Source)
        at org.wso2.carbon.apimgt.integration.client.OAuthRequestInterceptor.apply(OAuthRequestInterceptor.java:84)
        at feign.SynchronousMethodHandler.targetRequest(SynchronousMethodHandler.java:158)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:88)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
        at com.sun.proxy.$Proxy40.apisGet(Unknown Source)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherServiceImpl.publishAPI(APIPublisherServiceImpl.java:53)
        ... 4 more
[2018-12-05 17:11:04,588] [IoT-Core] ERROR - {org.wso2.carbon.apimgt.rest.api.util.interceptors.auth.BasicAuthenticationInterceptor} Authentication failed. Please check your username/password
[2018-12-05 17:11:04,590] [IoT-Core] ERROR - {org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler} failed to publish api.
org.wso2.carbon.apimgt.webapp.publisher.exception.APIManagerPublisherException: feign.FeignException: status 401 reading DCRClient#register(ClientProfile)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherServiceImpl.publishAPI(APIPublisherServiceImpl.java:75)
        at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler.publishAPIs(APIPublisherStartupHandler.java:97)

**Comment by zbxzxx** [comment]
the default username & password is admin
you can login  localhost:9443/carbon console and change admin password use the configuration password
hope to resolve your error
