### ISSUE TITLE
iot broker starts, but with errors

### ISSUE THREAD

**Issue by wiwengweng** [wso2/product-iots#1914]
**Description:**

broker.bat starts with error.
````
PS D:\搜狗高速下载\wso2iot-3.3.0\bin> .\broker.bat
"D:\搜狗高~1\WSO2IO~1.0\bin\..\wso2\broker\bin\version.txt"
JAVA_HOME environment variable is set to C:\Program Files\Java\jdk1.8.0_211
CARBON_HOME environment variable is set to D:\搜狗高~1\WSO2IO~1.0\wso2\broker\bin\..
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[2019-04-25 16:12:48,119] [IOT-Broker]  WARN {org.apache.axiom.util.stax.dialect.StAXDialectDetector} -  Unable to determine dialect of the StAX implementation at bundleresource://14.fwk1454127753/
[2019-04-25 16:12:48,119] [IOT-Broker]  WARN {org.apache.axiom.util.stax.dialect.StAXDialectDetector} -  Unable to determine dialect of the StAX implementation at bundleresource://14.fwk1454127753/
 INFO {org.wso2.andes.wso2.internal.QpidBundleActivator} -  Setting BundleContext in PluginManager
[2019-04-25 16:12:49,824] [IOT-Broker]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Starting WSO2 Carbon...
[2019-04-25 16:12:49,827] [IOT-Broker]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Operating System : Windows Server 2016 10.0, amd64
[2019-04-25 16:12:49,833] [IOT-Broker]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Java Home        : C:\Program Files\Java\jdk1.8.0_211\jre
[2019-04-25 16:12:49,834] [IOT-Broker]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Java Version     : 1.8.0_211
[2019-04-25 16:12:49,835] [IOT-Broker]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Java VM          : Java HotSpot(TM) 64-Bit Server VM 25.211-b12,Oracle Corporation
[2019-04-25 16:12:49,836] [IOT-Broker]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Carbon Home      : D:\鎼滅嫍楂榽1\WSO2IO~1.0\wso2\broker\bin\..
[2019-04-25 16:12:49,840] [IOT-Broker]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Java Temp Dir    : D:\鎼滅嫍楂榽1\WSO2IO~1.0\wso2\broker\bin\..\tmp
[2019-04-25 16:12:49,845] [IOT-Broker]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  User             : Administrator, zh-CN, Asia/Shanghai
[2019-04-25 16:12:53,265] [IOT-Broker]  INFO {org.wso2.carbon.registry.core.jdbc.EmbeddedRegistryService} -  Configured Registry in 123ms
[2019-04-25 16:12:53,685] [IOT-Broker]  INFO {org.wso2.carbon.registry.core.internal.RegistryCoreServiceComponent} -  Registry Mode    : READ-WRITE
[2019-04-25 16:12:53,738] [IOT-Broker]  INFO {org.wso2.andes.configuration.AndesConfigurationManager} -  Main andes configuration located at : D:\鎼滅嫍楂榽1\WSO2IO~1.0\wso2\broker\bin\..\conf\broker.xml
[2019-04-25 16:12:54,001] [IOT-Broker]  INFO {org.wso2.andes.configuration.AndesConfigurationManager} -  Main andes configuration located at : D:\鎼滅嫍楂榽1\WSO2IO~1.0\wso2\broker\bin\..\conf\broker.xml
[2019-04-25 16:12:54,290] [IOT-Broker]  INFO {org.wso2.carbon.metrics.impl.util.JmxReporterBuilder} -  Creating JMX reporter for Metrics with domain 'org.wso2.carbon.metrics'
[2019-04-25 16:12:54,316] [IOT-Broker]  INFO {org.wso2.carbon.metrics.impl.util.JDBCReporterBuilder} -  Creating JDBC reporter for Metrics with source 'win50', data source 'jdbc/WSO2MetricsDB' and 60 seconds polling period
[2019-04-25 16:12:54,328] [IOT-Broker]  INFO {org.wso2.carbon.metrics.impl.reporter.AbstractReporter} -  Started JDBC reporter for Metrics
[2019-04-25 16:12:54,330] [IOT-Broker]  INFO {org.wso2.carbon.metrics.impl.reporter.AbstractReporter} -  Started JMX reporter for Metrics
[2019-04-25 16:12:58,665] [IOT-Broker]  INFO {org.wso2.carbon.registry.indexing.solr.SolrClient} -  Default Embedded Solr Server Initialized
[2019-04-25 16:12:59,053] [IOT-Broker]  INFO {org.wso2.carbon.user.core.internal.UserStoreMgtDSComponent} -  Carbon UserStoreMgtDSComponent activated successfully.
[2019-04-25 16:13:33,231] [IOT-Broker]  INFO {org.apache.axis2.deployment.ClusterBuilder} -  Clustering has been disabled
[2019-04-25 16:13:33,631] [IOT-Broker]  INFO {org.wso2.carbon.identity.user.store.configuration.deployer.UserStoreConfigurationDeployer} -  User Store Configuration Deployer initiated.
[2019-04-25 16:14:09,569] [IOT-Broker]  INFO {org.wso2.carbon.identity.user.store.configuration.deployer.UserStoreConfigurationDeployer} -  User Store Configuration Deployer initiated.
[2019-04-25 16:14:11,146] [IOT-Broker]  INFO {org.apache.axis2.deployment.ModuleDeployer} -  Deploying module: addressing-1.6.1-wso2v23 - file:/D:/鎼滅嫍楂榽1/WSO2IO~1.0/wso2/broker/bin/../repository/deployment/client/modules/addressing-1.6.1-wso2v23.mar
[2019-04-25 16:14:11,826] [IOT-Broker]  INFO {org.apache.axis2.deployment.DeploymentEngine} -  Deploying Web service: org.wso2.carbon.andes.admin-3.2.34 -
[2019-04-25 16:14:11,860] [IOT-Broker]  INFO {org.apache.axis2.deployment.DeploymentEngine} -  Deploying Web service: org.wso2.carbon.andes.admin.mqtt-3.2.34 -
[2019-04-25 16:14:11,931] [IOT-Broker]  INFO {org.apache.axis2.deployment.DeploymentEngine} -  Deploying Web service: org.wso2.carbon.andes.event.admin-3.2.34 -
[2019-04-25 16:14:13,715] [IOT-Broker]  INFO {org.wso2.carbon.core.init.CarbonServerManager} -  Repository       : D:\鎼滅嫍楂榽1\WSO2IO~1.0\wso2\broker\bin\../repository/deployment/server/
[2019-04-25 16:14:13,735] [IOT-Broker]  INFO {org.wso2.carbon.andes.core.internal.ds.QueueManagerServiceDS} -  Successfully created the queue manager service
[2019-04-25 16:14:13,745] [IOT-Broker]  INFO {org.wso2.carbon.andes.core.internal.ds.SubscriptionManagerServiceDS} -  Successfully created the subscription manager service
[2019-04-25 16:14:13,805] [IOT-Broker]  INFO {org.wso2.carbon.core.multitenancy.eager.TenantLoadingConfig} -  Using tenant lazy loading policy...
[2019-04-25 16:14:13,832] [IOT-Broker]  INFO {org.wso2.carbon.core.internal.permission.update.PermissionUpdater} -  Permission cache updated for tenant -1234
[2019-04-25 16:14:14,234] [IOT-Broker]  INFO {org.wso2.andes.configuration.AndesConfigurationManager} -  Main andes configuration located at : D:\鎼滅嫍楂榽1\WSO2IO~1.0\wso2\broker\bin\..\conf\broker.xml
[2019-04-25 16:14:14,272] [IOT-Broker]  INFO {org.wso2.carbon.andes.internal.QpidServiceComponent} -  Activating Andes Message Broker Engine...
[2019-04-25 16:14:14,295] [IOT-Broker]  INFO {org.wso2.andes.server.Broker} -  Starting Qpid using configuration : D:\鎼滅嫍楂榽1\WSO2IO~1.0\wso2\broker\bin\..\conf\advanced\qpid-config.xml
[2019-04-25 16:14:14,352] [IOT-Broker]  INFO {org.wso2.andes.configuration.qpid.ServerConfiguration} -  Signal HUP not supported for OS: Windows Server 2016
[2019-04-25 16:14:14,354] [IOT-Broker]  INFO {org.wso2.andes.server.registry.ApplicationRegistry} -  Initialising Application Registry(org.wso2.andes.server.registry.ConfigurationFileApplicationRegistry@395404ae)
[2019-04-25 16:14:14,394] [IOT-Broker]  INFO {org.wso2.andes.server.plugins.PluginManager} -  Opened service trackers
[Broker] BRK-1001 : Startup : Version: 0.11 Build: 90784:90849
[2019-04-25 16:14:14,522] [IOT-Broker]  INFO {org.wso2.andes.server.management.JMXManagedObjectRegistry} -  Initialising managed object registry using jplatform MBean server
[2019-04-25 16:14:14,529] [IOT-Broker]  INFO {org.wso2.andes.server.security.auth.manager.PrincipalDatabaseAuthenticationManager} -  PrincipalDatabase concrete implementation : org.wso2.carbon.andes.authentication.andes.CarbonBasedPrincipalDatabase
[2019-04-25 16:14:14,535] [IOT-Broker]  INFO {org.wso2.andes.server.security.auth.manager.PrincipalDatabaseAuthenticationManager} -  Initialised PLAIN SASL provider successfully
[2019-04-25 16:14:14,538] [IOT-Broker]  INFO {org.wso2.andes.server.security.auth.manager.PrincipalDatabaseAuthenticationManager} -  Additional SASL providers successfully registered.
[2019-04-25 16:14:14,541] [IOT-Broker]  INFO {org.wso2.andes.server.security.auth.manager.PrincipalDatabaseAuthenticationManager} -  Registering UserManagementMBean
[Broker] MNG-1001 : Startup
[Broker] MNG-1004 : Ready : Using the platform JMX Agent
[2019-04-25 16:14:14,725] [IOT-Broker]  INFO {org.wso2.andes.store.rdbms.RDBMSConnection} -  JDBC connection established with jndi config WSO2MBStoreDB
[2019-04-25 16:14:14,746] [IOT-Broker]  INFO {org.wso2.andes.store.rdbms.RDBMSAndesContextStoreImpl} -  Andes Context Store initialised
[2019-04-25 16:14:14,749] [IOT-Broker]  INFO {org.wso2.andes.kernel.AndesKernelBoot} -  AndesContextStore initialised with org.wso2.andes.store.rdbms.RDBMSAndesContextStoreImpl
[2019-04-25 16:14:14,766] [IOT-Broker]  INFO {org.wso2.andes.store.rdbms.RDBMSConnection} -  JDBC connection established with jndi config WSO2MBStoreDB
[2019-04-25 16:14:14,787] [IOT-Broker]  WARN {org.wso2.andes.configuration.AndesConfigurationManager} -  Error when trying to read property : transaction/maxWaitTimeout. Switching to default value : 30
[2019-04-25 16:14:14,789] [IOT-Broker]  INFO {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Message Store initialised
[2019-04-25 16:14:14,793] [IOT-Broker]  INFO {org.wso2.andes.kernel.AndesKernelBoot} -  Andes MessageStore initialised with org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl
[2019-04-25 16:14:14,848] [IOT-Broker]  INFO {org.wso2.andes.server.cluster.ClusterManager} -  Initializing Standalone Mode. Current Node ID:NODE:win50/192.168.32.83 192.168.32.83
[2019-04-25 16:14:14,859] [IOT-Broker]  INFO {org.wso2.andes.kernel.slot.SlotCreator} -  Slot restoring started for MQTT_Topic_carbon.super/android_sense/+/data_NODE:win50/172.21.0.1
[2019-04-25 16:14:14,859] [IOT-Broker]  INFO {org.wso2.andes.kernel.slot.SlotCreator} -  Slot restoring started for MQTT_Topic_carbon.super/virtual_firealarm/+/temperature_NODE:win50/172.21.0.1
[2019-04-25 16:14:14,865] [IOT-Broker]  INFO {org.wso2.andes.kernel.slot.SlotCreator} -  Slot restoring started for MQTT_Topic_carbon.super/raspberrypi/+/temperature_NODE:win50/172.21.0.1
[2019-04-25 16:14:14,894] [IOT-Broker]  INFO {org.wso2.andes.kernel.slot.SlotCreator} -  Recovered 0 messages for queue "MQTT_Topic_carbon.super/virtual_firealarm/+/temperature_NODE:win50/172.21.0.1".
[2019-04-25 16:14:14,894] [IOT-Broker]  INFO {org.wso2.andes.kernel.slot.SlotCreator} -  Recovered 0 messages for queue "MQTT_Topic_carbon.super/android_sense/+/data_NODE:win50/172.21.0.1".
[2019-04-25 16:14:14,903] [IOT-Broker]  INFO {org.wso2.andes.kernel.slot.SlotCreator} -  Slot restoring ended for MQTT_Topic_carbon.super/android_sense/+/data_NODE:win50/172.21.0.1
[2019-04-25 16:14:14,896] [IOT-Broker]  INFO {org.wso2.andes.kernel.slot.SlotCreator} -  Recovered 0 messages for queue "MQTT_Topic_carbon.super/raspberrypi/+/temperature_NODE:win50/172.21.0.1".
[2019-04-25 16:14:14,896] [IOT-Broker]  INFO {org.wso2.andes.kernel.slot.SlotCreator} -  Slot restoring ended for MQTT_Topic_carbon.super/virtual_firealarm/+/temperature_NODE:win50/172.21.0.1
[2019-04-25 16:14:14,907] [IOT-Broker]  INFO {org.wso2.andes.kernel.slot.SlotCreator} -  Slot restoring ended for MQTT_Topic_carbon.super/raspberrypi/+/temperature_NODE:win50/172.21.0.1
[2019-04-25 16:14:15,081] [IOT-Broker]  INFO {org.wso2.andes.kernel.Andes} -  Andes API initialised.
[2019-04-25 16:14:15,141] [IOT-Broker]  INFO {org.wso2.andes.kernel.AndesChannel} -  Channel created (ID: Internel_channel)
[2019-04-25 16:14:15,154] [IOT-Broker]  INFO {org.wso2.andes.kernel.AndesKernelBoot} -  Syncing exchanges, queues, bindings and subscriptions
[2019-04-25 16:14:15,160] [IOT-Broker]  INFO {org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent} -  Running DB sync task.
[2019-04-25 16:14:15,165] [IOT-Broker]  WARN {org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent} -  Recovering node. Adding exchange messageRouterName=amq.dlc,type=DLC,autoDelete=false
[2019-04-25 16:14:15,171] [IOT-Broker]  INFO {org.wso2.andes.kernel.AndesContextInformationManager} -  Message Router Sync [create]: amq.dlc
[2019-04-25 16:14:15,173] [IOT-Broker]  WARN {org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent} -  Recovering node. Adding queue to queue registry queueName=deadletterchannel,queueOwner=admin,isExclusive=false,isDurable=true,isShared=false,lastPurgedTimestamp=0
[2019-04-25 16:14:15,174] [IOT-Broker]  INFO {org.wso2.andes.kernel.Andes} -  Starting Safe Zone Calculator for slots.
[2019-04-25 16:14:15,191] [IOT-Broker]  WARN {org.wso2.andes.configuration.AndesConfigurationManager} -  Error when trying to read property : performanceTuning/slots/idleTaskDelay. Switching to default value : 100
[2019-04-25 16:14:15,264] [IOT-Broker]  INFO {org.wso2.andes.kernel.AndesContextInformationManager} -  Queue Sync [create]: deadletterchannel
[2019-04-25 16:14:15,267] [IOT-Broker]  WARN {org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent} -  Recovering node. Adding queue to queue registry queueName=MQTT_Topic_carbon.super/android_sense/+/data_NODE:win50/172.21.0.1,queueOwner=admin,isExclusive=false,isDurable=false,isShared=false,lastPurgedTimestamp=0
[2019-04-25 16:14:15,272] [IOT-Broker]  INFO {org.wso2.andes.kernel.AndesContextInformationManager} -  Queue Sync [create]: MQTT_Topic_carbon.super/android_sense/+/data_NODE:win50/172.21.0.1
[2019-04-25 16:14:15,277] [IOT-Broker]  WARN {org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent} -  Recovering node. Adding queue to queue registry queueName=MQTT_Topic_carbon.super/virtual_firealarm/+/temperature_NODE:win50/172.21.0.1,queueOwner=admin,isExclusive=false,isDurable=false,isShared=false,lastPurgedTimestamp=0
[2019-04-25 16:14:15,282] [IOT-Broker]  INFO {org.wso2.andes.kernel.AndesContextInformationManager} -  Queue Sync [create]: MQTT_Topic_carbon.super/virtual_firealarm/+/temperature_NODE:win50/172.21.0.1
[2019-04-25 16:14:15,286] [IOT-Broker]  WARN {org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent} -  Recovering node. Adding queue to queue registry queueName=MQTT_Topic_carbon.super/raspberrypi/+/temperature_NODE:win50/172.21.0.1,queueOwner=admin,isExclusive=false,isDurable=false,isShared=false,lastPurgedTimestamp=0
[2019-04-25 16:14:15,288] [IOT-Broker]  INFO {org.wso2.andes.kernel.AndesContextInformationManager} -  Queue Sync [create]: MQTT_Topic_carbon.super/raspberrypi/+/temperature_NODE:win50/172.21.0.1
[Broker] BRK-1002 : Starting : Listening on TCP port 5675
[2019-04-25 16:14:15,294] [IOT-Broker]  WARN {org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent} -  Recovering node. Adding binding [Binding]E=mqtt.topic/Q=MQTT_Topic_carbon.super/android_sense/+/data_NODE:win50/172.21.0.1/RK=carbon.super/android_sense/+/data/D=false/EX=false
[2019-04-25 16:14:15,298] [IOT-Broker]  INFO {qpid.message.broker.listening} -  [Broker] BRK-1002 : Starting : Listening on TCP port 5675
[2019-04-25 16:14:15,313] [IOT-Broker]  INFO {org.wso2.andes.kernel.AndesContextInformationManager} -  Binding Sync [create]: [Binding]E=mqtt.topic/Q=MQTT_Topic_carbon.super/android_sense/+/data_NODE:win50/172.21.0.1/RK=carbon.super/android_sense/+/data/D=false/EX=false
[2019-04-25 16:14:15,318] [IOT-Broker]  WARN {org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent} -  Recovering node. Adding binding [Binding]E=mqtt.topic/Q=MQTT_Topic_carbon.super/virtual_firealarm/+/temperature_NODE:win50/172.21.0.1/RK=carbon.super/virtual_firealarm/+/temperature/D=false/EX=false
[Broker] BRK-1002 : Starting : Listening on TCP/SSL port 8675
[2019-04-25 16:14:15,321] [IOT-Broker]  INFO {org.wso2.andes.kernel.AndesContextInformationManager} -  Binding Sync [create]: [Binding]E=mqtt.topic/Q=MQTT_Topic_carbon.super/virtual_firealarm/+/temperature_NODE:win50/172.21.0.1/RK=carbon.super/virtual_firealarm/+/temperature/D=false/EX=false
[2019-04-25 16:14:15,327] [IOT-Broker]  WARN {org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent} -  Recovering node. Adding binding [Binding]E=mqtt.topic/Q=MQTT_Topic_carbon.super/raspberrypi/+/temperature_NODE:win50/172.21.0.1/RK=carbon.super/raspberrypi/+/temperature/D=false/EX=false
[2019-04-25 16:14:15,325] [IOT-Broker]  INFO {qpid.message.broker.listening} -  [Broker] BRK-1002 : Starting : Listening on TCP/SSL port 8675
[2019-04-25 16:14:15,330] [IOT-Broker]  INFO {org.wso2.andes.kernel.AndesContextInformationManager} -  Binding Sync [create]: [Binding]E=mqtt.topic/Q=MQTT_Topic_carbon.super/raspberrypi/+/temperature_NODE:win50/172.21.0.1/RK=carbon.super/raspberrypi/+/temperature/D=false/EX=false
[Broker] BRK-1004 : Qpid Broker Ready
[2019-04-25 16:14:15,338] [IOT-Broker]  WARN {org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent} -  Recovering node. Adding binding [Binding]E=amq.dlc/Q=deadletterchannel/RK=deadletterchannel/D=true/EX=false
[2019-04-25 16:14:15,347] [IOT-Broker]  INFO {org.wso2.andes.kernel.AndesContextInformationManager} -  Binding Sync [create]: [Binding]E=amq.dlc/Q=deadletterchannel/RK=deadletterchannel/D=true/EX=false
[2019-04-25 16:14:15,353] [IOT-Broker]  INFO {org.wso2.andes.kernel.MessagingEngine} -  Starting SlotDelivery Workers.
[2019-04-25 16:14:15,354] [IOT-Broker]  INFO {org.wso2.andes.task.TaskExecutorService} -  Starting task manager. Task count 0
[2019-04-25 16:14:15,364] [IOT-Broker]  INFO {org.wso2.andes.kernel.MessagingEngine} -  Start Disruptor writing messages to store.
[2019-04-25 16:14:15,394] [IOT-Broker] ERROR {org.dna.mqtt.wso2.MqttLogExceptionHandler} -  ValueEvent exception occurred on disruptor.
org.fusesource.hawtdb.api.IOPagingException: File's magic does not match expected value
        at org.fusesource.hawtdb.api.PageFileFactory.open(PageFileFactory.java:98)
        at org.dna.mqtt.moquette.messaging.spi.impl.HawtDBStorageService.<init>(HawtDBStorageService.java:83)
        at org.dna.mqtt.moquette.messaging.spi.impl.SimpleMessaging.processInit(SimpleMessaging.java:220)
        at org.dna.mqtt.moquette.messaging.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:212)
        at org.dna.mqtt.moquette.messaging.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:47)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2019-04-25 16:14:15,698] [IOT-Broker]  INFO {org.dna.mqtt.moquette.server.netty.NettyAcceptor} -  Server binded host: 0.0.0.0, port: 1886
[2019-04-25 16:14:15,718] [IOT-Broker]  INFO {org.dna.mqtt.moquette.server.netty.NettyAcceptor} -  Starting SSL on port 8886
[2019-04-25 16:14:15,720] [IOT-Broker]  INFO {org.dna.mqtt.moquette.server.netty.NettyAcceptor} -  Server binded host: 0.0.0.0, port: 8886
[2019-04-25 16:14:15,729] [IOT-Broker]  INFO {org.wso2.carbon.andes.internal.QpidServiceComponent} -  AMQP Host Address : 0.0.0.0 Port : 5675
[2019-04-25 16:14:15,732] [IOT-Broker]  INFO {org.wso2.carbon.andes.internal.QpidServiceComponent} -  Successfully connected to AMQP server on port 5675
[2019-04-25 16:14:15,748] [IOT-Broker]  INFO {org.wso2.carbon.andes.internal.QpidServiceComponent} -  MQTT Host Address : 0.0.0.0 Port : 1886
[2019-04-25 16:14:15,749] [IOT-Broker]  INFO {org.wso2.carbon.andes.internal.QpidServiceComponent} -  Successfully connected to MQTT server on port 1886
[2019-04-25 16:14:15,761] [IOT-Broker]  INFO {org.wso2.carbon.andes.internal.QpidServiceComponent} -  WSO2 Message Broker is started.
[2019-04-25 16:14:15,821] [IOT-Broker]  WARN {org.dna.mqtt.moquette.messaging.spi.impl.ProtocolProcessor} -  Andes does not support last will operation
[2019-04-25 16:14:15,825] [IOT-Broker] ERROR {org.dna.mqtt.wso2.MqttLogExceptionHandler} -  ValueEvent exception occurred on disruptor.
java.lang.NullPointerException
        at org.dna.mqtt.moquette.messaging.spi.impl.ProtocolProcessor.processConnect(ProtocolProcessor.java:256)
        at org.dna.mqtt.moquette.messaging.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:160)
        at org.dna.mqtt.moquette.messaging.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:47)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2019-04-25 16:14:15,889] [IOT-Broker]  INFO {org.wso2.carbon.core.deployment.DeploymentInterceptor} -  Deploying Axis2 service: echo {super-tenant}
[2019-04-25 16:14:15,892] [IOT-Broker]  INFO {org.apache.axis2.deployment.DeploymentEngine} -  Deploying Web service: Echo.aar - file:/D:/鎼滅嫍楂榽1/WSO2IO~1.0/wso2/broker/bin/../repository/deployment/server/axis2services/Echo.aar
[2019-04-25 16:14:15,917] [IOT-Broker]  INFO {org.wso2.carbon.core.deployment.DeploymentInterceptor} -  Deploying Axis2 service: Version {super-tenant}
[2019-04-25 16:14:15,919] [IOT-Broker]  INFO {org.apache.axis2.deployment.DeploymentEngine} -  Deploying Web service: Version.aar - file:/D:/鎼滅嫍楂榽1/WSO2IO~1.0/wso2/broker/bin/../repository/deployment/server/axis2services/Version.aar
[2019-04-25 16:14:15,935] [IOT-Broker]  INFO {org.wso2.carbon.core.transports.http.HttpTransportListener} -  HTTP port        : 9766
[2019-04-25 16:14:15,936] [IOT-Broker]  INFO {org.wso2.carbon.core.transports.http.HttpsTransportListener} -  HTTPS port       : 9446
[2019-04-25 16:14:16,096] [IOT-Broker]  INFO {org.wso2.carbon.core.init.JMXServerManager} -  JMX Service URL  : service:jmx:rmi://localhost:11114/jndi/rmi://localhost:10002/jmxrmi
[2019-04-25 16:14:16,098] [IOT-Broker]  INFO {org.wso2.carbon.core.internal.StartupFinalizerServiceComponent} -  Server           :  WSO2 Message Broker-3.3.0
[2019-04-25 16:14:16,103] [IOT-Broker]  INFO {org.wso2.carbon.core.internal.StartupFinalizerServiceComponent} -  WSO2 Carbon started in 92 sec
[2019-04-25 16:14:16,380] [IOT-Broker]  INFO {org.wso2.carbon.ui.internal.CarbonUIServiceComponent} -  Mgt Console URL  : https://192.168.32.83:9446/carbon/
[2019-04-25 16:15:45,821] [IOT-Broker] ERROR {org.dna.mqtt.wso2.MqttLogExceptionHandler} -  ValueEvent exception occurred on disruptor.
java.lang.NullPointerException
        at org.dna.mqtt.moquette.messaging.spi.impl.ProtocolProcessor.proccessConnectionLost(ProtocolProcessor.java:761)
        at org.dna.mqtt.moquette.messaging.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:215)
        at org.dna.mqtt.moquette.messaging.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:47)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
````
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
IoT-server 3.3.0

**OS, DB, other environment details and versions:**    
Windows10

**Steps to reproduce:**
start broker will see this error

**Related Issues:**

if ignoring this error and start iot-server and analytics service, then download the fire alarm virtual device, and run it. The device will not be able to publish data to the broker, device connection status will be 'not-registered' and with this error logs:

````
16:18:05 [WARN] FireAlarmMQTTCommunicator - AGENT_LOG:: Connection to MQTT Broker at: tcp://192.168.32.83:1886 failed.
 Will retry in 5000 milli-seconds.
16:18:30 [WARN] FireAlarmMQTTCommunicator - AGENT_LOG:: Connection to MQTT Broker at: tcp://192.168.32.83:1886 failed.
 Will retry in 5000 milli-seconds.
16:18:55 [WARN] FireAlarmMQTTCommunicator - AGENT_LOG:: Connection to MQTT Broker at: tcp://192.168.32.83:1886 failed.
 Will retry in 5000 milli-seconds.
16:19:20 [WARN] FireAlarmMQTTCommunicator - AGENT_LOG:: Connection to MQTT Broker at: tcp://192.168.32.83:1886 failed.
 Will retry in 5000 milli-seconds.
16:19:45 [WARN] FireAlarmMQTTCommunicator - AGENT_LOG:: Connection to MQTT Broker at: tcp://192.168.32.83:1886 failed.
 Will retry in 5000 milli-seconds.
16:20:10 [WARN] FireAlarmMQTTCommunicator - AGENT_LOG:: Connection to MQTT Broker at: tcp://192.168.32.83:1886 failed.
 Will retry in 5000 milli-seconds.
````

Could you give some hints how to solve this? Thanks in advance.

**Comment by wiwengweng** [comment]
config files are not modified at all as original as they are

**Comment by ruhollahShafiee** [comment]
I have this problem too.
