### ISSUE TITLE
V3.2 - Remote Connection not working when changing to SQL Database

### ISSUE THREAD

**Issue by Busbar2297** [wso2/product-iots#1921]
**Description:**
When changing DB to SQL database, remote connection doesn't work.
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
Windows Server 2012 R2, IOTs v3.2
**Steps to reproduce:**
Change DB config to SQL, start services, start connection through remote tools, you will get error:

ru.SourceHandler} I/O error: An established connection was aborted by the softw
re in your host machine
ava.io.IOException: An established connection was aborted by the software in yo
r host machine
       at sun.nio.ch.SocketDispatcher.read0(Native Method)
       at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
       at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
       at sun.nio.ch.IOUtil.read(IOUtil.java:197)
       at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
       at org.apache.http.nio.reactor.ssl.SSLIOSession.receiveEncryptedData(SSL
OSession.java:371)
       at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSes
ion.java:406)
       at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(Abstra
tIODispatch.java:119)
       at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor
java:159)
       at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(Abstr
ctIOReactor.java:338)
       at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(Abst
actIOReactor.java:316)
       at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIO
eactor.java:277)
       at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.
ava:105)
       at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.
un(AbstractMultiworkerIOReactor.java:586)
       at java.lang.Thread.run(Thread.java:748)

**Related Issues:**

**Comment by totolook** [comment]
I have the same bug in apim manager 3.2.0; that error appears every 1 second.
