### ISSUE TITLE
  start-all.sh  and  stop-all.sh script can't use!

### ISSUE THREAD

**Issue by yujie123jw** [wso2/product-iots#352]
start-all.sh  and  stop-all.sh script can't use!
runing   **start-all.sh** 
_[2017-04-06 16:44:37,095] [IoT-Core]  INFO {org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer} -  Deployed webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/authenticationendpoint].File[/home/wso2/wso2iot-3.1.0-M3.20170406/repository/deployment/server/webapps/authenticationendpoint.war]
[2017-04-06 16:44:37,380] [IoT-Analytics] ERROR {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  Failed to create a http connection.
org.apache.http.conn.HttpHostConnectException: Connect to localhost:9443 [localhost/127.0.0.1] failed: 拒绝连接 (Connection refused)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:138)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener.startListener(MQTTAdapterListener.java:162)
        at org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener.run(MQTTAdapterListener.java:256)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: 拒绝连接 (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:250)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
        ... 13 more
[2017-04-06 16:44:37,441] [IoT-Analytics] ERROR {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  MQTT Exception occurred when starting listener
错误的用户名或密码 (4)
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:28)
        at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:885)
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:118)
        at java.lang.Thread.run(Thread.java:745)
[2017-04-06 16:44:38,022] [IoT-Core]  INFO {org.springframework.web.context.ContextLoader} -  Root WebApplicationContext: initialization started
[2017-04-06 16:44:38,096] [IoT-Core]  INFO {org.springframework.web.context.support.XmlWebApplicationContext} -  Refreshing Root WebApplicationContext: startup date [Thu Apr 06 16:44:38 CST 2017]; root of context hierarchy
[2017-04-06 16:44:38,134] [IoT-Core]  INFO {org.springframework.beans.factory.xml.XmlBeanDefinitionReader} -  Loading XML bean definitions from ServletContext resource [/WEB-INF/beans.xml]
[2017-04-06 16:44:38,157] [IoT-Core]  INFO {org.springframework.beans.factory.xml.XmlBeanDefinitionReader} -  Loading XML bean definitions from class path resource [META-INF/cxf/cxf.xml]
[2017-04-06 16:44:38,363] [IoT-Core]  INFO {org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor} -  JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
[2017-04-06 16:44:38,466] [IoT-Core]  INFO {org.hibernate.validator.internal.util.Version} -  HV000001: Hibernate Validator 5.0.2.Final
[2017-04-06 16:44:38,724] [IoT-Core]  INFO {org.apache.cxf.endpoint.ServerImpl} -  Setting the server's publish address to be /register
[2017-04-06 16:44:38,746] [IoT-Analytics] ERROR {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  Failed to create a http connection.
org.apache.http.conn.HttpHostConnectException: Connect to localhost:9443 [localhost/127.0.0.1] failed: 拒绝连接 (Connection refused)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:138)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener.startListener(MQTTAdapterListener.java:162)
        at org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener.run(MQTTAdapterListener.java:256)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: 拒绝连接 (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:250)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
        ... 13 more
[2017-04-06 16:44:38,793] [IoT-Core]  INFO {org.springframework.web.context.ContextLoader} -  Root WebApplicationContext: initialization completed in 771 ms
[2017-04-06 16:44:38,801] [IoT-Core]  INFO {org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer} -  Deployed webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/client-registration/v0.11].File[/home/wso2/wso2iot-3.1.0-M3.20170406/repository/deployment/server/webapps/client-registration#v0.11.war]
[2017-04-06 16:44:38,803] [IoT-Analytics] ERROR {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  MQTT Exception occurred when starting listener_
runing   **stop-all.sh**
_cat: /home/wso2/wso2iot-3.1.0-SNAPSHOT/wso2/analytics/wso2carbon.pid: 没有那个文件或目录
kill: 用法:kill [-s 信号声明 | -n 信号编号 | -信号声明] 进程号 | 任务声明 ... 或 kill -l [信号声明]
cat: /home/wso2/wso2iot-3.1.0-SNAPSHOT/wso2carbon.pid: 没有那个文件或目录
kill: 用法:kill [-s 信号声明 | -n 信号编号 | -信号声明] 进程号 | 任务声明 ... 或 kill -l [信号声明]
cat: /home/wso2/wso2iot-3.1.0-SNAPSHOT/wso2/broker/wso2carbon.pid: 没有那个文件或目录
kill: 用法:kill [-s 信号声明 | -n 信号编号 | -信号声明] 进程号 | 任务声明 ... 或 kill -l [信号声明]
[wso2@dev-220 bin]$ ./stop-all.sh
cat: /home/wso2/wso2iot-3.1.0-SNAPSHOT/wso2/analytics/wso2carbon.pid: 没有那个文件或目录
kill: 用法:kill [-s 信号声明 | -n 信号编号 | -信号声明] 进程号 | 任务声明 ... 或 kill -l [信号声明]
cat: /home/wso2/wso2iot-3.1.0-SNAPSHOT/wso2carbon.pid: 没有那个文件或目录
kill: 用法:kill [-s 信号声明 | -n 信号编号 | -信号声明] 进程号 | 任务声明 ... 或 kill -l [信号声明]
cat: /home/wso2/wso2iot-3.1.0-SNAPSHOT/wso2/broker/wso2carbon.pid: 没有那个文件或目录
kill: 用法:kill [-s 信号声明 | -n 信号编号 | -信号声明] 进程号 | 任务声明 ... 或 kill -l [信号声明]_

but i sort  run  broker.sh , iot-server.sh ,analytics.sh  is SUCESSFUL !
**As  follow logs**
_iot.devices.wordcount:1.0.0
[2017-04-06 16:53:25,386] [IoT-Analytics]  INFO {org.wso2.carbon.analytics.eventsink.AnalyticsEventStoreDeployer} -  Deployed successfully analytics event store: org_wso2_iot_devices_wordcount.xml
[2017-04-06 16:53:34,369] [IoT-Analytics]  INFO {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  MQTT Connection successful
[2017-04-06 16:53:34,417] [IoT-Analytics]  INFO {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  MQTT Connection successful
[2017-04-06 16:53:34,479] [IoT-Analytics]  INFO {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  MQTT Connection successful
[2017-04-06 16:53:34,505] [IoT-Analytics]  INFO {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  MQTT Connection successful
[2017-04-06 16:53:47,518] [IoT-Analytics]  INFO {org.wso2.carbon.event.processor.manager.core.internal.CarbonEventManagementService} -  Starting polling event receivers_

WHY?

**Comment by sinthuja** [comment]
We have removed the start-all.sh and stop-all.sh from the server distribution from IoT server 3.1.0 onwards. Please do start the servers separately for individual profiles by using iot-server.sh, analytics.sh, and broker.sh.
