### ISSUE TITLE
Error when loading Device Management page

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-iots#393]
> 500 Cannot call method "indexOf" of undefined

when loading /devicemgt/devices

![screenshot from 2017-04-28 21-06-58](https://cloud.githubusercontent.com/assets/11583571/25536570/f98177fe-2c58-11e7-9aa8-70c722f4468c.png)

> [2017-04-28 21:04:41,231] [IoT-Core] ERROR - {handlebars-module} An exception thrown when executing the script '/app/pages/cdmf.page.devices/devices.js'.
[2017-04-28 21:04:41,235] [IoT-Core] ERROR - {dynamic-files-renderer} Cannot call method "indexOf" of undefined
org.mozilla.javascript.EcmaError: TypeError: Cannot call method "indexOf" of undefined (/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js#2236(Function)#2)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3687)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3665)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3693)
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3712)
	at org.mozilla.javascript.ScriptRuntime.undefCallError(ScriptRuntime.java:3731)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2258)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2251)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c0._c_anonymous_11(/devicemgt/app/modules/business-controllers/user.js:202)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c0.call(/devicemgt/app/modules/business-controllers/user.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
	at org.jaggeryjs.rhino.devicemgt.app.pages.cdmf.page.devices.c1._c_onRequest_1(/devicemgt/app/pages/cdmf.page.devices/devices.js:83)
	at org.jaggeryjs.rhino.devicemgt.app.pages.cdmf.page.devices.c1.call(/devicemgt/app/pages/cdmf.page.devices/devices.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0._c_executeScript_8(/devicemgt/lib/modules/handlebars/handlebars.js:239)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0.call(/devicemgt/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0._c_pageHelper_10(/devicemgt/lib/modules/handlebars/handlebars.js:295)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0.call(/devicemgt/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1473)
	at script.anonymous(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js#2236(Function):2)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c2._c_anonymous_44(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js:558)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c2.call(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c2._c_anonymous_142(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js:2029)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c2.call(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0._c_anonymous_16(/devicemgt/lib/modules/handlebars/handlebars.js:706)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0.call(/devicemgt/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.c6._c_anonymous_4(/devicemgt/lib/dynamic-files-renderer.js:97)
	at org.jaggeryjs.rhino.devicemgt.lib.c6.call(/devicemgt/lib/dynamic-files-renderer.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.c6._c_anonymous_3(/devicemgt/lib/dynamic-files-renderer.js:80)
	at org.jaggeryjs.rhino.devicemgt.lib.c6.call(/devicemgt/lib/dynamic-files-renderer.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.c5._c_anonymous_5(/devicemgt/lib/pages-router.js:181)
	at org.jaggeryjs.rhino.devicemgt.lib.c5.call(/devicemgt/lib/pages-router.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.devicemgt.lib.c3._c_script_0(/devicemgt/lib/pages.jag:23)
	at org.jaggeryjs.rhino.devicemgt.lib.c3.call(/devicemgt/lib/pages.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.devicemgt.lib.c3.call(/devicemgt/lib/pages.jag)
	at org.jaggeryjs.rhino.devicemgt.lib.c3.exec(/devicemgt/lib/pages.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:45)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by amalhub** [comment]
I encountered the same thing. But it happened to me when I try to access the page before all the servers fully start. Once this happens, doing a restart and waiting till all servers start solved the issue in my environment.

**Comment by amalhub** [comment]
Reproducible in M5 pack.

**Comment by amalhub** [comment]
Reproducible in M5 pack when there are no devices registered. 
![image](https://cloud.githubusercontent.com/assets/7391925/25612497/95afd660-2f48-11e7-88a6-2f2b863aed31.png)
https://localhost:9443/devicemgt/devices

This need to be fixed and display the page as "no devices registered yet".

**Comment by amalhub** [comment]
Fixed with https://github.com/wso2/carbon-device-mgt/commit/b54bf3000f0baa81f444a51f0b39ae2b7e3bd616
