### ISSUE TITLE
mobile-qsg.sh fails to create the mobile app in publisher

### ISSUE THREAD

**Issue by jsonds** [wso2/product-iots#415]
Execute the mobile-qsg.sh the below exception is thrown in IoT backend. The app is not available in the publisher.

**mobile-qsg.sh log**
```
Starting wso2iots-3.0.0 QSG setup ...
Creating users 
Creating iotMobileUser role
Adding sample policies 
Upload the android application 
Create the android application 
Unable to create the android mobile application. Terminating the IoTS QSG now.
wso2iots-3.0.0 QSG setup completed.
```

**IoT log**
```
[2017-05-08 12:03:57,267] [IoT-Core] ERROR - {org.wso2.carbon.appmgt.rest.api.publisher.utils.validation.AppDTOValidator} Mandatory field  'iconFile' is not provided.
[2017-05-08 12:03:57,273] [IoT-Core]  WARN - {org.apache.cxf.jaxrs.impl.WebApplicationExceptionMapper} org.wso2.carbon.appmgt.rest.api.util.exception.BadRequestException: Mandatory field  'iconFile' is not provided.
	at org.wso2.carbon.appmgt.rest.api.util.utils.RestApiUtil.buildBadRequestException(RestApiUtil.java:184)
	at org.wso2.carbon.appmgt.rest.api.util.utils.RestApiUtil.handleBadRequest(RestApiUtil.java:132)
	at org.wso2.carbon.appmgt.rest.api.publisher.utils.validation.AppDTOValidator.validateMandatoryField(AppDTOValidator.java:123)
	at org.wso2.carbon.appmgt.rest.api.publisher.utils.validation.AppDTOValidator.validateMobileApp(AppDTOValidator.java:97)
	at org.wso2.carbon.appmgt.rest.api.publisher.utils.validation.AppDTOValidator.validateAppDTO(AppDTOValidator.java:45)
	at org.wso2.carbon.appmgt.rest.api.publisher.impl.AppsApiServiceImpl.appsAppTypePost(AppsApiServiceImpl.java:429)
	at org.wso2.carbon.appmgt.rest.api.publisher.AppsApi.appsAppTypePost(AppsApi.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:212)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:45)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jsonds** [comment]
Labels - Bug, 3.1.0-M6, Blocker

**Comment by Megala21** [comment]
This issue is fixed with the latest pack with the commits https://github.com/wso2/carbon-appmgt/commit/4798f751c75445195f3b8636f6b97a1e137397e7#diff-c4c42c59f7c73d93c91e9b3d0895eec7 and https://github.com/wso2/product-iots/commit/834ad4f7727ed6aa236bda31eb9f6b95659a3a32#diff-ac3620b6f6e4002179fe36244c914afa 

Tested in latest pack and I could see the app in the publisher. Hence closing this issue.
