### ISSUE TITLE
NPE at startup after installing iOS features in M5

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-iots#422]
The product worked fine on it's own but an NPE occurred at startup just after the iOS features were installed in the M5 pack.

[2017-05-08 13:20:19,130] [IoT-Core] ERROR - {org.wso2.carbon.identity.oauth2.grant.jwt.JWTBearerGrantHandler} Signature or Message Authentication invalid.
Exception in thread "Thread-31" java.lang.NullPointerException
	at org.wso2.carbon.apimgt.integration.client.OAuthRequestInterceptor.apply(OAuthRequestInterceptor.java:104)
	at feign.SynchronousMethodHandler.targetRequest(SynchronousMethodHandler.java:158)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:88)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy40.apisGet(Unknown Source)
	at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherServiceImpl.publishAPI(APIPublisherServiceImpl.java:53)
	at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler.publishAPIs(APIPublisherStartupHandler.java:97)
	at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler.access$500(APIPublisherStartupHandler.java:30)
	at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler$1.run(APIPublisherStartupHandler.java:69)
	at java.lang.Thread.run(Thread.java:745)

**Comment by milanperera** [comment]
This happens due to misconfiguration of certificate at the default identity provider.
So when its running the ios-configurator, it will generate a certificate for the JWT and stores in the default keystore. That generated certificate should be added to the <IOTS-HOME>/conf/identity/identity-providers/iot_default.xml under <Certificate> element.
The latest ios-configurator script is changed to fix this issue.

**Comment by milanperera** [comment]
This issue is fixed in https://github.com/wso2/carbon-devicemgt-proprietary-plugins/pull/105
