### ISSUE TITLE
NPE when trying to register the iOS device - M7

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-iots#484]
Trying to register the iPhone 5S (iOS 10.1.1) and getting the following exception at the step of Profile Installation. 
![profile_installation](https://cloud.githubusercontent.com/assets/6646840/26344972/0c7a0eba-3fbf-11e7-9ee7-a0fbceda19c4.jpg)

[2017-05-23 06:54:12,497] [IoT-Core] ERROR - {handlebars-module} An exception thrown when executing the script '/app/units/mdm.unit.enrollments.license-box/license-box.js'.
[2017-05-23 06:54:12,500] [IoT-Core] ERROR - {dynamic-files-renderer} java.lang.NullPointerException: null
org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (/ios-web-agent/lib/modules/handlebars/handlebars-v2.0.0.js#2236(Function)#2(Function)#2)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.ios_web_agent.app.modules.oauth.c0._c_anonymous_2(/ios-web-agent/app/modules/oauth/token-protected-service-invokers.js:48)
	at org.jaggeryjs.rhino.ios_web_agent.app.modules.oauth.c0.call(/ios-web-agent/app/modules/oauth/token-protected-service-invokers.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
	at org.jaggeryjs.rhino.ios_web_agent.app.modules.oauth.c0._c_anonymous_3(/ios-web-agent/app/modules/oauth/token-protected-service-invokers.js:78)
	at org.jaggeryjs.rhino.ios_web_agent.app.modules.oauth.c0.call(/ios-web-agent/app/modules/oauth/token-protected-service-invokers.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.ios_web_agent.app.modules.oauth.c0._c_anonymous_5(/ios-web-agent/app/modules/oauth/token-protected-service-invokers.js:117)
	at org.jaggeryjs.rhino.ios_web_agent.app.modules.oauth.c0.call(/ios-web-agent/app/modules/oauth/token-protected-service-invokers.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.ios_web_agent.app.modules.oauth.c0._c_anonymous_6(/ios-web-agent/app/modules/oauth/token-protected-service-invokers.js:127)
	at org.jaggeryjs.rhino.ios_web_agent.app.modules.oauth.c0.call(/ios-web-agent/app/modules/oauth/token-protected-service-invokers.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.ios_web_agent.app.modules.business_controllers.c1._c_anonymous_12(/ios-web-agent/app/modules/business-controllers/device.js:318)
	at org.jaggeryjs.rhino.ios_web_agent.app.modules.business_controllers.c1.call(/ios-web-agent/app/modules/business-controllers/device.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.ios_web_agent.app.units.mdm.unit.enrollments.license_box.c1._c_onRequest_1(/ios-web-agent/app/units/mdm.unit.enrollments.license-box/license-box.js:27)
	at org.jaggeryjs.rhino.ios_web_agent.app.units.mdm.unit.enrollments.license_box.c1.call(/ios-web-agent/app/units/mdm.unit.enrollments.license-box/license-box.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c0._c_executeScript_8(/ios-web-agent/lib/modules/handlebars/handlebars.js:239)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c0.call(/ios-web-agent/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c0._c_unitHelper_11(/ios-web-agent/lib/modules/handlebars/handlebars.js:414)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c0.call(/ios-web-agent/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1473)
	at script.anonymous(/ios-web-agent/lib/modules/handlebars/handlebars-v2.0.0.js#2236(Function)#2(Function):2)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c2._c_anonymous_48(/ios-web-agent/lib/modules/handlebars/handlebars-v2.0.0.js:589)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c2.call(/ios-web-agent/lib/modules/handlebars/handlebars-v2.0.0.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c0._c_zoneHelper_12(/ios-web-agent/lib/modules/handlebars/handlebars.js:517)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c0.call(/ios-web-agent/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1473)
	at script.anonymous(/ios-web-agent/lib/modules/handlebars/handlebars-v2.0.0.js#2236(Function)#2(Function):11)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c2._c_anonymous_44(/ios-web-agent/lib/modules/handlebars/handlebars-v2.0.0.js:558)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c2.call(/ios-web-agent/lib/modules/handlebars/handlebars-v2.0.0.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c2._c_anonymous_142(/ios-web-agent/lib/modules/handlebars/handlebars-v2.0.0.js:2029)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c2.call(/ios-web-agent/lib/modules/handlebars/handlebars-v2.0.0.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c0._c_pageHelper_10(/ios-web-agent/lib/modules/handlebars/handlebars.js:316)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c0.call(/ios-web-agent/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1473)
	at script.anonymous(/ios-web-agent/lib/modules/handlebars/handlebars-v2.0.0.js#2236(Function):2)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c2._c_anonymous_44(/ios-web-agent/lib/modules/handlebars/handlebars-v2.0.0.js:558)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c2.call(/ios-web-agent/lib/modules/handlebars/handlebars-v2.0.0.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c2._c_anonymous_142(/ios-web-agent/lib/modules/handlebars/handlebars-v2.0.0.js:2029)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c2.call(/ios-web-agent/lib/modules/handlebars/handlebars-v2.0.0.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c0._c_anonymous_16(/ios-web-agent/lib/modules/handlebars/handlebars.js:706)
	at org.jaggeryjs.rhino.ios_web_agent.lib.modules.handlebars.c0.call(/ios-web-agent/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.ios_web_agent.lib.c6._c_anonymous_4(/ios-web-agent/lib/dynamic-files-renderer.js:97)
	at org.jaggeryjs.rhino.ios_web_agent.lib.c6.call(/ios-web-agent/lib/dynamic-files-renderer.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.ios_web_agent.lib.c6._c_anonymous_3(/ios-web-agent/lib/dynamic-files-renderer.js:80)
	at org.jaggeryjs.rhino.ios_web_agent.lib.c6.call(/ios-web-agent/lib/dynamic-files-renderer.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.ios_web_agent.lib.c2._c_anonymous_5(/ios-web-agent/lib/pages-router.js:181)
	at org.jaggeryjs.rhino.ios_web_agent.lib.c2.call(/ios-web-agent/lib/pages-router.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.ios_web_agent.lib.c0._c_script_0(/ios-web-agent/lib/pages.jag:23)
	at org.jaggeryjs.rhino.ios_web_agent.lib.c0.call(/ios-web-agent/lib/pages.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.ios_web_agent.lib.c0.call(/ios-web-agent/lib/pages.jag)
	at org.jaggeryjs.rhino.ios_web_agent.lib.c0.exec(/ios-web-agent/lib/pages.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:615)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:45)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.jaggeryjs.scriptengine.util.HostObjectUtil.invalidArgsError(HostObjectUtil.java:41)
	at org.jaggeryjs.scriptengine.engine.RhinoTopLevel.parse(RhinoTopLevel.java:48)
	at sun.reflect.GeneratedMethodAccessor389.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 141 more

**Comment by milanperera** [comment]
This is being tested in the 3.1.0-alpha pack and it worked without any issues.
Note: From iOS 10.1 onwards, self signed certificates will not be accepted by the OS, hence it needs to configure in the default settings app as suggested in [1].

[1] https://wso2.org/jira/browse/DOCUMENTATION-4527
