### ISSUE TITLE
Intermittently, cannot login to the device management app page: gives a http 500 error

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-iots#486]
Error in the device mgt page is: HTTP 500

Backend error is: 

[2017-05-23 11:47:19,966] [IoT-Core]  WARN - {org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler} API authentication failure due to Resource forbidden 
[2017-05-23 11:47:19,989] [IoT-Core] ERROR - {handlebars-module} An exception thrown when executing the script '/app/pages/cdmf.page.dashboard/dashboard.js'.
[2017-05-23 11:47:19,989] [IoT-Core] ERROR - {dynamic-files-renderer} Unexpected token: <
org.mozilla.javascript.EcmaError: SyntaxError: Unexpected token: < (/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js#2236(Function)#2)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3687)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3665)
	at org.mozilla.javascript.NativeJSON.parse(NativeJSON.java:112)
	at org.mozilla.javascript.NativeJSON.parse(NativeJSON.java:119)
	at org.jaggeryjs.scriptengine.util.HostObjectUtil.parseJSON(HostObjectUtil.java:70)
	at org.jaggeryjs.scriptengine.engine.RhinoTopLevel.parse(RhinoTopLevel.java:51)
	at sun.reflect.GeneratedMethodAccessor276.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c2._c_anonymous_3(/devicemgt/app/modules/business-controllers/group.js:51)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c2.call(/devicemgt/app/modules/business-controllers/group.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.devicemgt.app.modules.oauth.c0._c_anonymous_3(/devicemgt/app/modules/oauth/token-protected-service-invokers.js:130)
	at org.jaggeryjs.rhino.devicemgt.app.modules.oauth.c0.call(/devicemgt/app/modules/oauth/token-protected-service-invokers.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.app.modules.oauth.c0._c_anonymous_6(/devicemgt/app/modules/oauth/token-protected-service-invokers.js:167)
	at org.jaggeryjs.rhino.devicemgt.app.modules.oauth.c0.call(/devicemgt/app/modules/oauth/token-protected-service-invokers.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.app.modules.oauth.c0._c_anonymous_7(/devicemgt/app/modules/oauth/token-protected-service-invokers.js:177)
	at org.jaggeryjs.rhino.devicemgt.app.modules.oauth.c0.call(/devicemgt/app/modules/oauth/token-protected-service-invokers.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c2._c_anonymous_2(/devicemgt/app/modules/business-controllers/group.js:49)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c2.call(/devicemgt/app/modules/business-controllers/group.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
	at org.jaggeryjs.rhino.devicemgt.app.pages.cdmf.page.dashboard.c1._c_onRequest_1(/devicemgt/app/pages/cdmf.page.dashboard/dashboard.js:44)
	at org.jaggeryjs.rhino.devicemgt.app.pages.cdmf.page.dashboard.c1.call(/devicemgt/app/pages/cdmf.page.dashboard/dashboard.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0._c_executeScript_8(/devicemgt/lib/modules/handlebars/handlebars.js:239)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0.call(/devicemgt/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0._c_pageHelper_10(/devicemgt/lib/modules/handlebars/handlebars.js:295)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0.call(/devicemgt/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1473)
	at script.anonymous(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js#2236(Function):2)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c2._c_anonymous_44(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js:558)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c2.call(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c2._c_anonymous_142(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js:2029)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c2.call(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0._c_anonymous_16(/devicemgt/lib/modules/handlebars/handlebars.js:706)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0.call(/devicemgt/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.c6._c_anonymous_4(/devicemgt/lib/dynamic-files-renderer.js:97)
	at org.jaggeryjs.rhino.devicemgt.lib.c6.call(/devicemgt/lib/dynamic-files-renderer.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.c6._c_anonymous_3(/devicemgt/lib/dynamic-files-renderer.js:80)
	at org.jaggeryjs.rhino.devicemgt.lib.c6.call(/devicemgt/lib/dynamic-files-renderer.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.c5._c_anonymous_5(/devicemgt/lib/pages-router.js:181)
	at org.jaggeryjs.rhino.devicemgt.lib.c5.call(/devicemgt/lib/pages-router.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.devicemgt.lib.c3._c_script_0(/devicemgt/lib/pages.jag:23)
	at org.jaggeryjs.rhino.devicemgt.lib.c3.call(/devicemgt/lib/pages.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.devicemgt.lib.c3.call(/devicemgt/lib/pages.jag)
	at org.jaggeryjs.rhino.devicemgt.lib.c3.exec(/devicemgt/lib/pages.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:45)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
[2017-05-23 11:54:29,096] [IoT-Core]  WARN - {org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler} API authentication failure due to Resource forbidden 
[2017-05-23 11:54:29,133] [IoT-Core] ERROR - {handlebars-module} An exception thrown when executing the script '/app/pages/cdmf.page.dashboard/dashboard.js'.
[2017-05-23 11:54:29,133] [IoT-Core] ERROR - {dynamic-files-renderer} Unexpected token: <
org.mozilla.javascript.EcmaError: SyntaxError: Unexpected token: < (/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js#2236(Function)#2)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3687)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3665)
	at org.mozilla.javascript.NativeJSON.parse(NativeJSON.java:112)
	at org.mozilla.javascript.NativeJSON.parse(NativeJSON.java:119)
	at org.jaggeryjs.scriptengine.util.HostObjectUtil.parseJSON(HostObjectUtil.java:70)
	at org.jaggeryjs.scriptengine.engine.RhinoTopLevel.parse(RhinoTopLevel.java:51)
	at sun.reflect.GeneratedMethodAccessor276.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c2._c_anonymous_3(/devicemgt/app/modules/business-controllers/group.js:51)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c2.call(/devicemgt/app/modules/business-controllers/group.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.devicemgt.app.modules.oauth.c0._c_anonymous_3(/devicemgt/app/modules/oauth/token-protected-service-invokers.js:130)
	at org.jaggeryjs.rhino.devicemgt.app.modules.oauth.c0.call(/devicemgt/app/modules/oauth/token-protected-service-invokers.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.app.modules.oauth.c0._c_anonymous_6(/devicemgt/app/modules/oauth/token-protected-service-invokers.js:167)
	at org.jaggeryjs.rhino.devicemgt.app.modules.oauth.c0.call(/devicemgt/app/modules/oauth/token-protected-service-invokers.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.app.modules.oauth.c0._c_anonymous_7(/devicemgt/app/modules/oauth/token-protected-service-invokers.js:177)
	at org.jaggeryjs.rhino.devicemgt.app.modules.oauth.c0.call(/devicemgt/app/modules/oauth/token-protected-service-invokers.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c2._c_anonymous_2(/devicemgt/app/modules/business-controllers/group.js:49)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c2.call(/devicemgt/app/modules/business-controllers/group.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
	at org.jaggeryjs.rhino.devicemgt.app.pages.cdmf.page.dashboard.c1._c_onRequest_1(/devicemgt/app/pages/cdmf.page.dashboard/dashboard.js:44)
	at org.jaggeryjs.rhino.devicemgt.app.pages.cdmf.page.dashboard.c1.call(/devicemgt/app/pages/cdmf.page.dashboard/dashboard.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0._c_executeScript_8(/devicemgt/lib/modules/handlebars/handlebars.js:239)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0.call(/devicemgt/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0._c_pageHelper_10(/devicemgt/lib/modules/handlebars/handlebars.js:295)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0.call(/devicemgt/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1473)
	at script.anonymous(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js#2236(Function):2)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c2._c_anonymous_44(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js:558)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c2.call(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c2._c_anonymous_142(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js:2029)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c2.call(/devicemgt/lib/modules/handlebars/handlebars-v2.0.0.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0._c_anonymous_16(/devicemgt/lib/modules/handlebars/handlebars.js:706)
	at org.jaggeryjs.rhino.devicemgt.lib.modules.handlebars.c0.call(/devicemgt/lib/modules/handlebars/handlebars.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.c6._c_anonymous_4(/devicemgt/lib/dynamic-files-renderer.js:97)
	at org.jaggeryjs.rhino.devicemgt.lib.c6.call(/devicemgt/lib/dynamic-files-renderer.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.c6._c_anonymous_3(/devicemgt/lib/dynamic-files-renderer.js:80)
	at org.jaggeryjs.rhino.devicemgt.lib.c6.call(/devicemgt/lib/dynamic-files-renderer.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.lib.c5._c_anonymous_5(/devicemgt/lib/pages-router.js:181)
	at org.jaggeryjs.rhino.devicemgt.lib.c5.call(/devicemgt/lib/pages-router.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.devicemgt.lib.c3._c_script_0(/devicemgt/lib/pages.jag:23)
	at org.jaggeryjs.rhino.devicemgt.lib.c3.call(/devicemgt/lib/pages.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.devicemgt.lib.c3.call(/devicemgt/lib/pages.jag)
	at org.jaggeryjs.rhino.devicemgt.lib.c3.exec(/devicemgt/lib/pages.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:45)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sinthuja** [comment]
Pasindu will work on this.

**Comment by sinthuja** [comment]
This issue doesn't happen in the latest pack and 3.1.0 GA release. And hence closing this issue.
