### ISSUE TITLE
[IOTS-237] NPE thrown if invalid device id is passed to HTTP publisher

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#695]
<p>If an invalid device id is passed to the a HTTP publisher endpoint following error is thrown.</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> curl -X GET -H <span class="code-quote">"Authorization: Bearer 595bef16de7c68fbf7626759abad3c68"</span> http:<span class="code-comment">//localhost:9763/arduino/device/vb423pol61i/controls</span> </pre> </div></div> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"></pre> </div></div> <p><span class="error">[2016-06-13 16:27:56,039]</span> ERROR - AbstractFaultChainInitiatorObserver Error occurred during error handling, give up!<br/> org.apache.cxf.interceptor.Fault<br/> at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:170)<br/> at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:136)<br/> at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)<br/> at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)<br/> at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)<br/> at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94)<br/> at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)<br/> at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)<br/> at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:249)<br/> at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)<br/> at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)<br/> at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)<br/> at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)<br/> at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:289)<br/> at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:214)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)<br/> at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:265)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)<br/> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)<br/> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)<br/> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)<br/> at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)<br/> at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.processRequest(WebappAuthenticationValve.java:145)<br/> at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:67)<br/> at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)<br/> at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)<br/> at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)<br/> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)<br/> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)<br/> at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)<br/> at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1739)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1698)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)<br/> at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)<br/> at java.lang.Thread.run(Thread.java:745)<br/> Caused by: java.lang.NullPointerException<br/> at org.wso2.carbon.device.mgt.core.authorization.DeviceAccessAuthorizationServiceImpl.isDeviceOwner(DeviceAccessAuthorizationServiceImpl.java:207)<br/> at org.wso2.carbon.device.mgt.core.authorization.DeviceAccessAuthorizationServiceImpl.isAdminOrDeviceOwner(DeviceAccessAuthorizationServiceImpl.java:173)<br/> at org.wso2.carbon.device.mgt.core.authorization.DeviceAccessAuthorizationServiceImpl.isUserAuthorized(DeviceAccessAuthorizationServiceImpl.java:69)<br/> at org.wso2.carbon.device.mgt.core.authorization.DeviceAccessAuthorizationServiceImpl.isUserAuthorized(DeviceAccessAuthorizationServiceImpl.java:100)<br/> at org.wso2.carbon.device.mgt.iot.arduino.service.impl.ArduinoServiceImpl.readControls(ArduinoServiceImpl.java:104)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:497)<br/> at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:188)<br/> at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:104)<br/> ... 45 more<br/> <span class="error">[2016-06-13 16:27:56,043]</span> ERROR - StandardWrapperValve Servlet.service() for servlet <span class="error">[CXFServlet]</span> in context with path <span class="error">[/arduino]</span> threw exception<br/> java.lang.RuntimeException: org.apache.cxf.interceptor.Fault<br/> at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:116)<br/> at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:336)<br/> at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)<br/> at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:249)<br/> at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)<br/> at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)<br/> at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)<br/> at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)<br/> at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:289)<br/> at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:214)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)<br/> at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:265)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)<br/> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)<br/> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)<br/> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)<br/> at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)<br/> at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.processRequest(WebappAuthenticationValve.java:145)<br/> at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:67)<br/> at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)<br/> at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)<br/> at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)<br/> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)<br/> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)<br/> at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)<br/> at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1739)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1698)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)<br/> at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)<br/> at java.lang.Thread.run(Thread.java:745)<br/> Caused by: org.apache.cxf.interceptor.Fault<br/> at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:170)<br/> at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:136)<br/> at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)<br/> at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)<br/> at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)<br/> at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94)<br/> at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)<br/> ... 40 more<br/> Caused by: java.lang.NullPointerException<br/> at org.wso2.carbon.device.mgt.core.authorization.DeviceAccessAuthorizationServiceImpl.isDeviceOwner(DeviceAccessAuthorizationServiceImpl.java:207)<br/> at org.wso2.carbon.device.mgt.core.authorization.DeviceAccessAuthorizationServiceImpl.isAdminOrDeviceOwner(DeviceAccessAuthorizationServiceImpl.java:173)<br/> at org.wso2.carbon.device.mgt.core.authorization.DeviceAccessAuthorizationServiceImpl.isUserAuthorized(DeviceAccessAuthorizationServiceImpl.java:69)<br/> at org.wso2.carbon.device.mgt.core.authorization.DeviceAccessAuthorizationServiceImpl.isUserAuthorized(DeviceAccessAuthorizationServiceImpl.java:100)<br/> at org.wso2.carbon.device.mgt.iot.arduino.service.impl.ArduinoServiceImpl.readControls(ArduinoServiceImpl.java:104)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:497)<br/> at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:188)<br/> at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:104)<br/> ... 45 more</p> {codd}<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-237'>https://wso2.org/jira/browse/IOTS-237</a></p>

**Comment by Megala21** [comment]
This issue is not re-producible with the latest-pack. Currently it is properly handled and following exception log is printed.
```
 ERROR - {org.wso2.carbon.device.mgt.iot.arduino.service.impl.ArduinoServiceImpl} Error occurred while retriving operation
org.wso2.carbon.device.mgt.common.operation.mgt.OperationManagementException: Device not found for given device Identifier:vb423pol61i and given typearduino
	at org.wso2.carbon.device.mgt.core.operation.mgt.OperationManagerImpl.getNextPendingOperation(OperationManagerImpl.java:468)
	at org.wso2.carbon.device.mgt.core.service.DeviceManagementProviderServiceImpl.getNextPendingOperation(DeviceManagementProviderServiceImpl.java:996)
	at org.wso2.carbon.device.mgt.iot.arduino.service.impl.ArduinoServiceImpl.readControls(ArduinoServiceImpl.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:188)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:104)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:249)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:289)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:214)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:265)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.processRequest(WebappAuthenticationValve.java:138)
	at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:68)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

```
Hence closing this.
