### ISSUE TITLE
[IOTS-230] Arduino Sample Download Sketch does not work + Windows

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#700]
<p>Steps:<br/> Goto Enroll Device<br/> URL - <a href="https://localhost:9443/devicemgt/device/arduino/enroll#" class="external-link" rel="nofollow">https://localhost:9443/devicemgt/device/arduino/enroll#</a><br/> Click on download Sketch and get the following error<br/> Caused by: java.io.IOException: Unable to delete file: D:\Learning\IOT\IOTS_H~1\bin\..\repository\resources\sketches\archives\r1alpw8wb2gj\PollServer.ino</p> <p>Logs Details</p> <p>TID: <span class="error">[-1234]</span> [] <span class="error">[2016-06-10 22:29:05,917]</span> ERROR </p> {org.wso2.carbon.device.mgt.iot.arduino.service.impl.ArduinoServiceImpl} - Zip File Creation Failed {org.wso2.carbon.device.mgt.iot.arduino.service.impl.ArduinoServiceImpl} <p>org.wso2.carbon.device.mgt.common.DeviceManagementException: Zip File Creation Failed<br/> at org.wso2.carbon.device.mgt.iot.arduino.service.impl.util.ZipUtil.createZipFile(ZipUtil.java:72)<br/> at org.wso2.carbon.device.mgt.iot.arduino.service.impl.ArduinoServiceImpl.createDownloadFile(ArduinoServiceImpl.java:236)<br/> at org.wso2.carbon.device.mgt.iot.arduino.service.impl.ArduinoServiceImpl.downloadSketch(ArduinoServiceImpl.java:178)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:601)<br/> at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:188)<br/> at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:104)<br/> at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)<br/> at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)<br/> at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)<br/> at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94)<br/> at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)<br/> at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)<br/> at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:249)<br/> at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)<br/> at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)<br/> at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)<br/> at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)<br/> at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:289)<br/> at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:214)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)<br/> at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:265)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)<br/> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)<br/> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)<br/> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)<br/> at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)<br/> at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.processRequest(WebappAuthenticationValve.java:145)<br/> at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:67)<br/> at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)<br/> at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)<br/> at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)<br/> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)<br/> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)<br/> at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)<br/> at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1739)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1698)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)<br/> at java.lang.Thread.run(Thread.java:722)<br/> Caused by: java.io.IOException: Unable to delete file: D:\Learning\IOT\IOTS_H~1\bin\..\repository\resources\sketches\archives\r1alpw8wb2gj\PollServer.ino<br/> at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)<br/> at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)<br/> at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)<br/> at org.wso2.carbon.device.mgt.iot.util.Utils.getSketchArchive(Utils.java:107)<br/> at org.wso2.carbon.device.mgt.iot.arduino.service.impl.util.ZipUtil.createZipFile(ZipUtil.java:69)<br/> ... 53 more<br/> TID: <span class="error">[-1234]</span> [] <span class="error">[2016-06-10 22:29:06,082]</span> ERROR </p> {api/device-api.jag} - {} {api/device-api.jag}<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-230'>https://wso2.org/jira/browse/IOTS-230</a></p>

**Comment by codehArt** [comment]
getting this in response

<am:fault xmlns:am="http://wso2.org/apimanager">
            <am:code>404</am:code>
            <am:type>Status report</am:type>
            <am:message>Not Found</am:message>
            <am:description>The requested resource (/raspberrypi/device/download?deviceName=demo&amp;deviceType=raspberrypi&amp;sketchType=raspberrypi) is not available.</am:description>
</am:fault>
