### ISSUE TITLE
[APPM-297] Error When creating Web Apps with postgresSQL - ERROR: relation "apm_entitlement_policy_partial" does not exist

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#720]
<p>When "Add New Web Application" is clicked the following error is thrown when configured with PostgreSQL,</p> <p> ERROR: relation "apm_entitlement_policy_partial" does not exist<br/> Position: 15<br/> at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)<br/> at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)<br/> at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)<br/> at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)<br/> at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)<br/> at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)<br/> at org.wso2.carbon.appmgt.impl.dao.AppMDAO.getSharedEntitlementPolicyPartialsList(AppMDAO.java:5257)<br/> at org.wso2.carbon.appmgt.impl.APIProviderImpl.getSharedPolicyPartialsList(APIProviderImpl.java:508)<br/> at org.wso2.carbon.appmgt.impl.UserAwareAPIProvider.getSharedPolicyPartialsList(UserAwareAPIProvider.java:36)<br/> at org.wso2.carbon.appmgt.hostobjects.APIProviderHostObject.jsFunction_getSharedPolicyPartialList(APIProviderHostObject.java:813)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br/> at java.lang.reflect.Method.invoke(Method.java:597)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)<br/> at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3._c_getSharedPolicyPartialList_21(/publisher/apis/v1/entitlement_api_router.jag:132)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3._c_anonymous_8(/publisher/apis/v1/entitlement_api_router.jag:49)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)<br/> at org.jaggeryjs.rhino.publisher.modules.c4._c_anonymous_12(/publisher/modules/router-g.js:183)<br/> at org.jaggeryjs.rhino.publisher.modules.c4.call(/publisher/modules/router-g.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3._c_anonymous_1(/publisher/apis/v1/entitlement_api_router.jag:198)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)<br/> at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)<br/> at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_17(/publisher/modules/publisher.js:438)<br/> at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.mozilla.javascript.gen.<em>store</em>_server_js_5._c_anonymous_17(<span class="error">[store]</span>/server.js:271)<br/> at org.mozilla.javascript.gen.<em>store</em>_server_js_5.call(<span class="error">[store]</span>/server.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_16(/publisher/modules/publisher.js:433)<br/> at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3._c_script_0(/publisher/apis/v1/entitlement_api_router.jag:5)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)<br/> at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.exec(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:536)<br/> at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)<br/> at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749)<br/> at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:487)<br/> at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:379)<br/> at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339)<br/> at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)<br/> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)<br/> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)<br/> at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)<br/> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)<br/> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)<br/> at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:56)<br/> at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156)<br/> at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52)<br/> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)<br/> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)<br/> at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)<br/> at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1653)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)<br/> at java.lang.Thread.run(Thread.java:662)<br/> <span class="error">[2015-01-12 13:52:51,221]</span> ERROR - WebAppManager org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.appmgt.api.AppManagementException: Failed to retrieve shared entitlement policy partials. (/publisher/apis/v1/entitlement_api_router.jag#132)<br/> org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.appmgt.api.AppManagementException: Failed to retrieve shared entitlement policy partials. (/publisher/apis/v1/entitlement_api_router.jag#132)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:536)<br/> at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)<br/> at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749)<br/> at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:487)<br/> at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:379)<br/> at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339)<br/> at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)<br/> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)<br/> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)<br/> at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)<br/> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)<br/> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)<br/> at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:56)<br/> at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156)<br/> at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52)<br/> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)<br/> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)<br/> at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)<br/> at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1653)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)<br/> at java.lang.Thread.run(Thread.java:662)<br/> Caused by: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.appmgt.api.AppManagementException: Failed to retrieve shared entitlement policy partials. (/publisher/apis/v1/entitlement_api_router.jag#132)<br/> at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)<br/> at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3._c_getSharedPolicyPartialList_21(/publisher/apis/v1/entitlement_api_router.jag:132)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3._c_anonymous_8(/publisher/apis/v1/entitlement_api_router.jag:49)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)<br/> at org.jaggeryjs.rhino.publisher.modules.c4._c_anonymous_12(/publisher/modules/router-g.js:183)<br/> at org.jaggeryjs.rhino.publisher.modules.c4.call(/publisher/modules/router-g.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3._c_anonymous_1(/publisher/apis/v1/entitlement_api_router.jag:198)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)<br/> at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)<br/> at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_17(/publisher/modules/publisher.js:438)<br/> at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.mozilla.javascript.gen.<em>store</em>_server_js_5._c_anonymous_17(<span class="error">[store]</span>/server.js:271)<br/> at org.mozilla.javascript.gen.<em>store</em>_server_js_5.call(<span class="error">[store]</span>/server.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_16(/publisher/modules/publisher.js:433)<br/> at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3._c_script_0(/publisher/apis/v1/entitlement_api_router.jag:5)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)<br/> at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.exec(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> ... 35 more<br/> Caused by: org.wso2.carbon.appmgt.api.AppManagementException: Failed to retrieve shared entitlement policy partials.<br/> at org.wso2.carbon.appmgt.impl.dao.AppMDAO.handleException(AppMDAO.java:4609)<br/> at org.wso2.carbon.appmgt.impl.dao.AppMDAO.getSharedEntitlementPolicyPartialsList(AppMDAO.java:5271)<br/> at org.wso2.carbon.appmgt.impl.APIProviderImpl.getSharedPolicyPartialsList(APIProviderImpl.java:508)<br/> at org.wso2.carbon.appmgt.impl.UserAwareAPIProvider.getSharedPolicyPartialsList(UserAwareAPIProvider.java:36)<br/> at org.wso2.carbon.appmgt.hostobjects.APIProviderHostObject.jsFunction_getSharedPolicyPartialList(APIProviderHostObject.java:813)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br/> at java.lang.reflect.Method.invoke(Method.java:597)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)<br/> ... 68 more<br/> Caused by: org.postgresql.util.PSQLException: ERROR: relation "apm_entitlement_policy_partial" does not exist<br/> Position: 15<br/> at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)<br/> at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)<br/> at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)<br/> at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)<br/> at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)<br/> at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)<br/> at org.wso2.carbon.appmgt.impl.dao.AppMDAO.getSharedEntitlementPolicyPartialsList(AppMDAO.java:5257)<br/> ... 76 more</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-297'>https://wso2.org/jira/browse/APPM-297</a></p>

**Comment by madhawap** [comment]
This issue is not related to IoT server, hence closed.
