### ISSUE TITLE
[APPM-1567] Favorite apps are not loaded for some users

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#838]
<p>Can reproduce this error<span class="error">[1]</span> by following these steps.<br/> 1. Create a webapp TestWebApp1<br/> 2. Create a user (user1) and role (role1) from /carbon mgt console<br/> 3. logged in to the store as user1<br/> 4. Make the TestWebApp1 as the favourite<br/> 5. Tested from favourites and it is there<br/> 6. Edit the webapp and set the visibility only to 'store-admin' role <br/> 7. Again checked the /store by login as user1, then i can see the below error in backend logs</p> <p><span class="error">[1]</span> - ERROR - UserAwareAPIConsumer Failed to get WebApp from : /appmgt/applicationdata/provider/admin/TestWebApp1/1.1/webapp<br/> org.wso2.carbon.registry.core.secure.AuthorizationFailedException: User user1 is not authorized to read the resource /_system/governance/appmgt/applicationdata/provider/admin/TestWebApp1/1.1/webapp.<br/> at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.get(CacheBackedRegistry.java:169)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.getInternal(UserRegistry.java:616)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.access$400(UserRegistry.java:60)<br/> at org.wso2.carbon.registry.core.session.UserRegistry$5.run(UserRegistry.java:596)<br/> at org.wso2.carbon.registry.core.session.UserRegistry$5.run(UserRegistry.java:593)<br/> at java.security.AccessController.doPrivileged(Native Method)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.get(UserRegistry.java:593)<br/> at org.wso2.carbon.appmgt.impl.AbstractAPIManager.getAPI(AbstractAPIManager.java:325)<br/> at org.wso2.carbon.appmgt.hostobjects.APIStoreHostObject.getFavouriteAppsInDetail(APIStoreHostObject.java:3440)<br/> at org.wso2.carbon.appmgt.hostobjects.APIStoreHostObject.jsFunction_getAllFavouriteApps(APIStoreHostObject.java:3359)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:497)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)<br/> at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.store.modules.favourites.c1._c_anonymous_2(/store/modules/favourites/favourites.jag:42)<br/> at org.jaggeryjs.rhino.store.modules.favourites.c1.call(/store/modules/favourites/favourites.jag)<br/> at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)<br/> at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)<br/> at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.store.modules.favourites.c0._c_anonymous_2(/store/modules/favourites/module.jag:8)<br/> at org.jaggeryjs.rhino.store.modules.favourites.c0.call(/store/modules/favourites/module.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.store.controllers.c3._c_anonymous_1(/store/controllers/favouriteapps.jag:112)<br/> at org.jaggeryjs.rhino.store.controllers.c3.call(/store/controllers/favouriteapps.jag)<br/> at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)<br/> at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)<br/> at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.store.modules.c1._c_anonymous_77(/store/modules/store.js:1212)<br/> at org.jaggeryjs.rhino.store.modules.c1.call(/store/modules/store.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.jaggeryjs.rhino.&amp;lt;store&amp;gt;.scripts.c0._c_anonymous_17(&amp;lt;store&amp;gt;/scripts/server.js:286)<br/> at org.jaggeryjs.rhino.&amp;lt;store&amp;gt;.scripts.c0.call(&amp;lt;store&amp;gt;/scripts/server.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.store.modules.c1._c_anonymous_76(/store/modules/store.js:1206)<br/> at org.jaggeryjs.rhino.store.modules.c1.call(/store/modules/store.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.store.controllers.c3._c_script_0(/store/controllers/favouriteapps.jag:32)<br/> at org.jaggeryjs.rhino.store.controllers.c3.call(/store/controllers/favouriteapps.jag)<br/> at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)<br/> at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)<br/> at org.jaggeryjs.rhino.store.controllers.c3.call(/store/controllers/favouriteapps.jag)<br/> at org.jaggeryjs.rhino.store.controllers.c3.exec(/store/controllers/favouriteapps.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:587)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:507)<br/> at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)<br/> at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)<br/> at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:378)<br/> at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)<br/> at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)<br/> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)<br/> at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)<br/> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)<br/> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)<br/> at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)<br/> at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)<br/> at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)<br/> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)<br/> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)<br/> at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)<br/> at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1739)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1698)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1567'>https://wso2.org/jira/browse/APPM-1567</a></p>

**Comment by madhawap** [comment]
Web app functionalities are not related to IoT server at the moment, hence closed.
