### ISSUE TITLE
[APPM-1125] NativeWorkerPool Uncaught exception when invoking web apps

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#863]
<p>The following exception can be observed intermittently when accessing a web app URL published by TenantA , after logging in from TenantB (Subscriptions are allowed for the relevant web app for TenantB).</p> <p>Anonymous access was given to the web app initially.<br/> Then it was unpublished and re-published with access restricteid to TenantB.</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> [2015-12-07 15:34:40,512] ERROR - NativeWorkerPool Uncaught exception org.apache.axis2.engine.AxisError: ServiceContext in OperationContext does not match ! at org.apache.axis2.context.MessageContext.setOperationContext(MessageContext.java:1404) at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processResponse(MultitenantMessageReceiver.java:131) at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:83) at org.apache.synapse.transport.passthru.TargetErrorHandler$1.run(TargetErrorHandler.java:134) at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:744) </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1125'>https://wso2.org/jira/browse/APPM-1125</a></p>

**Comment by madhawap** [comment]
Web app publishing is not related to IoT server at the moment, hence closed.
