### ISSUE TITLE
[APPM-1184] Registry exception while publishing web apps

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#882]
<p>The following exception occurs intermittently while publishing web apps (Publish --&amp;gt; Published)<br/> This is frequenty reproducible with Oracle</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> [2015-12-15 16:44:24,033] INFO - CarbonAuthenticationUtil 'admin123@carbon.<span class="code-keyword">super</span> [-1234]' logged in at [2015-12-15 16:44:24,032+0530] [2015-12-15 16:44:24,081] INFO - API Destroying API: tenant1@tenant1.com--ddd:v1.0.0 [2015-12-15 16:44:27,615] INFO - assets_router:jag Emitting event : login [2015-12-15 16:44:44,148] INFO - assets_router:jag Emitting event : login [2015-12-15 16:44:55,063] INFO - assets_router:jag Emitting event : login [2015-12-15 16:44:59,501] INFO - CarbonAuthenticationUtil 'admin123@carbon.<span class="code-keyword">super</span> [-1234]' logged in at [2015-12-15 16:44:59,501+0530] [2015-12-15 16:44:59,573] INFO - API Initializing API: tenant1@tenant1.com--ddd:v1.0.0 [2015-12-15 16:45:12,091] ERROR - JaggeryTravellingPermissionLifeCycle Preprequest action must be completed before Publish [2015-12-15 16:45:12,091] ERROR - JaggeryTravellingPermissionLifeCycle org.wso2.carbon.registry.core.exceptions.RegistryException: Preprequest action must be completed before Publish [2015-12-15 16:45:12,101] ERROR - GovernanceArtifactImpl Invoking lifecycle action <span class="code-quote">"Publish"</span> failed org.wso2.carbon.registry.core.exceptions.RegistryException: Preprequest action must be completed before Publish at org.wso2.jaggery.scxml.aspects.JaggeryTravellingPermissionLifeCycle.invoke(JaggeryTravellingPermissionLifeCycle.java:510) at org.wso2.carbon.governance.registry.eventing.handlers.GovernanceEventingHandler.invokeAspect(GovernanceEventingHandler.java:243) at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.invokeAspect(HandlerManager.java:2792) at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.invokeAspect(HandlerLifecycleManager.java:531) at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.invokeAspect(EmbeddedRegistry.java:2550) at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.invokeAspect(CacheBackedRegistry.java:427) at org.wso2.carbon.registry.core.session.UserRegistry.invokeAspect(UserRegistry.java:1955) at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.invokeAction(GovernanceArtifactImpl.java:625) at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.invokeAction(GovernanceArtifactImpl.java:605) at sun.reflect.GeneratedMethodAccessor268.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126) at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) at org.mozilla.javascript.gen.artifacts_23._c_anonymous_21(artifacts:288) at org.mozilla.javascript.gen.artifacts_23.call(artifacts) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.apis.v_1.c5._c_anonymous_9(/publisher/apis/v1/lifecycle_api_router.jag:198) at org.jaggeryjs.rhino.publisher.apis.v_1.c5.call(/publisher/apis/v1/lifecycle_api_router.jag) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) at org.jaggeryjs.rhino.publisher.modules.c4._c_anonymous_12(/publisher/modules/router-g.js:183) at org.jaggeryjs.rhino.publisher.modules.c4.call(/publisher/modules/router-g.js) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.apis.v_1.c5._c_anonymous_1(/publisher/apis/v1/lifecycle_api_router.jag:513) at org.jaggeryjs.rhino.publisher.apis.v_1.c5.call(/publisher/apis/v1/lifecycle_api_router.jag) at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430) at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269) at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_17(/publisher/modules/publisher.js:438) at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js) at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23) at org.mozilla.javascript.gen._store__server_js_11._c_anonymous_17([store]/server.js:284) at org.mozilla.javascript.gen._store__server_js_11.call([store]/server.js) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_16(/publisher/modules/publisher.js:433) at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js) at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) at org.jaggeryjs.rhino.publisher.apis.v_1.c5._c_script_0(/publisher/apis/v1/lifecycle_api_router.jag:24) at org.jaggeryjs.rhino.publisher.apis.v_1.c5.call(/publisher/apis/v1/lifecycle_api_router.jag) at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) at org.jaggeryjs.rhino.publisher.apis.v_1.c5.call(/publisher/apis/v1/lifecycle_api_router.jag) at org.jaggeryjs.rhino.publisher.apis.v_1.c5.exec(/publisher/apis/v1/lifecycle_api_router.jag) at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567) at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273) at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:536) at org.jaggeryjs.jaggery.core.JaggeryServlet.doPut(JaggeryServlet.java:39) at javax.servlet.http.HttpServlet.service(HttpServlet.java:758) at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748) at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486) at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:378) at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338) at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178) at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47) at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:56) at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141) at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:744) </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1184'>https://wso2.org/jira/browse/APPM-1184</a></p>

**Comment by madhawap** [comment]
Web app publishing is not related to IoT server at the moment. Hence closed.
