### ISSUE TITLE
[APPM-1018] [PostgreSQL] Cannot publish a web app

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#895]
<p><span class="error">[2015-07-09 19:25:56,538]</span> ERROR - AppMDAO SQL Error while executing the query to save Policy Group : INSERT INTO APM_POLICY_GROUP(NAME,THROTTLING_TIER,USER_ROLES,URL_ALLOW_ANONYMOUS,DESCRIPTION) VALUES(?,?,?,?,?) : (policyGroupName:Default, throttlingTier:Unlimited, userRoles: ,isAnonymousAllowed:false, Partial Mappings:[Ljava.lang.Object;@5251defd) : ERROR: column "POLICY_GRP_ID" does not exist<br/> Position: 128<br/> org.postgresql.util.PSQLException: ERROR: column "POLICY_GRP_ID" does not exist<br/> Position: 128<br/> at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)<br/> at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)<br/> at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)<br/> at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)<br/> at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)<br/> at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:366)<br/> at org.wso2.carbon.appmgt.impl.dao.AppMDAO.savePolicyGroup(AppMDAO.java:6825)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:606)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)<br/> at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3._c_savePolicyGroup_33(/publisher/apis/v1/entitlement_api_router.jag:210)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3._c_anonymous_15(/publisher/apis/v1/entitlement_api_router.jag:88)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)<br/> at org.jaggeryjs.rhino.publisher.modules.c4._c_anonymous_12(/publisher/modules/router-g.js:183)<br/> at org.jaggeryjs.rhino.publisher.modules.c4.call(/publisher/modules/router-g.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3._c_anonymous_1(/publisher/apis/v1/entitlement_api_router.jag:302)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)<br/> at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)<br/> at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_17(/publisher/modules/publisher.js:438)<br/> at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.mozilla.javascript.gen.<em>store</em>_server_js_29._c_anonymous_17(<span class="error">[store]</span>/server.js:266)<br/> at org.mozilla.javascript.gen.<em>store</em>_server_js_29.call(<span class="error">[store]</span>/server.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_16(/publisher/modules/publisher.js:433)<br/> at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3._c_script_0(/publisher/apis/v1/entitlement_api_router.jag:5)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)<br/> at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.exec(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:536)<br/> at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)<br/> at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)<br/> at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:378)<br/> at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)<br/> at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)<br/> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)<br/> at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)<br/> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)<br/> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)<br/> at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:56)<br/> at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156)<br/> at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52)<br/> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)<br/> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)<br/> at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)<br/> at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)<br/> at java.lang.Thread.run(Thread.java:745)<br/> <span class="error">[2015-07-09 19:25:56,543]</span> ERROR - WebAppManager org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.appmgt.api.AppManagementException: SQL Error while executing the query to save Policy Group : INSERT INTO APM_POLICY_GROUP(NAME,THROTTLING_TIER,USER_ROLES,URL_ALLOW_ANONYMOUS,DESCRIPTION) VALUES(?,?,?,?,?) : (policyGroupName:Default, throttlingTier:Unlimited, userRoles: ,isAnonymousAllowed:false, Partial Mappings:[Ljava.lang.Object;@5251defd) : ERROR: column "POLICY_GRP_ID" does not exist<br/> Position: 128 (/publisher/apis/v1/entitlement_api_router.jag#210)<br/> org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.appmgt.api.AppManagementException: SQL Error while executing the query to save Policy Group : INSERT INTO APM_POLICY_GROUP(NAME,THROTTLING_TIER,USER_ROLES,URL_ALLOW_ANONYMOUS,DESCRIPTION) VALUES(?,?,?,?,?) : (policyGroupName:Default, throttlingTier:Unlimited, userRoles: ,isAnonymousAllowed:false, Partial Mappings:[Ljava.lang.Object;@5251defd) : ERROR: column "POLICY_GRP_ID" does not exist<br/> Position: 128 (/publisher/apis/v1/entitlement_api_router.jag#210)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:536)<br/> at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)<br/> at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)<br/> at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:378)<br/> at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)<br/> at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)<br/> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)<br/> at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)<br/> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)<br/> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)<br/> at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:56)<br/> at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156)<br/> at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52)<br/> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)<br/> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)<br/> at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)<br/> at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)<br/> at java.lang.Thread.run(Thread.java:745)<br/> Caused by: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.appmgt.api.AppManagementException: SQL Error while executing the query to save Policy Group : INSERT INTO APM_POLICY_GROUP(NAME,THROTTLING_TIER,USER_ROLES,URL_ALLOW_ANONYMOUS,DESCRIPTION) VALUES(?,?,?,?,?) : (policyGroupName:Default, throttlingTier:Unlimited, userRoles: ,isAnonymousAllowed:false, Partial Mappings:[Ljava.lang.Object;@5251defd) : ERROR: column "POLICY_GRP_ID" does not exist<br/> Position: 128 (/publisher/apis/v1/entitlement_api_router.jag#210)<br/> at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)<br/> at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3._c_savePolicyGroup_33(/publisher/apis/v1/entitlement_api_router.jag:210)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3._c_anonymous_15(/publisher/apis/v1/entitlement_api_router.jag:88)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)<br/> at org.jaggeryjs.rhino.publisher.modules.c4._c_anonymous_12(/publisher/modules/router-g.js:183)<br/> at org.jaggeryjs.rhino.publisher.modules.c4.call(/publisher/modules/router-g.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3._c_anonymous_1(/publisher/apis/v1/entitlement_api_router.jag:302)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)<br/> at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)<br/> at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_17(/publisher/modules/publisher.js:438)<br/> at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.mozilla.javascript.gen.<em>store</em>_server_js_29._c_anonymous_17(<span class="error">[store]</span>/server.js:266)<br/> at org.mozilla.javascript.gen.<em>store</em>_server_js_29.call(<span class="error">[store]</span>/server.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_16(/publisher/modules/publisher.js:433)<br/> at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3._c_script_0(/publisher/apis/v1/entitlement_api_router.jag:5)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)<br/> at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.call(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.jaggeryjs.rhino.publisher.apis.v_1.c3.exec(/publisher/apis/v1/entitlement_api_router.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> ... 37 more<br/> Caused by: org.wso2.carbon.appmgt.api.AppManagementException: SQL Error while executing the query to save Policy Group : INSERT INTO APM_POLICY_GROUP(NAME,THROTTLING_TIER,USER_ROLES,URL_ALLOW_ANONYMOUS,DESCRIPTION) VALUES(?,?,?,?,?) : (policyGroupName:Default, throttlingTier:Unlimited, userRoles: ,isAnonymousAllowed:false, Partial Mappings:[Ljava.lang.Object;@5251defd) : ERROR: column "POLICY_GRP_ID" does not exist<br/> Position: 128<br/> at org.wso2.carbon.appmgt.impl.dao.AppMDAO.handleException(AppMDAO.java:4790)<br/> at org.wso2.carbon.appmgt.impl.dao.AppMDAO.savePolicyGroup(AppMDAO.java:6860)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:606)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)<br/> ... 70 more</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1018'>https://wso2.org/jira/browse/APPM-1018</a></p>

**Comment by madhawap** [comment]
Web app publishing is not related to IoT server at the moment, hence closed.
