### ISSUE TITLE
Intermittent JdbcSQLException issue with default h2 database

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-iots#965]
Following issue was seen intermittently.

[2017-06-06 09:11:26,070] [IoT-Core] ERROR - {org.wso2.carbon.device.mgt.ios.services.impl.DeviceManagementAdminServiceImpl} Issue in retrieving operation management service instance
org.wso2.carbon.device.mgt.common.operation.mgt.OperationManagementException: Error occurred while adding operation
	at org.wso2.carbon.device.mgt.core.operation.mgt.OperationManagerImpl.addOperation(OperationManagerImpl.java:227)
	at org.wso2.carbon.device.mgt.core.service.DeviceManagementProviderServiceImpl.addOperation(DeviceManagementProviderServiceImpl.java:1177)
	at org.wso2.carbon.device.mgt.ios.util.IOSServiceUtils.getOperationResponse(IOSServiceUtils.java:132)
	at org.wso2.carbon.device.mgt.ios.services.impl.DeviceManagementAdminServiceImpl.getApplicationListOperation(DeviceManagementAdminServiceImpl.java:391)
	at org.wso2.carbon.device.mgt.ios.services.impl.DeviceManagementAdminServiceImpl.getDeviceInformation(DeviceManagementAdminServiceImpl.java:540)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:188)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:104)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:249)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:289)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:209)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:265)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.processRequest(WebappAuthenticationValve.java:138)
	at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:68)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.device.mgt.core.operation.mgt.dao.OperationManagementDAOException: Error occurred while adding operation metadata
	at org.wso2.carbon.device.mgt.core.operation.mgt.dao.impl.GenericOperationDAOImpl.addOperation(GenericOperationDAOImpl.java:82)
	at org.wso2.carbon.device.mgt.core.operation.mgt.dao.impl.CommandOperationDAOImpl.addOperation(CommandOperationDAOImpl.java:42)
	at org.wso2.carbon.device.mgt.core.operation.mgt.OperationManagerImpl.addOperation(OperationManagerImpl.java:146)
	... 55 more
Caused by: org.h2.jdbc.JdbcSQLException: Timeout trying to lock table "DM_OPERATION"; SQL statement:
INSERT INTO DM_OPERATION(TYPE, CREATED_TIMESTAMP, RECEIVED_TIMESTAMP, OPERATION_CODE)  VALUES (?, ?, ?, ?) [50200-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.table.RegularTable.doLock(RegularTable.java:516)
	at org.h2.table.RegularTable.lock(RegularTable.java:450)
	at org.h2.command.dml.Insert.insertRows(Insert.java:155)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	at org.wso2.carbon.device.mgt.core.operation.mgt.dao.impl.GenericOperationDAOImpl.addOperation(GenericOperationDAOImpl.java:73)
	... 57 more
[2017-06-06 09:11:26,161] [IoT-Core] ERROR - {org.wso2.carbon.device.mgt.jaxrs.service.impl.DeviceManagementServiceImpl} Error occurred while fetching the operations for the 'ios' device, which carries the id '90b7ac2c11a0e59b2a4217b6625762b829ef0212'
org.wso2.carbon.device.mgt.common.operation.mgt.OperationManagementException: Error occurred while retrieving the list of operations assigned for 'ios' device '90b7ac2c11a0e59b2a4217b6625762b829ef0212'
	at org.wso2.carbon.device.mgt.core.operation.mgt.OperationManagerImpl.getOperations(OperationManagerImpl.java:383)
	at org.wso2.carbon.device.mgt.core.service.DeviceManagementProviderServiceImpl.getOperations(DeviceManagementProviderServiceImpl.java:1189)
	at org.wso2.carbon.device.mgt.jaxrs.service.impl.DeviceManagementServiceImpl.getDeviceOperations(DeviceManagementServiceImpl.java:493)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:188)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:104)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:249)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:289)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:214)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:265)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.device.mgt.jaxrs.ApiOriginFilter.doFilter(ApiOriginFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:615)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.processRequest(WebappAuthenticationValve.java:138)
	at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:68)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.device.mgt.core.operation.mgt.dao.OperationManagementDAOException: SQL error occurred while retrieving the operation available for the device'1' with status '
	at org.wso2.carbon.device.mgt.core.operation.mgt.dao.impl.GenericOperationDAOImpl.getOperationsForDevice(GenericOperationDAOImpl.java:946)
	at org.wso2.carbon.device.mgt.core.operation.mgt.OperationManagerImpl.getOperations(OperationManagerImpl.java:371)
	... 62 more
Caused by: org.h2.jdbc.JdbcSQLException: Timeout trying to lock table "DM_OPERATION"; SQL statement:
SELECT o.ID, TYPE, o.CREATED_TIMESTAMP, o.RECEIVED_TIMESTAMP, OPERATION_CODE, om.STATUS, om.ID AS OM_MAPPING_ID, om.UPDATED_TIMESTAMP FROM DM_OPERATION o INNER JOIN (SELECT * FROM DM_ENROLMENT_OP_MAPPING dm WHERE dm.ENROLMENT_ID = ?) om ON o.ID = om.OPERATION_ID ORDER BY o.CREATED_TIMESTAMP DESC LIMIT ?,? [50200-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.table.RegularTable.doLock(RegularTable.java:516)
	at org.h2.table.RegularTable.lock(RegularTable.java:450)
	at org.h2.table.TableFilter.lock(TableFilter.java:145)
	at org.h2.table.TableFilter.lock(TableFilter.java:147)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:618)
	at org.h2.command.dml.Query.query(Query.java:314)
	at org.h2.command.dml.Query.query(Query.java:284)
	at org.h2.command.dml.Query.query(Query.java:36)
	at org.h2.command.CommandContainer.query(CommandContainer.java:91)
	at org.h2.command.Command.executeQuery(Command.java:196)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:106)
	at org.wso2.carbon.device.mgt.core.operation.mgt.dao.impl.GenericOperationDAOImpl.getOperationsForDevice(GenericOperationDAOImpl.java:927)
	... 63 more
[2017-06-06 09:12:53,955] [IoT-Core] ERROR - {org.wso2.carbon.policy.mgt.core.task.MonitoringTask} Error occurred while trying to run a task.
org.wso2.carbon.device.mgt.common.policy.mgt.monitor.PolicyComplianceException: Error occurred while adding monitoring operation to devices
	at org.wso2.carbon.policy.mgt.core.mgt.impl.MonitoringManagerImpl.addMonitoringOperation(MonitoringManagerImpl.java:360)
	at org.wso2.carbon.policy.mgt.core.task.MonitoringTask.execute(MonitoringTask.java:113)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.device.mgt.common.operation.mgt.OperationManagementException: Error occurred while adding operation
	at org.wso2.carbon.device.mgt.core.operation.mgt.OperationManagerImpl.addOperation(OperationManagerImpl.java:227)
	at org.wso2.carbon.device.mgt.core.service.DeviceManagementProviderServiceImpl.addOperation(DeviceManagementProviderServiceImpl.java:1177)
	at org.wso2.carbon.policy.mgt.core.mgt.impl.MonitoringManagerImpl.addMonitoringOperationsToDatabase(MonitoringManagerImpl.java:420)
	at org.wso2.carbon.policy.mgt.core.mgt.impl.MonitoringManagerImpl.addMonitoringOperation(MonitoringManagerImpl.java:356)
	... 8 more
Caused by: org.wso2.carbon.device.mgt.core.operation.mgt.dao.OperationManagementDAOException: Error occurred while adding operation metadata
	at org.wso2.carbon.device.mgt.core.operation.mgt.dao.impl.GenericOperationDAOImpl.addOperation(GenericOperationDAOImpl.java:82)
	at org.wso2.carbon.device.mgt.core.operation.mgt.dao.impl.CommandOperationDAOImpl.addOperation(CommandOperationDAOImpl.java:42)
	at org.wso2.carbon.device.mgt.core.operation.mgt.OperationManagerImpl.addOperation(OperationManagerImpl.java:146)
	... 11 more
Caused by: org.h2.jdbc.JdbcSQLException: Timeout trying to lock table "DM_OPERATION"; SQL statement:
INSERT INTO DM_OPERATION(TYPE, CREATED_TIMESTAMP, RECEIVED_TIMESTAMP, OPERATION_CODE)  VALUES (?, ?, ?, ?) [50200-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.table.RegularTable.doLock(RegularTable.java:516)
	at org.h2.table.RegularTable.lock(RegularTable.java:450)
	at org.h2.command.dml.Insert.insertRows(Insert.java:155)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	at org.wso2.carbon.device.mgt.core.operation.mgt.dao.impl.GenericOperationDAOImpl.addOperation(GenericOperationDAOImpl.java:73)
	... 13 more
[2017-06-06 09:13:53,953] [IoT-Core] ERROR - {org.wso2.carbon.policy.mgt.core.task.MonitoringTask} Error occurred while trying to run a task.
org.wso2.carbon.device.mgt.common.policy.mgt.monitor.PolicyComplianceException: Error occurred while adding monitoring operation to devices
	at org.wso2.carbon.policy.mgt.core.mgt.impl.MonitoringManagerImpl.addMonitoringOperation(MonitoringManagerImpl.java:360)
	at org.wso2.carbon.policy.mgt.core.task.MonitoringTask.execute(MonitoringTask.java:113)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.device.mgt.common.operation.mgt.OperationManagementException: Error occurred while adding operation
	at org.wso2.carbon.device.mgt.core.operation.mgt.OperationManagerImpl.addOperation(OperationManagerImpl.java:227)
	at org.wso2.carbon.device.mgt.core.service.DeviceManagementProviderServiceImpl.addOperation(DeviceManagementProviderServiceImpl.java:1177)
	at org.wso2.carbon.policy.mgt.core.mgt.impl.MonitoringManagerImpl.addMonitoringOperationsToDatabase(MonitoringManagerImpl.java:420)
	at org.wso2.carbon.policy.mgt.core.mgt.impl.MonitoringManagerImpl.addMonitoringOperation(MonitoringManagerImpl.java:356)
	... 8 more
Caused by: org.wso2.carbon.device.mgt.core.operation.mgt.dao.OperationManagementDAOException: Error occurred while adding operation metadata
	at org.wso2.carbon.device.mgt.core.operation.mgt.dao.impl.GenericOperationDAOImpl.addOperation(GenericOperationDAOImpl.java:82)
	at org.wso2.carbon.device.mgt.core.operation.mgt.dao.impl.CommandOperationDAOImpl.addOperation(CommandOperationDAOImpl.java:42)
	at org.wso2.carbon.device.mgt.core.operation.mgt.OperationManagerImpl.addOperation(OperationManagerImpl.java:146)
	... 11 more
Caused by: org.h2.jdbc.JdbcSQLException: Timeout trying to lock table "DM_OPERATION"; SQL statement:
INSERT INTO DM_OPERATION(TYPE, CREATED_TIMESTAMP, RECEIVED_TIMESTAMP, OPERATION_CODE)  VALUES (?, ?, ?, ?) [50200-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.table.RegularTable.doLock(RegularTable.java:516)
	at org.h2.table.RegularTable.lock(RegularTable.java:450)
	at org.h2.command.dml.Insert.insertRows(Insert.java:155)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	at org.wso2.carbon.device.mgt.core.operation.mgt.dao.impl.GenericOperationDAOImpl.addOperation(GenericOperationDAOImpl.java:73)
	... 13 more

**Comment by chamaraanu** [comment]
This exists in the Alpha pack too..
